### ISSUE TITLE
Time Series modeling

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1004]
Add support for building models on timeseries datasets, which have an ordered date/time column.

We should probably mark this feature as pre-release for the August release.

[Notes here](https://alteryx.quip.com/ezMpAKOanRoA/Timeseries-Design-Notes).

**Comment by freddyaboulton** [comment]
@dsherry and I finalized the implementation plan:

1. Implement TimeSeriesRegression, TimeSeriesBinary, TimeSeriesMulticlass problem_types
    1. This has implications for our objectives
    2. Time Estimate: 2 days
2. Implement gap and max_lag “at the same time”
    1.  TimeSeriesRegression pipeline (handle gap)
    2. and DelayedFeatureExtractor  to handle max_lag 
    3. Time Estimate: 4 days
3. Implement TimeSeriesBinaryClassification and TimeSeriesMulticlassClassification
    1. Time Estimate: 3 days
4. Update AutoML to take-in time-series parameters via problem_configuration
    1.  Updates AutoMLAlgorithm and IterativeAlgorithm
    2. Implement TimeSeriesSplit and integrate into AutoML
    3. Time Estimate: 3 days
5. Add a User Guide entry for Time Series modeling.
    1. Time Estimate: 2 days
6. Gather performance test datasets and run performance tests
    1. Dylan can start this before we finish the previous steps
    2. Time Estimate: 5 days
7. Implement MeanAbsoluteScaledError objective
    1. Time Estimate: 2 days
8. Implement graph_prediction_over_time and functions
    1. Time Estimate: 2 days
9. Implement min_delay either in this phase or the next. 
    1. Time Estimate: 3 days

The goal is:

1 -2, 4 - 6 (automl for regression) done by Nov release
3, 7 - 9 (binary/multiclass) done by Dec release

**Comment by dsherry** [comment]
Discussion with @jeremyliweishih @freddyaboulton : 
* @freddyaboulton doing TS demo on Friday, will try to get #1482 #1258 done for that
* I'll file issues for a few more things: update `make_pipelines`, ARIMA/Prophet/LSTM, add `min_delay`, etc. 
* After that @jeremyliweishih will start looking at adding the TS estimators

**Comment by dsherry** [comment]
@freddyaboulton I filed a few more of the features we discussed from [the future work in the design doc](https://alteryx.quip.com/AM04ASOaQS4v/Time-Series-November-Design-Document#EcTACAj0B4Y). I didn't go too far into the future like interpolation and stuff, but lmk if there's anything major which you think is missing and should be filed.

**Comment by dsherry** [comment]
Outstanding for completion of this phase of timeseries support:
* #1517 
* #1580 
* #1581 
* Merge timeseries yaml into looking_glass
* We can punt on #1384 for now

**Comment by freddyaboulton** [comment]
Closing because #1517, #1580, #1581 have been completed and looking_glass has time series datasets!
