### ISSUE TITLE
Data Splitting Strategy

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1049]
At the moment, evalml has fairly basic support for controlling data splitting. Users can provide automl training data, set a cross-validation object to override our defaults, and control whether or not binary classification pipelines' thresholds will be optimized (which uses a separate split created internally from the training data).

There are a number of considerations around data splitting which need resolution:
* What will evalml's default behavior be?
* What options do we expose to users? Configure training, holdout sizes, CV folds / ordering, enable/disable other splits
* What's the API to expose those options? Does the automl search object know anything about the holdout?
* Should evalml persist data to disk / in memory, to alleviate concerns about access to training data across different API calls? Or should we ask the user to manage that persistence?

We've started [a notes doc here](https://alteryx.quip.com/z9KJAHWFo1Sa/EvalML-Data-Splitting-Notes).

@freddyaboulton @kmax12 @gsheni

**Comment by dsherry** [comment]
@jeremyliweishih what's the status of this?

**Comment by jeremyliweishih** [comment]
@dsherry 

Working on #973 which introduces down-sampling to balance classification targets. #194 looks like a dupe of #973 so the PR (#1266) should cover both these issues. This leaves #648 which I am hoping #1266 will introduce positive changes to. The hypothesis is that balancing classification targets will allow AutoMLSearch to take advantage of threshold tuning and provide better results. ATM working on the performance documents on both down sampling and adding threshold tuning on top of that.

**Comment by dsherry** [comment]
@jeremyliweishih thanks, sounds good! I'll continue discussion on #1266 . Yep looks like #194 and #973 are dups, good call.

**Comment by tyler3991** [comment]
@jeremyliweishih , @dsherry, looks like all of the issues associated with this epic are ice boxed for now. I'm removing it from the "roadmap" view on zenhub for December.

**Comment by dsherry** [comment]
We've merged undersampling, and are working on oversampling. Creating a new epic for that.
