### ISSUE TITLE
Flaky text unit tests

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#1083]
Test `test_featurizer_only_text(text_df)` in file `evalml/tests/component_tests/test_text_featurizer.py` fails due to a reference before assignment. This test fails occasionally, as I ran into it only once out of many runs. 

see: [circleci test](https://app.circleci.com/pipelines/github/FeatureLabs/evalml/5310/workflows/6dd53f78-da54-4ae7-a953-9b9784415eb3/jobs/54457)

Error was: `NameError: free variable 'swords' referenced before assignment in enclosing scope`

**Comment by eccabay** [comment]
`nlp_primitives` [release](https://github.com/FeatureLabs/nlp_primitives/releases/tag/v1.1.0) is done, this issue should be resolved
