### ISSUE TITLE
Ensembling

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1128]
This Epic tracks laying down the initial work necessary to support ensembling.

Design doc here: https://alteryx.quip.com/wcJbAoWJVpAN/Ensembling-Design-Document

**Comment by angela97lin** [comment]
Here's the current status:

The first PR for implementing the stacked ensemble classifier / regressor is ready for and awaiting review (#1134). There was a lot of back-and-forth about how to get the components to work in our pipelines (to prepare for AutoML), and the current solution does this by implementing a basic scikit-learn wrapper and then limiting `n_jobs=1` to avoid the multiprocessing worker failures seen on CircleCI.

Once that PR is reviewed and ready to merge, there are still two more PRs in this epic: #1130 and #1131. Given the amount of time left for September, it is likely that #1134 will be part of the September release, but #1130 and #1131 will be part of the October release.

@dsherry

**Comment by tyler3991** [comment]
#1240 is a bug and is associated with this epic. However, since all feature work is complete in this epic, closing.
