### ISSUE TITLE
Simplify evalml's logging behavior

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1174]
**Background**
Our current logging behavior sets up our default logging pattern: log debug-level stuff to a file, and info-level to stdout. The file location is configurable using the env var `EVALML_LOG_FILE`. [Here's our doc on this](https://evalml.alteryx.com/en/stable/user_guide/utilities.html#Configuring-Logging).

**Discussion**
I like that we have a default logging pattern. It makes it easy for users to get up and running with evalml.

However, what we have now is also too complex. I wouldn't expect a third-party python library to have its own logging behavior--I'd expect that I could control its behavior via the python `logging` package, i.e. changing the log level, creating a file logger, pretty-printing etc.

The question at hand: **How can we simplify our log behavior to make it easy for users to modify evalml's logging behavior?**

Use-cases:
1. User scripting with evalml directly in jupyter/other.
2. User wants to use evalml programmatically, i.e. integrated into their application.

I think we've tailored our logging setup for the first case, but haven't considered the second. In the second case, the parent application could be a python application, or a standalone application. In either case, we should make it easy and clear to change the behavior. One drawback of the current approach is that users need to learn about our env var setup, but it would probably be more intuitive for us to support setting the log level directly using `logging`.

Note this issue also applies to featuretools and the other Innovation Labs-related analytics projects. If we can come up with a good pattern for this, we can update those libraries to do the same.

**Comment by dsherry** [comment]
#1273 was a dup. Note to whoever picks this up: please read #1273 !

**Comment by dsherry** [comment]
@bchen1116 @freddyaboulton and I spent some time debugging a fun issue (filed as #1366). It took longer to debug because the debug log didn't include a stack trace. We should make it so that we log stack traces at debug-level during automl.

**Comment by freddyaboulton** [comment]
> @bchen1116 @freddyaboulton and I spent some time debugging a fun issue (filed as #1366). It took longer to debug because the debug log didn't include a stack trace. We should make it so that we log stack traces at debug-level during automl.

For whoever picks this up, I believe the stacktrace is logged when there is a `PipelineScoreError` but not if the exception occurs outside scoring (fitting, splitting data, optimizing threshold).

**Comment by dsherry** [comment]
A user brought this last point up in #1710 : if a model errors during automl, the message logged out directs users to look at `evalml_debug.log` for a stack trace, but then it turns out there's no stack trace visible there!

**Comment by jeremyliweishih** [comment]
Ask from LG: add the ability to create new log files so that in LG we can send back trial specific logs.
