### ISSUE TITLE
Docstring for `pipeline.feature_importance` is incorrect

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1213]
After #1209, several pipeline base class docstrings are now exposed. However, the `feature_importance` is incorrect:
![image](https://user-images.githubusercontent.com/5422235/94039089-43f05600-fd95-11ea-9030-defb233e5bed.png)

This issue tracks fixing this docstring.

**Comment by dsherry** [comment]
Debugging with @bchen1116 , some changes to try on this branch: `ds_1213_feature_importance_docs_debug`
