### ISSUE TITLE
Lightgbm: add note about libomp to our install docs

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1216]
@cmancuso noticed that lightgbm failed locally for him on his mac until he ran `brew install libomp`:
```
[info] E               Exception: An exception occurred while trying to import `lightgbm`: dlopen(/Users/.../Documents/dev/.../env/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
[info] E                 Referenced from: /Users/.../Documents/dev/.../env/lib/python3.8/site-packages/lightgbm/lib_lightgbm.so
[info] E                 Reason: image not found
```

Let's verify that this is needed in order to use lightgbm, and add a mention of this to our install docs.

RE unit test coverage: our CI jobs run on windows and linux, not mac. That said, let's verify that we have unit tests which would at least fail locally on mac if `libomp` is missing.

**Comment by bchen1116** [comment]
@dsherry Do you mean to add unit tests that would fail if `libomp` is missing, or do you mean that we should check whether the `LightGBM` tests fail when `libomp` is missing?

**Comment by dsherry** [comment]
@bchen1116 the latter. Our CI jobs don't run on mac right now, and I don't think we should try to set up a mac-based CI job today. I was suggesting let's make sure that if `libomp` is missing locally on your mac, we have at least one unit test which would fail, and our docs mention the requirement.

So:
* Verify that you have `libomp` installed on your machine.
* Run all the unit tests locally, verify they all pass.
* Uninstall `libomp` on your machine
* Run all the unit tests locally, note which fail
* If at least one fails, we've verified that `libomp` is required install on mac in order for lightgbm to work. We should add a note about this to [our install guide](https://evalml.alteryx.com/en/stable/install.html) -- can create "Mac" section at bottom.
* If none fail, we should follow up with Chris and try to understand what happened

**Comment by bchen1116** [comment]
@dsherry gotcha. The tests for LightGBM do fail when `libomp` isn't installed, and pass when it is. Creating the PR now.
