### ISSUE TITLE
Add DataChecks to the User Guide

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1227]
As an evalml user, I'd like a guide on how to work with the `DataChecks` class. Currently, the [docs](https://evalml.alteryx.com/en/stable/user_guide/data_checks.html) only talk about individual `DataCheck` subclasses.

This came out of a discussion on #1167

**Comment by angela97lin** [comment]
Closed by #1412
https://evalml.alteryx.com/en/latest/user_guide/data_checks.html#Defining-Collections-of-Data-Checks
