### ISSUE TITLE
`TerminatedWorker` error when running StackedEnsemble components on CircleCI with `n_jobs!=1`

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1240]
#1134 added two new StackedEnsemble components, but with a caveat: `n_jobs = 1` is a must to prevent running into odd CircleCI errors (see [here](https://app.circleci.com/pipelines/github/alteryx/evalml/6059/workflows/7c03ae25-1941-4852-aa61-7fbb87bc6f0b/jobs/64413)).

This is obviously a limitation, and we should try to figure out the underlying issue! I could not repro this on my local machine, nor my SSH'ing into a failed job's environment.

Potentially relevant issue: scikit-learn-contrib/skope-rules#18

Issue could be related to our scikit-learn wrapper and figuring out how to make our wrapper object scikit-learn compliant (passes `check_estimator`). I tried looking into what extra work would be necessary to do so but I think there would be a lot that would have to change with our current API (for pipelines) before we could make this work.

**Comment by dsherry** [comment]
Workaround: keep `n_jobs` at 1 for stacked ensembler.

@bchen1116 tried to repro but couldn't.

@angela97lin let's discuss.

**Comment by angela97lin** [comment]
Closed via #1472!
