### ISSUE TITLE
CircleCI: auth needed for Docker Hub as of Nov 1st

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1260]
Message which @jeremyliweishih posted in slack today (thanks Jeremy!):
> Hi there,
> On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.
> Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
> We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them.
> For more information or to leave a question for us, please head over to Discuss or contact support.
> Thanks and happy building,
> - The CircleCI team

Next step: determine what if any action is needed in order for our CI jobs to continue uninterrupted.

@rwedge @gsheni FYI this may affect CI for featuretools/compose/woodwork/others as well

**Comment by dsherry** [comment]
@tyler3991 has been looking into this! Thanks :)

**Comment by tyler3991** [comment]
looking at getting a Docker "[Team](https://www.docker.com/pricing)" account so we have authenticated user pulls from Docker Hub. 

@rwedge, @gsheni, @dsherry are also in the loop. Starting by requesting one user account. Let me know if you think I should go a different route. I know Docker team is 5 user minimum. Its likely Alteryx would use other 4 in other places. I can get more if needed.

**Comment by dsherry** [comment]
Oops, #1356 closed this. Closing!
