### ISSUE TITLE
EvalML Attempts to Create Model when Provided an incompatible target variable/problem combination

### ISSUE THREAD

**Issue by SydneyAyx** [alteryx/evalml#1271]
When you feed a numeric target variable in as a multiclass classification problem, EvalML will generate a model pipeline (after searching) with all nan objective function values. It would be nice to have a data check that confirmed the problem type is appropriate for the target varibale.

**Comment by freddyaboulton** [comment]
@SydneyAyx Can you post a repro? Is the issue that you passed a target for multiclass where the classes are encoded as ints and the scores should not be nan or that you passed in a regression target for a multiclass search and the search failed silently?

**Comment by SydneyAyx** [comment]
The first situation, apparently (target for multiclass where the classes are encoded as ints and scores should not be nan). This is reproducible with the abalone dataset with "rings" as the target.

**Comment by dsherry** [comment]
We have a data check for class imbalance, `ClassImbalanceDataCheck`. But, it appears we didn't yet add it to `DefaultDataChecks` for inclusion in automl! I filed #1276 for that. Closing this in favor of that issue. Thanks @SydneyAyx !
