### ISSUE TITLE
Update ensemble pipelines to use a DAG, instead of passing sub-pipeline instances via params

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1281]
**Background**
Currently our pipelines' component graphs are represented as a linear sequence of steps. This works fine for use-cases which are conducive to this limitation, but not as great for complex pipelines.

In order to add support for ensembling in #1128, we had to implement a workaround: the parameters dict for ensembles will contain pipeline instances (containing the parameters for each). (@angela97lin )

Work is currently underway in #273 to allow pipeline graphs to be specified as directed acyclic graphs (DAGS) instead of as linear sequences (@eccabay )

**Description**
This issue tracks updating ensemble pipelines to define a graph where each sub-pipeline in the ensemble is an input to the final ensemble estimator. We can start this once pipelines as DAGS (#273) is complete.

**Comment by dsherry** [comment]
We're marking this as blocked on #1930 . Otherwise, we'd have to do a lot of plumbing to make sure the input pipelines get passed into the estimator correctly. We think that plumbing will get much easier if we implement our own stacked ensembler first.

Another consideration here too: what if we want to train / predict each pipeline on each fold on separate workers?

**Comment by dsherry** [comment]
@christopherbunn is this issue completed or is it still in progress?

**Comment by christopherbunn** [comment]
Yep! With the completion of #1930, ensembler pipelines are now represented as DAGs.
