### ISSUE TITLE
Add documentation for Woodwork support

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1287]
This issue tracks adding documentation about what types we expect categorical, numeric and text to be set to in order for automl to treat features correctly, as well warn users what may happen if users pass in pandas DataFrames / numpy arrays.

Design doc for epic here: https://alteryx.quip.com/Oa4aA6h0Rf2k/Woodwork-DataTable-Integration-Design-Document

**Comment by dsherry** [comment]
Tracks:
* Update automl user guide, describe how to use woodwork
* Update all automl examples, start page
* Make sure API ref looks good
