### ISSUE TITLE
Update pipelines and all components to accept Woodwork DataTables

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1288]
Design doc for epic here: https://alteryx.quip.com/Oa4aA6h0Rf2k/Woodwork-DataTable-Integration-Design-Document

**Comment by dsherry** [comment]
We should also update `make_pipeline` to accept datatables, and delete `text_features` input, [RE this line](https://github.com/alteryx/evalml/pull/1062/files#diff-8b4df814812e6f5df24c600bc7f429b036e0e2f78613bfbdcdf0ed3ab86bffd6R421) in the text PR.
