### ISSUE TITLE
Update components from selecting using pandas dtypes to selecting using DataTable semantic or logical types

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1290]
Design doc for epic here: https://alteryx.quip.com/Oa4aA6h0Rf2k/Woodwork-DataTable-Integration-Design-Document

**Comment by dsherry** [comment]
Note that we'll want to pay special attention to the text featurizer component. Currently (as in #1062 ), it expects a list of text features to be passed in via the parameters dict. Now that we have woodwork in place, we should remove that behavior in favor of doing `dt.select('natural_language')` in fit and transform. For consideration: we could keep the `text_features` params input as optional, if specified would override the woodwork datatable content. Or we could simply use the datatable.

**Comment by dsherry** [comment]
@angela97lin will #1423 close this issue? If not, what's left after that's merged? I just saw your comment about [the datetime featurizer](https://github.com/alteryx/evalml/pull/1423#discussion_r525388736).

**Comment by angela97lin** [comment]
@dsherry I don't think in all cases (such as the datetime featurizer), so this issue tracks any dangling conversions we have yet to make, as well as (hopefully) completely getting rid of the dtype lists we have (`numeric_dtypes`,`boolean`, `numeric_and_boolean_dtypes`, etc.)

**Comment by dsherry** [comment]
@angela97lin understood, thanks!
