### ISSUE TITLE
Add Alteryx footer to EvalML documentation page

### ISSUE THREAD

**Issue by tyler3991** [alteryx/evalml#1305]
### Add Alteryx footer to EvalML documentation page

-----

#### Description

We would like to add an Alteryx branded footer to the bottom of all of our open source libraries. 

* Banner color = HEX #0D2345
* Github / Twitter icons added to footer
* Contrary to artwork shown, the footer should only show up when you scroll to the very bottom of the page
* Compose is already changed! That can be used as a template. 
* Github does not like SVG. Reach out to @tyler3991  for the "Alteryx Open Source" and copyright SVG. 

#### Expected Output

![image](https://user-images.githubusercontent.com/3720375/95996022-70751c00-0def-11eb-9df3-5e689678dccb.png)

**Comment by dsherry** [comment]
[Here's the compose PR](https://github.com/FeatureLabs/compose/pull/185) from @jeff-hernandez (thanks!)

**Comment by tyler3991** [comment]
Hey @gsheni , wanted to throw this out there just in case you want to do something similar. In FeatureTools, I noticed Jeff and Roy consolidated all of the images into a `docs/source/_static/images`, removing the `images` folder from `docs/source`. 

https://github.com/FeatureLabs/featuretools/pull/1189#discussion_r505891527
