### ISSUE TITLE
Add heuristic-based column dropping component

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#1315]
While we have a number of data checks that will raise errors if the input data is, for example, highly null or has no variance, users may not want to have to clean their data themselves. A simple way to reduce dimensionality is to just drop these sorts of columns, using a component that contains multiple of these filters. The filters I think should be included are:
- Missing Value Ratio (stemming from highly null data check)
- Low Variance Filter (stemming from no variance data check)
- High Correlation Filter

**Comment by dsherry** [comment]
Closing, we have data check actions on our roadmap.
