### ISSUE TITLE
Data checks: make it easier to process results

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1325]
Currently, the data check messages are returned as a list of `DataCheckMessage` objects, which can either be errors or warnings.

This achieves the goal of delivering the data check errors and warnings to users. But the current return format makes it hard to work with the results--we should update the API to make it easy.

Use-cases we should bear in mind here:
* User wants to get a list of all errors, or a list of all warnings, but not both
* User wants to know if there's been at least one error or warning (perhaps redundant with the above)
* User wants to combine multiple errors into a single string message, to raise an exception / display

**Comment by angela97lin** [comment]
Ideas:
- Return two lists: errors, warnings
- Return dictionary {"errors": list of errors, "warnings": list of warnings}

**Comment by dsherry** [comment]
I like the dict! Keeps us flexible if we change the message types. Let's use [the `DataCheckMessageType` enum](https://github.com/alteryx/evalml/blob/main/evalml/data_checks/data_check_message_type.py#L4) as the keys.
