### ISSUE TITLE
Remove `core-requirements.txt` from installed package

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1328]
https://github.com/alteryx/evalml/pull/1293 updated and fixed our CLI tool by adding `core-requirements.txt` to our package data so it is readable. However, users may be confused as to why this is being installed. We should look into how to achieve the same functionality without adding `core-requirements.txt` to our installed package.

**Comment by dsherry** [comment]
Yep, for context for whoever picks this up, we decided it was worth merging the fix, including `core-requirements.txt` in our packaging in order to satisfy codecov and to fix the env CLI tool before the next release. This issue tracks paying down that tech debt :)
