### ISSUE TITLE
Add `_pipelines_per_batch` as a private parameter for AutoML Search

### ISSUE THREAD

**Issue by christopherbunn** [alteryx/evalml#1339]
Per [this comment](https://github.com/alteryx/evalml/pull/1320#discussion_r510365714), we should put `_pipelines_per_batch` as a private automl search parameter.

**Comment by dsherry** [comment]
Thanks @christopherbunn . Yep, this would be helpful to have exposed for perf testing, but we don't wanna commit to making it public and keeping it around until we've had more time to bake on it.
