### ISSUE TITLE
Should clone copy the random state by default?

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1340]
In #1321, we had to modify the pipeline.clone call in `_compute_cv_scores` to pass in the random state of the automl search object - without this the pipeline always get init with random state 0. 

Comments from the original PR:

Yep

RE your comment in standup this week: @eccabay and I chose this behavior because we felt copying random_state under the hood was dirty. However, in light of our recent conversation about #1324 (component/pipeline determinism), perhaps we should revisit this, and have `clone` copy `random_state` by default. Do you have thoughts @freddyaboulton @eccabay ? We can move the discussion to an issue and resolve there.

_Originally posted by @dsherry in https://github.com/alteryx/evalml/pull/1321#discussion_r510911430_

**Comment by freddyaboulton** [comment]
Maybe we should rename just `clone` to `new` and keep the api as is? Clone makes me think I'd get an **exact** copy of the pipeline but in reality I'm getting a new version of the pipeline (whether or not the components are fit is not carried over to the new pipeline).

**Comment by dsherry** [comment]
In #1719 we're removing support for `numpy.random_state.RandomState` instances as input to evalml -- only integer seeds will be supported as input moving forward. We did this to simplify our code and tests and to avoid hairy bugs.

I think that will make this issue easier to tackle. I think we should have `clone` copy over that random seed.

@freddyaboulton @bchen1116 thoughts?

**Comment by freddyaboulton** [comment]
Yep that sounds good to me @dsherry !
