### ISSUE TITLE
Pandas warning appears when using breast cancer demo dataset

### ISSUE THREAD

**Issue by christopherbunn** [alteryx/evalml#1344]
Likely related to the internal conversion of input data to Woodwork tables. 
 
![image](https://user-images.githubusercontent.com/8752455/97052490-1858bb00-154f-11eb-8785-472d4bc5ca82.png)

**Comment by christopherbunn** [comment]
This might actually be a Woodwork issue, as when I comment out [this line](https://github.com/FeatureLabs/woodwork/blob/b77e6eda4c83d30c05e2f1730e160c1787de72a6/woodwork/data_table.py#L164) the warning disappears.

**Comment by gsheni** [comment]
While, Woodworks tries to fix this buy, you can temporarily do the following at this [line](https://github.com/alteryx/evalml/blob/4c9e5a99d420213aac21ab63a1459a626cb326bc/evalml/automl/automl_search.py#L390)
```python
            X = ww.DataTable(X, copy_dataframe=True)
```

**Comment by dsherry** [comment]
Thanks @gsheni and @thehomebrewnerd! Sure, I think that'll be fine for now. Note that copying here will slow down automl search a bit for larger datasets when woodwork is used for input instead of pandas.

FWIW I wasn't able to repro this locally when I tried real quick. Perhaps I was missing something.

**Comment by christopherbunn** [comment]
Per [this comment](https://github.com/alteryx/evalml/pull/1358#issuecomment-718870228), the inclusion of featuretools with [the TextFeaturizer PR ](83343aa85b2bc9ec272b52c1151e35bce041def9) silences this error. On main as of today, this error is not reproducible.
