### ISSUE TITLE
explain_prediction functions display scaled feature values when pipeline has a standard scaler

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1359]
Repro:

```python
from evalml.model_understanding.prediction_explanations import explain_predictions_best_worst

import evalml

class RFBinaryClassificationPipeline(evalml.pipelines.BinaryClassificationPipeline):
    component_graph = ['Simple Imputer', 'Standard Scaler', 'Random Forest Classifier']
    

X, y = evalml.demos.load_breast_cancer()

pipeline = RFBinaryClassificationPipeline({})
pipeline.fit(X, y)

report = explain_predictions_best_worst(pipeline=pipeline, input_features=X, y_true=y,
                                        include_shap_values=True, num_to_explain=2)

print(f"Min worst perimeter feature value {X['worst perimeter'].min()}")
print(report)
```

Output:
```
Min worst perimeter feature value 50.41
RFBinary Classification Pipeline

{'Simple Imputer': {'impute_strategy': 'most_frequent', 'fill_value': None}, 'Random Forest Classifier': {'n_estimators': 100, 'max_depth': 6, 'n_jobs': -1}}

	Best 1 of 2

		Predicted Probabilities: [benign: 0.0, malignant: 1.0]
		Predicted Value: malignant
		Target Value: malignant
		Cross Entropy: 0.0

		     Feature Name         Feature Value        Contribution to        SHAP Value
		                                                 Prediction                     
		================================================================================
		    worst perimeter           1.43                    +                  0.10   
		     worst radius             1.42                    +                  0.08   
		 worst concave points         0.88                    +                  0.08   
		worst fractal dimension       0.50                    -                 -0.00   
		   compactness error          0.61                    -                 -0.00   
		    worst symmetry            -1.20                   -                 -0.00   
```

Users may be confused when they see this output - we should show the original feature value. This issue, along with #1347, falls under the theme of mapping the explanations for the features the estimator sees to the features the user input into the pipeline. 

FYI @kmax12

**Comment by kmax12** [comment]
in practice, i think this only comes up with linear models since other models we include don't need this scaling

what if, as a simple fix for now, we just add standard scaling functionality inside our linear model components and removed this component? we could actually still keep this component around, we just wouldn't need to include in any pipeline we create in automl to avoid the specific problem here. 

we could then try solve this problem more generally in conjunction with something like #1347

**Comment by chukarsten** [comment]
Iced : we have mostly tree based models that don't care about scaling.  Not high priority.

**Comment by angela97lin** [comment]
This came up in conversation with @freddyaboulton and @fjlanasa, who wanted to display the original feature value for pipelines with linear estimators. While it seems like there's a way to work around it (grab from original df using index and column), could be worth talking about again :)
