### ISSUE TITLE
Some jobs don't appear in `get-jobs`

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1372]
I noticed that job_id 176 is listed in prod, but not job_id 175, or 177 which I just kicked off. However, I see stuff running in ECS, and running `get-job` with any of those IDs works fine.

I tried setting the `--results-per-page` flag to 1000, but still couldn't see the missing jobs

**Comment by angela97lin** [comment]
@dsherry Is this supposed to be filed in looking glass? 😂
