### ISSUE TITLE
Add a user guide or tutorial page for time series regression

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1384]
We should show how to run AutoMLSearch on a time series regression dataset and how to visualize predictions with `graph_prediction_vs_target_over_time` .

**Comment by dsherry** [comment]
@freddyaboulton what's the status of this?

**Comment by freddyaboulton** [comment]
@dsherry We agreed to punt while we did other time series features! 

https://github.com/alteryx/evalml/issues/1004#issuecomment-755789562

**Comment by dsherry** [comment]
@freddyaboulton ahh yes, thank you :)
