### ISSUE TITLE
Cannot pickle pipelines from automl

### ISSUE THREAD

**Issue by kmax12** [alteryx/evalml#1400]
Trying to pickle a pipeline created by automl.search give this error 

```
AttributeError: Can't pickle local object 'make_pipeline.<locals>.GeneratedPipeline'
```

Reproduce with any dataset

```python
import evalml
import pandas as pd
import pickle 

df = pd.read_csv("/Users/james.kanter/Downloads/housing.csv")
automl = evalml.AutoMLSearch(problem_type="regression", max_iterations=2)
X = df.copy()
y = X.pop("SalePrice")
automl.search(X, y)
pickle.dumps(automl.best_pipeline)
```

This came up because I was trying to deploy a model using https://github.com/bentoml/BentoML/ which relied on pickle in the example I was trying to use.

**Comment by angela97lin** [comment]
@kmax12 Yup, makes sense given `GeneratedPipeline` is a local class. Would [saving/loading](https://evalml.alteryx.com/en/stable/generated/methods/evalml.automl.AutoMLSearch.save.html#evalml.automl.AutoMLSearch.save) the automl object (and then getting the best pipeline) be a sufficient workaround? 

So something like:
```
import evalml
import pandas as pd
import pickle 

df = pd.read_csv("/Users/james.kanter/Downloads/housing.csv")
automl = evalml.AutoMLSearch(problem_type="regression", max_iterations=2)
X = df.copy()
y = X.pop("SalePrice")
automl.search(X, y)
automl.save('pickled_automl')
automl.load('pickled_automl').best_pipeline
```

**Comment by kmax12** [comment]
in this case, no since I'm trying to only deploy the single pipeline and I don't have a concept of automl any more. 

this isn't pressing right now, I think we might need to consider a way define pipelines without the locally generated class. for example

```python
p = evalml.Pipeline(
    problem_type="regression",
    components=[Component1(param1="val1"),
                Component2(param1="val1"), ...])
```

basically a class that has similar init args to `make_pipeline_from_components`.
