### ISSUE TITLE
Lightgbm errors on HIV dataset

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1435]
From Oct 2020 blitz feedback. @freddyaboulton this was something you had mentioned I believe. Do you have a stack trace handy and/or a link to the dataset?

**Comment by freddyaboulton** [comment]
@dsherry I was getting `[LightGBM] [Fatal] Do not support special JSON characters in feature name.`

![image](https://user-images.githubusercontent.com/41651716/99119796-d2c86480-25c7-11eb-841b-0ba93e955798.png)

However, the dataset doesn't have weird column names (`feature_1`, `feature_2`, ...) and I can't reproduce this locally. This may be a performance test bug? FWIW, I downloaded the dataset from S3 and tried running AutoML locally and I still couldn't reproduce. Not sure what's going on. It could have been a one-time thing with downloading the data from S3 from one of the workers.

**Comment by dsherry** [comment]
Thanks! And thanks for trying to reproduce. If we're not able to repro this, and haven't noticed it since, we should close it.
