### ISSUE TITLE
Verify input support for lists in objectives/components/pipelines/automl

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1456]
We should verify if list inputs work for objectives/components/pipelines/automl.

Originally from https://github.com/alteryx/evalml/pull/1450#discussion_r528741774

I believe lists may work because `_convert_to_woodwork_structure` handles the list data type, but in objectives, we call `_standardize_input_type` which doesn't.

**Comment by bchen1116** [comment]
@angela97lin @dsherry Does this mean that we want to make sure components work if we pass in lists to `fit_transform()` or `predict_proba()`? Having our objectives makes sense, but I'm not sure if this means that for all class functions, if we can accept `pd/ww` data structures, we'd want to also be able to accept lists and numpy arrays?
