### ISSUE TITLE
Show only top unique values rather than all unique values for InvalidTargetDataCheck

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1460]
Follow-up from this discussion: https://github.com/alteryx/evalml/pull/1451#discussion_r529023943

In the case where the user accidentally specifies a classification problem type for a regression data set, our checks will blow up trying to list all of the unique values. To prevent this, we could only show the top 100 (or so) unique values instead.

**Comment by angela97lin** [comment]
@dsherry I took another look at this; we only specify the unique values when the number of unique values = 2, so we don't have to worry about the message blowing up. 

```
        if self.problem_type == ProblemTypes.BINARY and len(value_counts) != 2:
            messages["errors"].append(DataCheckError(message="Target does not have two unique values which is not supported for binary classification",
                                                     data_check_name=self.name,
                                                     message_code=DataCheckMessageCode.TARGET_BINARY_NOT_TWO_UNIQUE_VALUES,
                                                     details={"target_values": unique_values}).to_dict())

        if len(value_counts) == 2 and y.dtype in numeric_and_boolean_dtypes:
            if set(unique_values) != set([0, 1]):
                messages["warnings"].append(DataCheckWarning(message="Numerical binary classification target classes must be [0, 1], got [{}] instead".format(", ".join([str(val) for val in unique_values])),
                                                             data_check_name=self.name,
                                                             message_code=DataCheckMessageCode.TARGET_BINARY_INVALID_VALUES,
                                                             details={"target_values": unique_values}).to_dict())
```

Following the data check API update, we now store the values though. We could update this issue to track printing out the top 100 or so unique values, store only the top 100 or so, or do nothing at all. Thoughts?

**Comment by dsherry** [comment]
@angela97lin ah right, thanks. My vote: keep the messages as-is and store the top `n_unique` unique values (default 100) in `details`. I don't think its important for that threshold to be configurable, but that would be nice to have.

**Comment by angela97lin** [comment]
@dsherry Got it, will do! I'll add `n_unique` as a new parameter :)
