### ISSUE TITLE
Add thread count parameter to Catboost/XGBoost estimators

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1475]
Catboost allows users to specify a[ `thread_count` parameter](https://catboost.ai/docs/concepts/python-reference_parameters-list.html#python-reference_parameters-list) on init. Out Catboost estimators can accept `thread_count` as a kwarg, but since it is not a named argument, our automl algorithm won't create the component with the [user's desired level of parallelism](https://github.com/alteryx/evalml/blob/main/evalml/automl/automl_algorithm/iterative_algorithm.py#L137). 

It looks like the default value of `thread_count` is -1 for all available threads. I think in most cases this is what's desired but I think it would be useful for users if we properly document this parameter and make sure automl sets it to the right value.

`thread_count` can help if the user specifies a large number of estimators:
![image](https://user-images.githubusercontent.com/41651716/100631091-5c32a300-32f9-11eb-9a71-006e43665726.png)

evalml's Catboost estimators fail automl's `n_jobs` check:

```python
import inspect
params = inspect.signature(EvalmlCatBoost.__init__).parameters
assert 'n_jobs' not in params
```

The same can be said for [XGBoost](https://xgboost.readthedocs.io/en/latest/parameter.html)

**Comment by chukarsten** [comment]
Iced:  Nice to have, but a little niche use case.
