### ISSUE TITLE
Clean up custom objective function demos

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1491]
Both our fraud and lead scoring notebooks try to go through examples where optimizing for custom objectives introduces a better performing model for the use case. However, the actual outputted results no longer better in the case of FraudCost (https://evalml.featurelabs.com/en/stable/demos/fraud.html#Why-optimize-for-a-problem-specific-objective?) and different than what's written for lead scoring.

We should investigate: what happened that now fraud cost produces the same results regardless of optimizing for an objective? What changed about our search that we are no longer performing better?

EDIT: Cost benefit matrix is also showing the same score :thinking:

**Comment by dsherry** [comment]
This issue tracks updating the lead scoring and fraud demos so that we aren't claiming something untrue.

Lead scoring demo currently claims
> When we optimize for AUC, we can see that the AUC score from this pipeline is better than the AUC score from the pipeline optimized for lead scoring. However, the revenue per lead gained was only $7 per lead when optimized for AUC and was $45 when optimized for lead scoring. As a result, we would gain up to 6x the amount of revenue if we optimized for lead scoring.

However this doesn't match the current numbers.

**Comment by bchen1116** [comment]
Closing since I fixed the documentation with PR [2139](https://github.com/alteryx/evalml/pull/2139)
