### ISSUE TITLE
Pipeline/Estimator predict: include the target name

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1493]
If the input data included a name for the `y` input to `fit`, we should include that name in the output of `predict`.

RE discussion with @gsheni @kmax12 @angela97lin

**Comment by angela97lin** [comment]
@dsherry I'm thinking about potential APIs for this. Based on the discussion raised by @gsheni and @kmax12 we should update the `.input_feature_names` value held our pipelines to hold both the feature column names, as well as the target name.

Currently, `.input_feature_names` returns a dictionary, where the keys are the components and the corresponding values are the feature names that the component gets. We could update this to be a tuple, where the first element of the tuple is the current list of feature names, and the second element of the tuple is the name of the target.

That is, currently we have something like:
```python
{"OHE": ["col1", "col2", "col3"], "Imputer: ["col1_1", "col1_2", "col2", "col3"]}
```
We could update this to:
```python
{"OHE": (["col1", "col2", "col3"], "target"), "Imputer: (["col1_1", "col1_2", "col2", "col3"], "target")}
```

I don't see the target name changing, so maybe this is a bit silly, but it also keeps the nice structure we have now where we keep track of what every component sees.
