### ISSUE TITLE
Time series regression: add Prophet estimator

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1499]
We have done preliminary work in #1766 but did not merge as `pystan` has a `GPL3` license. We can move this issue forward once we solve the licensing issue.

- Add ProphetRegressot component
- Adding ProphetRegressor to AutoML
- Run performance tests to verify behavior
- Add installation instructions to docs (windows and linux)

https://facebook.github.io/prophet/

**Comment by jeremyliweishih** [comment]
Having issues with py3.6 windows tests but dropping py3.6 in #1712 should solve it!

**Comment by dsherry** [comment]
Conclusion: we could split this out into a separate repo, or wait for a licensing change.

**Comment by dsherry** [comment]
It appears we were incorrect about the licensing! PyStan 3 uses the ISC license.

https://discourse.mc-stan.org/t/pystan-license/274/34
https://github.com/stan-dev/pystan/blob/main/LICENSE

**Comment by dsherry** [comment]
Status update: @ParthivNaresh 's draft PR is almost ready for review. There are two details remaining:
* We need to figure out how to get the ReadTheDocs build to pass. It seems like the easiest way to do so is to figure out a way to install prophet during that build.
* There's some evidence to suggest that we won't be able to install prophet on windows. Once we address the ReadTheDocs failure above, we need to learn whether a) making a similar update to the windows CI allows it to work properly, or b) if we should file a separate issue for prophet windows support, prevent the prophet tests from running on windows and merge what we have.

@ParthivNaresh is going to set up a meeting for next week to discuss those problems and our options for addressing them.
