### ISSUE TITLE
Allow X to be None in Time Series Pipelines

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#1517]
In previous EvalML pipelines we have always made the assumption that `X` cannot be `None`. However, with the addition of the `TimeSeriesBaselineRegressor` and plans to add more estimators that rely only on `y` (such as ARIMA, PROPHET) we can revise this assumption for TimeSeriesRegressionPipelines. 

This issue keeps track of:

1. Removing the `ValueError` from `TimeSeriesRegressionPipeline.fit` and accommodating for an empty `X`
2. Removing the overridden `fit` method in `TimeSeriesBaseLineRegressionPipeline` as that was put in as a patch to solve this problem

**Comment by freddyaboulton** [comment]
Thanks for filing @jeremyliweishih ! Yea I think we should remove the exception from `TimeSeriesRegressionPipeline.fit`! For context, here is the discussion where we decided to add it in the first place. 

https://github.com/alteryx/evalml/pull/1418#discussion_r522397434
