### ISSUE TITLE
Write tests to ensure component parameters are JSON-serializable

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#1526]
Currently, all component params are JSON-serializable. We want to write tests to ensure that these and future params remain serializable in order for code generation to work. 

Link to discussion [here](https://github.com/alteryx/evalml/pull/1524#discussion_r538548153)

**Comment by dsherry** [comment]
@bchen1116 what's an example of a non-JSON-serializable type which we'd want to add to the pipeline parameters dict and to component parameters?

**Comment by chukarsten** [comment]
@bchen1116 @dsherry : Any updates on this one?

**Comment by bchen1116** [comment]
@chukarsten I believe DateTime objects, which could be introduced in future components (time series, for example), aren't JSON serializable. 
![image](https://user-images.githubusercontent.com/22552445/106180458-4eb75f00-616a-11eb-9e43-d799cfc64863.png)
Additionally, if we ever add components that can take in estimators/python objects as inputs. These were just things that came to the top of my head, but I think it's just a nice check to have

**Comment by dsherry** [comment]
@bchen1116 understood, thanks.

For datetimes, we could convert to string.

Your comments about estimators reminded me of #1281. Once we address that issue, we won't have any pipelines which pass estimators as parameters -- now that we have a proper DAG pipeline datastructure, that should be done via the component graph itself.

For now, let's declare that we don't support non-JSON-serializable objects in parameters dicts. I suggest we close this until we have a need to support this, or get the feature request from outside.
