### ISSUE TITLE
InvalidTargetDataCheck: make problem_type type checking smarter

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1548]
Right now, in `InvalidTargetDataCheck`, we have:
```
        valid_target_types = [dtype for dtype in numeric_and_boolean_dtypes + categorical_dtypes]
        if y.dtype.name not in valid_target_types:
```

This covers all of the types we handle. However, we can also take into consideration the `problem_type` attribute to be smarter about this--for example, if problem type is regression, and the target has categorical data.

**Comment by dsherry** [comment]
Thanks @angela97lin ! Agreed. RE our discussion on #1551 , it would be helpful if the data check errored if
* For regression, the problem type was not "numeric"
* For binary, the problem type was "categorical" (but first we should confirm that if a categorical column has only two unique values (other than `nan`) woodwork will label it as binary, not as "categorical"
* For multiclass, the problem type was binary
* For multiclass, the problem type had a high number of unique values--perhaps set a max cap at over 5%
