### ISSUE TITLE
Implement mutual information util method

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1557]
#1515 adds a data check to check for multicollinearity, but could be useful to have a util method for calculating mutual info.

Alternatively: is this something that evalml should do, or should this not be within the scope of evalml since it's purely a data-driven method (nothing to do with modelling)?

**Comment by dsherry** [comment]
@angela97lin what's the use-case here, and what could the API look like?

**Comment by angela97lin** [comment]
@dsherry Use case is, user wants to know the mutual information score for the features in their dataframe before doing any modelling / using AutoML. Could be as simple as:
```
def mutual_info(X):
    # Returns dict of col, col with mutual info score
```


However, I hesitate because technically this isn't modelling specific, so maybe we don't want to include it in EvalML and are okay with users just using a different library (such as Woodwork) if they want this.

**Comment by angela97lin** [comment]
Closing this since woodwork has a great mutual_information method, so I'm not sure there's much to add in EvalML!
