### ISSUE TITLE
Code generation for nonlinear pipelines

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#1563]
Currently, the codegen implementation returns a list of a pipeline's component graph. This doesn't work when the component graph is a dictionary, so with PR #1543 this will raise an error as a short term solution. The long term solution should be to support pipeline component graphs that are dictionaries.

**Comment by dsherry** [comment]
First step: confirm that codegen works for linear pipelines.

Next step: try a nonlinear pipeline and see what is it about codegen which breaks.

**Comment by angela97lin** [comment]
Note: this will be resolved by #2332!
