### ISSUE TITLE
Support iterating over pipelines for component iteration

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#1571]
As [discussed](https://github.com/alteryx/evalml/pull/1543#discussion_r544446628) in PR #1543, there is a slight breaking change introduced there where you can no longer iterate through component instances with `Pipeline.component_graph`. @freddyaboulton suggested we support iterating through the components using the pipeline directly, mirroring what the private `ComponentGraph` class does now.

This will involve implementing a pipeline iterator and updating the current code to reflect this change, as well as updating the docs to match.

**Comment by dsherry** [comment]
Whoever picks this up, please look at Becca's PR and decide what needs to happen. Should we merge it or close it?
