### ISSUE TITLE
Impute NaNs for natural language features

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1587]
In #1492, we realized the `LSA` transformer errors when there are NaNs in one of the feature columns. Should the `LSA` transformer handle NaNs "gracefully" like the `nlp_primitives` used in the `TextFeaturizer` or should we update the `Imputer` to impute text columns?

This is the reproducer/original comment on #1492 that lead us to open this issue:

I think the root cause is that there are NaNs in the `job` column and this causes the `TfidfVectorizer` in LSA to crash. You can reproduce this locally:

```python
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import woodwork as ww
from urllib.request import urlopen
customers_data = urlopen('https://featurelabs-static.s3.amazonaws.com/lead_scoring_ml_apps/customers.csv')
interactions_data = urlopen('https://featurelabs-static.s3.amazonaws.com/lead_scoring_ml_apps/interactions.csv')
leads_data = urlopen('https://featurelabs-static.s3.amazonaws.com/lead_scoring_ml_apps/previous_leads.csv')
customers = pd.read_csv(customers_data)
interactions = pd.read_csv(interactions_data)
leads = pd.read_csv(leads_data)

X = customers.merge(interactions, on='customer_id').merge(leads, on='customer_id')
y = X['label']
X = X.drop(['customer_id', 'date_registered', 'birthday','phone', 'email',
            'owner', 'company', 'id', 'time_x',
            'session', 'referrer', 'time_y', 'label', 'country'], axis=1)
TfidfVectorizer().fit_transform(X['job'])
```

Dropping NaNs fixes the issue:
![image](https://user-images.githubusercontent.com/41651716/102243772-85daf500-3ec9-11eb-81ec-47d473c9630b.png)

All of our AutoML pipelines have an Imputer. So I think the true bug is that the imputer does not impute NaNs for the `job` column!

![image](https://user-images.githubusercontent.com/41651716/102244251-0c8fd200-3eca-11eb-8499-c20d3fba7429.png)

This is because the Imputer will only impute [categorical columns, not text](https://github.com/alteryx/evalml/blob/main/evalml/pipelines/components/transformers/imputers/imputer.py#L67). When we convert to pandas from ww, text columns get converted to `object`. 

The question now is "where should NaNs be handled for text columns"?. I think we have two options:
1. Update the Imputer to handle text columns.
2. Interestingly, the `LSA` transformer comes after the `nlp_primitives` are finished computing features. That makes me think that the `nlp_primitives` DFS naturally handle NaNs  whereas `LSA` does not. Should that feature be added to LSA @eccabay ? 
3. Both

What do you guys think?

_Originally posted by @freddyaboulton in https://github.com/alteryx/evalml/issues/1492#issuecomment-745414068_

**Comment by kmax12** [comment]
i dont know of any reasonable techniques for directly imputing a natural language column like we do with our other types. a quick google search turned up nothing. 

the approach that does come to mind is my to ignore the nan rows while running the component and pass them through as nan values in an corresponding rows of the output. then you could apply the numeric imputer after that.

**Comment by freddyaboulton** [comment]
@kmax12 That approach makes sense! If we decide to go with that, then we would also need to modify `make_pipeline` to place the `TextFeaturizer` before the `Imputer`. 

I don't know if the `nlp_primitives` in the `TextFeaturizer` follow push the nans through so we should look into it and see if we need to modify our component accordingly.

**Comment by dsherry** [comment]
Options so far:
1. Continue to crash when we have nans. Not great
2. Ask users to drop all nan rows.
3. Max's suggestion: ignore nans during text, then impute afterwards.

I think we should go with Max's suggestion. Its better than our current behavior.
