### ISSUE TITLE
Support sklearn 0.24.0

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1593]
#1592 is preventing us from upgrading to sklearn 0.24.0. Once that's fixed, we should be able to make the upgrade.

**Comment by freddyaboulton** [comment]
For whoever picks this up, we also need to refactor `test_jupyter_graph_check` in model_understanding to support this latest release. 

The test checks that no warnings are raised but sklearn now raises a warning about a future breaking api change.
