### ISSUE TITLE
Show numerical values for confusion matrix squares

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1601]
From the Blitz: https://alteryx.quip.com/hifwAO0YHqul/Blitz-December-2020-Notes
![image (3)](https://user-images.githubusercontent.com/5422235/103104666-888ac800-45f6-11eb-9184-08c9506f8369.png)
![image (4)](https://user-images.githubusercontent.com/5422235/103104667-89235e80-45f6-11eb-99d1-4b60e4e70567.png)

**Comment by dsherry** [comment]
Yep, this would be cool.
