### ISSUE TITLE
build_conda_pkg failing on main

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1635]
https://app.circleci.com/pipelines/github/alteryx/evalml/8496/workflows/87e056de-b196-4b81-a985-2bee3705c0c2/jobs/98379

The failure appears to have started when we merged [the most recent automated deps update PR](https://github.com/alteryx/evalml/pull/1631), which updates the featuretools version from 0.22 to 0.23.

**Comment by freddyaboulton** [comment]
@dsherry I think this is related to the scipy update. I ran into the same test failures when [I made a PR](https://github.com/conda-forge/evalml-core-feedstock/pull/27) to build version 0.17.0 of our conda package. I think once we merge that PR, this will be resolved!

**Comment by dsherry** [comment]
@freddyaboulton ah!! Of course, thank you :)

**Comment by freddyaboulton** [comment]
Fixed! https://app.circleci.com/pipelines/github/alteryx/evalml/8514/workflows/c7f99e07-b4ca-4639-be92-7a50bf4264c5/jobs/98631
