### ISSUE TITLE
Pipeline predict should preserve the data index

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1639]
Currently, calling `pipeline.predict(X)` will return a series with an index with values from 0 to `X.shape[0] - 1`. This has can cause bugs  (#1634) and can be confusing to users if they pass in data with a custom index.

Should we change this behavior?

**Comment by chukarsten** [comment]
@freddyaboulton @angela97lin : has this been addressed?  I thought I reviewed a PR where you did this.

**Comment by freddyaboulton** [comment]
@chukarsten I don't believe we've had a discussion about this. The PR I think you're talking about is https://github.com/alteryx/evalml/issues/1493 which I think is a different (but related) thing.

**Comment by chukarsten** [comment]
OK, I think this is not an incredibly heavy list.  Dev backlogging it for prioritization.  @dsherry @tyler3991 ?

**Comment by chukarsten** [comment]
explain_predictions_best_worst() is being changed to force the index of y_pred and y_pred_values to y_true.  This needs to be changed after the implementation of above is complete.
