### ISSUE TITLE
Docs failing to reflect attributes

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#1653]
Certain classes such as `ObjectiveBase` and `ComponentBase` aren't reflecting their attributes. `ObjectiveBase` has `@property` and `@classproperty` decorators but none are displayed, while `ComponentBase` additionally has a class attribute with nothing being displayed.
https://evalml.alteryx.com/en/stable/generated/evalml.objectives.ObjectiveBase.html
https://evalml.alteryx.com/en/stable/generated/evalml.pipelines.components.ComponentBase.html?highlight=Componentbase

However, `PipelineBase` has instance attributes and class attributes reflected in its docs.
https://evalml.alteryx.com/en/stable/generated/evalml.pipelines.PipelineBase.html#evalml.pipelines.PipelineBase

**Comment by freddyaboulton** [comment]
I think this would be super helpful! We can help users learn about our objectives if we can get the objective constants (and their values) such as `perfect_score` and `greater_is_better` to appear in the api ref.
