### ISSUE TITLE
Custom woodwork types aren't preserved in components

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1662]
EDIT: following #1668, updating this issue.

**Problem**
Our components currently do not preserve the input custom woodwork types. After #1668, we updated automl and `ComponentGraph` to keep track of custom Woodwork types, such that if a user overrides a Woodwork type, it will be passed from component to component successfully. However, this is not true on a Component level: if a user passes an overridden Woodwork column to only a component, they will find that the returned Woodwork data structure did not preserve the override. That's odd.

**Symptoms**
User using Component will notice that evalml will reset any overridden Woodwork types.

**Fix**
Update all transformers `transform` to return Woodwork with the original overridden types, if applicable.

Note:
This behavior is relevant only in components where the original column should be preserved. In some cases, such as the standard scaler, type change is expected. In other cases, such as the OHE, the original column is removed and this doesn't apply.

**Comment by dsherry** [comment]
@angela97lin for tracking purposes, did I remember right that you already have a branch for this? Or am I incorrect?

**Comment by angela97lin** [comment]
@dsherry Not yet! I think maybe you were thinking about #1652, which I had a branch up for but is blocking on #1406?

**Comment by angela97lin** [comment]
Not blocking #1652 since the text columns are removed during transformation, and #1668 updates the ComponentGraph to keep track of and update carrying along the text columns within the component graph.
