### ISSUE TITLE
InvalidTargetsDataCheck should check X and y dimensions compatible

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1664]
Not sure if this belongs in this class, but I was able to pass a 8 row X input matrix and a 200 row y target matrix to InvalidTargetsDataCheck.validate(X,y) and it didn't complain.  Not sure if we want to implement a sanity check here, but it might be worth it.

**Comment by bchen1116** [comment]
Closing since [this PR](https://github.com/alteryx/evalml/pull/1816) addresses the size differences
