### ISSUE TITLE
Time Series Detrending

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1669]
Tracking work for handling trends in time series regression problems

**Comment by dsherry** [comment]
@freddyaboulton do you need anything else from myself, @chukarsten @tyler3991 on this at the moment? If not, we should file issues on Monday so we can get them into next sprint.

**Comment by freddyaboulton** [comment]
No, agreed @dsherry !

**Comment by dsherry** [comment]
@freddyaboulton we've completed all work for this epic, correct? If so please close it!
