### ISSUE TITLE
Survey methods for detrending time series data

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1671]

**Comment by dsherry** [comment]
Deliverable:
* Writeup of options for packages and algorithms to tackle stationary and non-stationary detrending of timeseries data
* Recommendation for the method we should use for detrending.

@freddyaboulton this look right? Came up during triage

**Comment by freddyaboulton** [comment]
The survey can be found [here](https://alteryx.quip.com/8gqaAU6xOWGj/Survey-of-Detrending-Approaches-and-OSS). The next step is a spike to test the best way to handle detrending (section 1 of the research plan).
