### ISSUE TITLE
Changes and fixes for time series classification problems

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1681]
Comment with reproducer thanks to @bchen1116 :

https://github.com/alteryx/evalml/pull/1666#pullrequestreview-566400601

**Comment by dsherry** [comment]
Discussed with @ParthivNaresh @freddyaboulton this afternoon

Description of problem case: TS binary or TS multiclass where any of the ordered TS splits contains only one class.

One example: TS dataset with all-0s initially and all-1s at the end.

Qs
* How do we check this? A: for now, check first chunk in TS ordered split
* Where do we describe behavior? A: API docs, also data checks user guide
* Does this go in TS data check or separate?
* How do we ensure the same config is passed to TS data splitting in the data check vs in automl?
* Do we include this data check in the time series binary and multiclass set? A: yes
