### ISSUE TITLE
CircleCI Windows Workers Randomly/Semi-consistently Failing

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1687]
This bug has been discovered for the second time in the pursuit of developing Issue #1640 .  The problem is with the CircleCI check, windows_test_all_python_versions, specifically the Python 3.8 test.  The referenced test that fails is the same in this branch as it was when @bchen1116 first encountered this bug.  

The error message CircleCI produces:

test setup failure
Worker 'gw7' crashed while running 'evalml/tests/automl_tests/test_automl.py::test_automl_error_callback'

Repro steps: ??? I've made a copy of the KNN branch called SHA: 7f3b1c3ac399b58b821c8f3cac0573fefa3fb5d7, but it is unclear how to actually reproduce the bug.

Attempted Fixes:

1. Ran tests locally on Linux box - could not repro.
2. Ran tests locally on Windows box - could not repro.
3. SSH'ed into Windows box on CircleCI that did the tests with the environment the server set up - could not repro.
4. Waited a period of time - bug went away.
5. @bchen1116 made some adjustments to code and pushed new commits and that made the bug go away, but I suspect since that didn't happen for me that something else is going on.

**Comment by dsherry** [comment]
Next step: whoever picks this up, try to repro. If you can, let's debug. If you can't let's close and reopen when we see it again.
