### ISSUE TITLE
AutoMLSearch plots not appearing in Docs

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#1692]
The plots generated in AutoMLSearch are not appearing in the [documentation](https://evalml.alteryx.com/en/stable/user_guide/automl.html#Limiting-the-AutoML-Search-Space)

![image](https://user-images.githubusercontent.com/22552445/104632800-3c1e2f80-566c-11eb-92e1-e589aecd39bd.png)

**Comment by dsherry** [comment]
@bchen1116 could you please remind me why we moved this to the icebox a couple weeks ago?

**Comment by dsherry** [comment]
This may have same root cause / fix as #2699 , but this is higher priority than that issue
