### ISSUE TITLE
Integrate KNN Classifier into AutoML

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1696]
Remove KNeighborsClassifier from gen_utils._not_used_in_automl and then update the tests to account for the new estimator being counted.

**Comment by chukarsten** [comment]
@dsherry @tyler3991 I'm moving this into the next sprint, if that's cool.  The KNN classifier was added, we should probably take the next step and add it to AutoML.  I also know how to do perf tests so I'll self assign.  Thoughts?

**Comment by tyler3991** [comment]
yeah that makes sense to me! @chukarsten

**Comment by dsherry** [comment]
@chukarsten what's the status of this?

**Comment by chukarsten** [comment]
Sorry I haven't been able to touch this since last sprint.  I put it in automl and ran the perf tests ,but wasn't seeing KNN being selected in any of the rankings.  I then brought back the iris datasets....and still didn't see any selection of knn.

**Comment by ParthivNaresh** [comment]
I'll take a stab at this
