### ISSUE TITLE
Uncap LightGBM Version

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#1713]
Right now, we [cap](https://github.com/alteryx/evalml/pull/1711) LightGBM version > 3.1.0 since it introduces a bug to our docs. We believe the version after 3.1.1 will fix this bug, but that hasn't been released yet. This issue tracks adding support for that version and unpinning the LightGBM version.

**Comment by dsherry** [comment]
Thanks @bchen1116 . Yep let's wait until lightgbm does another release and then try to update and see if our docs issue is fixed.
