### ISSUE TITLE
Spike: move to GitHub actions

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1715]
Background:
We currently use CircleCI. We'd like to move to GitHub actions. We should coordinate with @rwedge @gsheni and the other Inno labs projects, because they've already ported over and will have tips and code to share.

Goal:
This issue tracks figuring out what is required to move to GitHub actions, writing up a plan.

This is complete when we've filed an epic and have filed issues under that epic.

**Comment by rwedge** [comment]
For tips and knowledge share, @jeff-hernandez took point on porting the tests for featuretools etc.

**Comment by dsherry** [comment]
Hey @ParthivNaresh a note: I am hoping we can delete our `build_jobs` CI job in favor of the new RTD PR jobs we added. I filed #1823 to track a potential issue with that. Just wanted to highlight that though, I don't think we should invest in porting `build_jobs` in its entirety to GH actions.
