### ISSUE TITLE
Update visualize_decision_tree to track feature names

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#1718]
Currently `visualize_decision_tree` in `model_understanding` sets column names in its cells as the format `X[14]` or `X[4]`. ~~We should be able to pass in `feature_names` as a parameter to `visualize_decision_tree` and then to `export_graphviz` so that the visualization reflects the feature names.~~

Hijacking this issue a bit, but I think we shouldn't need to pass in another parameter for this, since #1757 addressed estimators keeping track of feature names they were trained on. We should just be able to grab that information now, without the help of the user :)

![VisualizeDT](https://user-images.githubusercontent.com/29577911/105405769-861d8d00-5bf9-11eb-9ba1-562c24d0f217.png)

**Comment by angela97lin** [comment]
@ParthivNaresh @dsherry 

We currently don't have a good way for estimators to keep track of the features that were trained on. (Note: pipelines do keep track). I think if we want to do this, we should update the estimators to keep track of the feature names first, and then this will be pretty straightforward.

**Comment by dsherry** [comment]
Options:
1. Update `visualize_decision_tree` to require training data as input. Have impl set the feature names under the hood.
2. During pipeline or estimator training, inside the estimator `fit` method, store input feature names on the estimator. Then when we call `visualize_decision_tree`, access that info.
3. Same as above, but move the pipeline `input_feature_names` impl down into each component -- store that info as metadata on each component, during each `fit` method.

Plan:
* We prefer option 3 above. If that proves too complicated or looks too long to implement, fall back to option 2.
* Whoever picks this up, please write up a quick design sketch and lets review.

**Comment by angela97lin** [comment]
Just assigned myself this since I'm working on #1757 as well. Don't think it'll be done in time for Jan B sprint but decided to leave as is and have it be moved during the triage for visibility of what was completed/not for the sprint.
