### ISSUE TITLE
Augment InvalidTargetDataCheck to check for mismatched indices in target and training data

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1726]
This fell out of https://github.com/alteryx/evalml/issues/1723. My guess is that this would fit best in `InvalidTargetDataCheck` but open to suggestions.

We've seen a few cases where indices cause bugs (imputer, encoder, etc). It could be a good idea to warn users if their data has mismatched indices, since that could leave to unexpected behavior. For example, pandas could try to backfill some indices and introduce NaN and cause errors while modelling.

@freddyaboulton FYI 😀

**Comment by dsherry** [comment]
Let's talk about this when we discuss #1723

**Comment by dsherry** [comment]
Oops I filed a duplicate (#1779). One little piece of context from that issue:
> For future compatibility with unsupervised problem types, I suggest we don't raise an error if y=None. I think the invalid target data check covers that case.

**Comment by angela97lin** [comment]
@freddyaboulton Correct me if I'm wrong, but I don't think this is is blocked on #1723, which I noticed you picked up? If that's true, I can pick this up and work on it concurrently :))

**Comment by freddyaboulton** [comment]
@angela97lin Yea, this isn't blocked by #1723!

**Comment by angela97lin** [comment]
@freddyaboulton Amazingggg, thank you 😁
