### ISSUE TITLE
Make it easy to score automl search pipelines on holdout

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1729]
I'd like us to consider the following use-cases:
* Train all pipelines on training data and return trained pipelines
* Train all pipelines on training data, score on holdout and return the scores
* Both of the above, with the ability to specify a subset instead of training on all pipelines

Let's explore some APIs for the above.

To close this issue: design doc.

**Comment by freddyaboulton** [comment]
@dsherry @chukarsten I've prepared a design doc [here](https://alteryx.quip.com/ySavAbaTT3zg/Updating-AutoML-to-make-it-easy-to-train-pipelines-on-entire-data)!
