### ISSUE TITLE
Data Health/Checks: Uniqueness Score

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1744]
Idea: implement a uniqueness score to evaluate a feature's uniqueness of values in the following way:

``` 
def unique_score(counts: pd.Series, many=False) -> dict:
    """
    This function receives the value counts of all values in a field, then calculates the
    value for the defined uniqueness score (sum of squares of proportions) based on if the data type suggests too few
    unique is bad or too many is bad.
    :param counts: result of value_counts on column
    :param many: reverses score for too many unique values when True
    :return: unique value score and distribution of values
    """
    norm_counts = counts / counts.sum()
    square_counts = norm_counts ** 2
    score = 1 - square_counts.sum()

    # categorical data is considered bad if there are too many unique values
    if many is True:
        score = 1 - score

    counts.index = counts.index.astype("str")
    payload = {"score": score, "distribution": counts.to_dict()}

    return payload
```

To fit our style of DataChecks:

1. A threshold for low uniqueness for continuous data needs to be selected.
2. A threshold for high uniqueness for categorical data needs to be selected.
3. The data check should be implemented within the class' .validate(X, y=None) function so that the input features are scored and validated for uniqueness.
4. (optional) The data check should be implemented so that .validate(X, y)) checks the target for high or low uniqueness depending on problem type.
5. (optional) Remove the uniqueness checking from InvalidTargetDataChecks.

**Comment by chukarsten** [comment]
@dsherry Here's one place where we don't seem to exactly match the functionality of the existing data health.  Let me know what you think.  

I'm mostly curious about how we handle data checks with respect to features and targets, be they separate or together.  I think what's weird about Data Checks right now is how the features and target are handled separately for similar checks.

**Comment by dsherry** [comment]
@chukarsten good point, we should consider how this fits with the uniqueness check in `InvalidTargetDataCheck`.

I'm tempted to suggest that we simply move the uniqueness check for the target out of there and into this new data check. That has its drawbacks too of course, since now if someone runs the invalid target check alone they don't get uniqueness applied. Let's chat about how to organize this stuff, there's gotta be a clean way to do it floating around in here somewhere.
