### ISSUE TITLE
Data health

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1767]
Tracks changes and additions to the data checks and the data checks API which are necessary in order to implement data health.

**Comment by fjlanasa** [comment]
@dsherry is this completed? I thought there were 4 issues but now i see 3/3 completed.

**Comment by dsherry** [comment]
@fjlanasa this is complete to the best of our knowledge. There was another issue #1801 but its not required for this work, just a refactor.

**Comment by fjlanasa** [comment]
@dsherry cool will look into what it will take to use this in PS. thanks!
