### ISSUE TITLE
Docs:Back Arrow on Install Page

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1773]

**Comment by chukarsten** [comment]
The red box should be addressed on the linked screenshot.  Perhaps all that in the back arrow link should be replaced with "Home" or something simple.

<img width="887" alt="Screen Shot 2021-02-01 at 2 43 01 PM" src="https://user-images.githubusercontent.com/64713315/106509708-f77ffa00-649b-11eb-870e-6ba908df88ab.png">

**Comment by jpcarroll** [comment]
Hi @chukarsten I would like to work on this issue!

**Comment by chukarsten** [comment]
Go for it!  Happy to have the help!

**Comment by jpcarroll** [comment]
I have created a PR for this change [here](https://github.com/alteryx/evalml/pull/1795).
