### ISSUE TITLE
AutoML: indicate which pipelines were selected for ensembling

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1776]
**Background**
Our stacked ensembler models are constructed from a handful of pipelines. The only way to know currently which pipelines are part of the ensemble is to look at a) the estimators used in each inputted pipeline or b) the names of each inputted pipeline.

**Feature Request**
We should add some way to query `AutoMLSearch` for a list of the pipeline IDs of each of the pipelines in each of the ensemble pipelines.

There are three likely candidates in our current API for where we could add this info:
* The `results` structure is where we currently store metadata about each pipeline.
* `get_pipeline` returns a fresh copy of the pipeline, ready for training.
* `describe_pipeline` current logs info to the logger, and can optionally return a dictionary with some info.

**Implementation notes**
The selection of input pipelines and construction of the ensemble pipeline [occurs in `IterativeAlgorithm`](https://github.com/alteryx/evalml/blob/main/evalml/automl/automl_algorithm/iterative_algorithm.py#L76), because `IterativeAlgorithm` holds the info about how pipelines have scored so far. But pipeline IDs are created and maintained by `AutoMLSearch`. We'll need to decide how to change this.

Two ideas off the top of my head: define a `Results` object accessible by both `AutoMLSearch` and `IterativeAlgorithm`, or define a `metadata` field on pipelines which can be used to pass pipeline ID into `IterativeAlgorithm`.

Ideally, we can find a solution which simplifies how `AutoMLSearch` and `IterativeAlgorithm` share information. I think we can use this as an opportunity to pay down some of the tech debt we accumulated when we added ensembles. Extra credit if the solution doesn't make it harder for us to parallelize automl pipeline evaluation.

To close this issue: design doc with a plan for how to fix. Then we can file issue to track the fix.

**Comment by angela97lin** [comment]
Note: it'd be good to note that the pipeline that is passed from AutoML to create the stacking ensemble pipeline in IterativeAlgorithm is a copy of, but not exactly the same pipeline as the one that has an id in AutoMLSearch. We take the best pipeline of each model family and instantiate a new pipeline that has the same parameters and random state to pass to our stacking ensemble.

Code from IterativeAlgorithm here:
```
            for pipeline_dict in self._best_pipeline_info.values():
                pipeline_class = pipeline_dict['pipeline_class']
                pipeline_params = pipeline_dict['parameters']
                input_pipelines.append(pipeline_class(parameters=self._transform_parameters(pipeline_class, pipeline_params),
                                                      random_state=self.random_state))
            ensemble = _make_stacked_ensemble_pipeline(input_pipelines, input_pipelines[0].problem_type,
                                                       random_state=self.random_state,
                                                       n_jobs=self.n_jobs)

```

**Comment by angela97lin** [comment]
Design doc here: https://alteryx.quip.com/VyJ6Ac1sAc7c/AutoML-Ensembling-Indicate-which-pipelines-were-selected-for-ensembling

Closing in favor of #1873 and #1872 :)
