### ISSUE TITLE
Small dataset support: update data splitting strategy

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1783]
I bet we'll see better generalizability on some small datasets (low number of rows) if we increase the default number of CV folds.

This issue tracks choosing and implementing a policy for small datasets.

My gut recommendation is to do 10 CV folds for datasets under a size threshold. Personally I'd set this threshold somewhere around 100 rows. [This writeup](https://scikit-learn.org/stable/modules/cross_validation.html#leave-one-out-loo) was a good read (note: I'm not suggesting we do leave-one-out CV; the text I'm linking to happened to be in that section).

@rpeck

**Comment by christopherbunn** [comment]
Closing due to a lack of performance improvement on smaller datasets. More info on #2312.
