### ISSUE TITLE
Update woodwork version to 0.0.9

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1788]
@gsheni @thehomebrewnerd have a patch for #1780 going out in that release (https://github.com/alteryx/woodwork/issues/541)

We should update to get that patch.

**Comment by gsheni** [comment]
Woodwork v0.0.9 has been released.

**Comment by angela97lin** [comment]
Was digging into this a bit. Looks like in 0.0.8 (and more specifically, this PR: https://github.com/alteryx/woodwork/pull/464), Woodwork changed their behavior such that when a DataTable is initialized, the index is set to RangeIndex. This causes an issue with EvalML components, which seek to preserve the Index of the original input data.

Talking to @tamargrey, a workaround would be to add an index column, pass it to the WW constructor as the index column to use, and then when converting back to pandas, removing that column. This has its own implications and complications though. The biggest for EvalML is, we currently return WW from components. The returned WW structure would need to have that index column. Weird behavior if user is using component on its own. If the component is fed into another component, the other component would need to know what column to use as the index and drop.

I filed something with Woodwork for this (https://github.com/alteryx/woodwork/issues/569), but we may want to halt on upgrading until this is resolved.

**Comment by angela97lin** [comment]
Closing in favor of #1899
