### ISSUE TITLE
Pipeline problem_type accessor

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1793]
Currently, the method of checking the problem type of a pipeline is to do:

```
if handle_problem_types(pipeline.problem_type) == ProblemTypes.Binary:
```

It would seem a little more intuitive to be able to do:

```
if pipeline.is_problem_type("binary"):
```

and fold the handling and comparison to ProblemTypes inside the PipelineBase class.

This issue is complete when the problem_type accessor is written and tested and a new issue generated for the refactoring of existing code to match this pattern.

**Comment by dsherry** [comment]
We have helpers for problem types: `is_regression`, others, in `evalml/problem_types/utils.py`. Closing.
