### ISSUE TITLE
Spike: Override default Woodwork type system to numpy/pandas compatible types

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1796]
In v.0.0.7, Woodwork added support for user-defined logical types and inference functions in TypeSystem object. @thehomebrewnerd suggested in https://github.com/alteryx/evalml/pull/1784#pullrequestreview-585593218 that we could potentially override the default Woodwork type system and use pandas_dtype and backup_dtype values that would not require the conversions that are currently done in `_convert_woodwork_types_wrapper` so that we don't end up with funky behavior when we convert a Woodwork structure back to pandas/numpy.

**Comment by dsherry** [comment]
Goal of spike: demonstrate what this would look like in a PR, and what we would gain from it.

I'd like to know where specifically `Int64` and the other nullable types used by woodwork today cause problems in evalml code.

**Comment by chukarsten** [comment]
@angela97lin closing in favor of #2019
