### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1804]
Migrate current CircleCI Workflows to GitHub Actions.

Quip Documentation: https://alteryx.quip.com/3k39OY4VPQGu/GitHub-Actions

**Comment by dsherry** [comment]
Before we close this, let's make sure we've updated [release.md](https://github.com/alteryx/evalml/blob/main/release.md) to link to github actions instead of circleci.

**Comment by dsherry** [comment]
Notes from discussion about codecov with @ParthivNaresh :
* Always upload codecov, even if any of the linux unit tests fail.
* Verify that if there is a coverage decrease, the "coverage" github check on the PR fails.
* Always run both of the linux 3.8 jobs (with/without core deps flag), because our coverage needs both. Otherwise, if even one test fails, one of the two jobs will not run, and coverage will look much worse than it really is. Fine to file this separately.

**Comment by dsherry** [comment]
@ParthivNaresh what work is left in order to close this epic? This was what I remembered:
* `build_conda_pkg` tracked by #1824 
* codecov -- if there is still work needed for this, and there isn't already a PR in flight, please file an issue and attach it to this epic so we can track.

**Comment by ParthivNaresh** [comment]
@dsherry I had filed #1911 previously, added it to the Epic now!

**Comment by dsherry** [comment]
@ParthivNaresh I believe we are all set here! You wanna close this epic? 😁
