### ISSUE TITLE
Binary Classification Pipeline  predict method does not use objective if it is passed as a named argument

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1819]
Repro:

```python
from evalml.objectives import BinaryClassificationObjective
from evalml.demos import load_breast_cancer
from evalml.pipelines import BinaryClassificationPipeline
import pandas as pd
from unittest.mock import MagicMock


class Pipeline(BinaryClassificationPipeline):
    component_graph = ["Random Forest Classifier"]


X, y = load_breast_cancer()


class CustomObjective(BinaryClassificationObjective):
    greater_is_better = False
    name = "Foo Objective"
    perfect_score = 0
    score_needs_proba = False
    
    def objective_function(self, y_true, y_predicted, X=None):
        pass
    
    def decision_function(self, ypred_proba, threshold, X):
        # The decoder will map 0 to benign so we should expect the
        # predictions to only contain "benign"
        return pd.Series([0] * len(ypred_proba))


pipeline = Pipeline({})
pipeline.fit(X, y)
pipeline._threshold = 0.3
expected_preds = ['benign'] * len(y)

assert not pipeline.predict(X, objective=CustomObjective()).to_series().tolist() == expected_preds
```

The strange thing is that it works as expected if the objective is not used as a kwarg:

```python
assert pipeline.predict(X, CustomObjective()).to_series().tolist() == expected_preds
```

The problem is in the pipeline meta class. If the objective is passed as a kwarg, then `y=None` and we [don't pass the objective to the method](https://github.com/alteryx/evalml/blob/main/evalml/pipelines/pipeline_base_meta.py#L25).

**Comment by freddyaboulton** [comment]
I think the root cause is that the pipeline metaclass has three arguments `X`, `y`, and `objective` but the `y` is (currently) only used for time series pipelines. 

Two posible solutions are:
1. Create a separate metaclass for time series pipelines
2. Add `y=None` as an argument for all pipelines.

I think I prefer option 1 because passing `y` for a non-timeseries pipeline's predict method could be strange to users.

I also think we should take the opportunity to improve the readability of the metaclass implementation. Right now, we dispatch based on the values of the arguments passed in, but I think it would be clearer if we dispatched on `method.___name__`.

**Comment by dsherry** [comment]
Seems reasonable to me. I agree option 1 is the more palatable of those two.

Can we use inheritance with the metaclass?

**Comment by freddyaboulton** [comment]
@dsherry I believe so!
