### ISSUE TITLE
InvalidTargetDataCheck: if y is None, raise data check error

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1820]
Original comment from @dsherry: https://github.com/alteryx/evalml/issues/1726#issuecomment-772647856

However, it feels weird to me for a data check that expects a target / checks for invalid target to be okay with not being passed a target. RE original comment, perhaps for unsupervised problems we shouldn't run that data check, rather than update the data check itself.

**Comment by dsherry** [comment]
Agreed, fine to preserve existing behavior for now and handle unsupervised in the future.

Action: update the check to raise a `DataCheckError` instead of an exception if `y` is `None`
https://github.com/alteryx/evalml/blob/main/evalml/data_checks/invalid_targets_data_check.py#L66
