### ISSUE TITLE
Optimize prediction explanations by computing the features only once

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1821]
Currently, the workhorse for our prediction explanations is [`_make_single_prediction_shap_table`](https://github.com/alteryx/evalml/blob/main/evalml/model_understanding/prediction_explanations/_user_interface.py#L205). 

This function expects a single row of features, computes the feature engineering, and then computes the shap values for that row. 

This works fine for explaining a single prediction, but when #1782 is merged, we'll be computing the features for the entire dataset for each row we want to explain. This is because of how features for the current row depend on previous features in time series.

Moved to #1833:

Additionally, to explain each row, we create a new [`explainer`](https://github.com/alteryx/evalml/blob/main/evalml/model_understanding/prediction_explanations/_algorithms.py#L67) and compute the shap values for only that row. But we can compute the shap values for all of the desired rows [at once](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/model_agnostic/Diabetes%20regression.html#Explain-all-the-predictions-in-the-test-set). 

I propose we only compute the features once and compute the shap values for all of the rows at once as well.

**Comment by dsherry** [comment]
What do we get:
* Computation is faster
* API is cleaner

@freddyaboulton , @chukarsten wants to catch up with you on this.

**Comment by freddyaboulton** [comment]
@chukarsten Free to catch up any time! Yea the computation would be faster because we're not duplicating work. 

The apis for the user facing functions in `explainers.py` will stay the same but the internals will be cleaned up, which I think is a win.

**Comment by freddyaboulton** [comment]
Filed #1833 to track computing the shap values only once. This issue tracks refactoring the code to compute the features only once.
