### ISSUE TITLE
Deprecate the explain_prediction function

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1822]
Once #1818 is merged, the following two function calls will be the same:

```python
explain_prediction(pipeline, input_features, y, index_to_explain=3)
```

```python
explain_predictions(pipeline, input_features, y, indices_to_explain=[3])
```

I think this makes `explain_prediciton` redundant.

**Comment by dsherry** [comment]
Yes!

**Comment by dsherry** [comment]
I think we should follow our pattern for deprecation:
* This issue tracks adding a deprecation warning now, and filing an issue to delete `explain_prediction` altogether
* We'll schedule that second issue for the following release

I suspect it would be ok to simply delete this method, but I think its good for us to stay in the habit of giving advance notice for deprecations.
