### ISSUE TITLE
Add CI to run docstring examples

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1823]
**Background**
We initially created a `build_docs` job because we didn't know of a good way to access the status of the RTD docs build and show that in github PRs.

Since we've enabled RTD PR builds and that seems to be going well, I hope we can eventually delete the `build_docs` job.

Currently our `build_docs` job will fail if you provide an invalid docstring example, meaning it is executing those examples. That's good; we should be catching errors in docstring examples.

**Goal**
After we move to github actions, we should still have CI which fails if docstring examples are invalid.

**Next steps**
This issue tracks either a) verifying that our RTD PR builds will fail if docstring examples are broken, or b) if not, figure out if there's a way to create a separate job (`validate_docstring_examples`?) which can take care of this.

**Comment by ParthivNaresh** [comment]
Addressed by our current linux tests which run the docstring examples and will fail if the docstring examples are broken.
See for example: https://app.circleci.com/pipelines/github/alteryx/evalml/10083/workflows/c6718e45-94c9-4bfc-a006-3f4e4c6738b8/jobs/118172
