### ISSUE TITLE
GitHub Actions - Workflow - build_conda_pkg

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#1824]
GitHub Actions workflow for build_conda_pkg.

Quip Doc: https://alteryx.quip.com/YbZzAp4EURNj/Workflow-buildcondapkg

**Comment by dsherry** [comment]
@ParthivNaresh could you please post a status update on this issue?

**Comment by ParthivNaresh** [comment]
@dsherry I'm blocked on this with the error `Error: Cannot perform an interactive login from a non TTY device` on https://github.com/alteryx/evalml/runs/2013368080?check_suite_focus=true. The `shellcheck` which is the first part of this workflow works as expected, but the second part is blocked by this error.
