### ISSUE TITLE
GitHub Actions - Workflow - linux python X.X unit tests

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#1825]
GitHub Actions workflow for linux python X.X unit tests.

Quip Doc: https://alteryx.quip.com/ZdlbAixZ9If3/Workflow-testallpythonversions

**Comment by dsherry** [comment]
Reopening because we haven't migrated the linux unit tests and codecov over to GH actions yet

**Comment by dsherry** [comment]
Ugh oops I'm completely wrong here... I meant to keep something open for verifying codecov. We're all set
