### ISSUE TITLE
Data oversampling after data preprocessing/feature engineering

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#1830]
Currently, our [plan](https://alteryx.quip.com/z9KJAHWFo1Sa/EvalML-Data-Splitting-Notes) is to implement a Random Undersampling method to handle imbalanced datasets. This undersampling would occur before the data has been passed into the pipelines, prior to any feature engineering.

In the future, we want to use oversampling methods on the training data, after all of the features have been created with our transformers. This will allow our sampling method to handle datetime and text data, as well as many other features that we would create during our data transformations.  Otherwise, we wouldn't be able to handle these instances well.

Filing this issue in order to look at the design necessary to make that happen. What changes would we need to make to the current AutoMLSearch in order to allow this?

**Comment by jeremyliweishih** [comment]
Following up on discussion today:

With the addition of these data splitting / data augmentation sprinkled throughout various areas of AutoML it difficult for a user to replicate this data splitting / data augmentation when they take a pipeline out of AutoML. A use case of this would be a user taking a pipeline into production and want to train the pipeline with more data but cannot do so as there is no easy way to replicate data splitting / data augmentation (under/over sampling etc.). 

We should brainstorm a potential solution to this problem as part of this issue as it would be prudent to get a solution for this before adding more data splitting / data augmenting.

**Comment by bchen1116** [comment]
Following up, here is a [design doc](https://alteryx.quip.com/l7WcAeaxkB82/Oversampling-after-Feature-Engineering-REVISED) for a potential plan on implementing oversampling, as well as [initial test results](https://alteryx.quip.com/EMqnAle4NI9B/Oversampler-Component-initial-results). Once the team approves, I will file the issues to resolve this spike and close this.

**Comment by dsherry** [comment]
@bchen1116 this spike is completed, yes? Closing. #2014 can track the work on this feature.

**Comment by bchen1116** [comment]
Yep, I can file the issues outlined in the [design doc](https://alteryx.quip.com/TW2nANznZcpN/Oversampling-in-AutoML-Search)
