### ISSUE TITLE
Demo: Two-way partial dependence plots

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1835]
Two-way partial dependence was implemented, but the model_understanding.ipynb notebook was not updated to demonstrate it.  (Thanks @chukarsten).  A section should be added to demonstrate some simple two-way partial dependence underneath the current one-way partial dependence plot and any other supporting cells in the notebook updated to include the functionality.

**Comment by dsherry** [comment]
@chukarsten this was closed last week, correct? I think the PR didn't close it. Marking as close, feel free to correct if I'm wrong.

**Comment by chukarsten** [comment]
You're good!  You see, I told you people (me) weren't properly maintaining the board!
