### ISSUE TITLE
Automl does not use objective decision function during scoring

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1868]
Our classification pipeline uses the `_compute_predictions` method in `score` to get the predicted labels and probabilities. 

However, `_compute_predictions` [does not pass the objective](https://github.com/alteryx/evalml/blob/main/evalml/pipelines/classification_pipeline.py#L138) to the pipeline `predict` method.  

Is this intended?

**Comment by angela97lin** [comment]
Notes from discussion w/ @freddyaboulton @dsherry @chukarsten 
- Currently only affects custom objectives (`infer_feature_types(objective.decision_function(ypred_proba, threshold=self.threshold, X=X))` not run) so not as high priority.
- Valid bug, should fix and create unit test with decision function and test `score` calls.
