### ISSUE TITLE
Shap values correspond to changes in probability or log odds depending on the estimator

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1886]
Repro
```python
from evalml.demos import load_breast_cancer
import shap
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from lightgbm.sklearn import LGBMClassifier


X, y = load_breast_cancer()
X = X.to_dataframe()
y = y.to_series()

rf = RandomForestClassifier()
rf.fit(X, y)

lg = LogisticRegression()
lg.fit(X, y)

lgbm = LGBMClassifier()
lgbm.fit(X, y)

# Random Forest
tree_explainer = shap.TreeExplainer(rf)
tree_explainer.shap_values(X.iloc[:5])
tree_explainer.expected_value  # array([0.62335677, 0.37664323])

# Light GBM
lgbm_explainer = shap.TreeExplainer(lgbm)
lgbm_explainer.shap_values(X.iloc[:5])
lgbm_explainer.expected_value # [2.4751205225979684, -2.4751205225979684]

# Logistic Regression
logistic_explainer = shap.KernelExplainer(lg.predict_proba, link='logit', data=X)
logistic_explainer.shap_values(X.iloc[:5])
logistic_explainer.expected_value # array([ 0.51530458, -0.51530458])
```

Shap values are defined as deltas from the expected value. In the code snippet, the expected value for the random forest is a probability but it's the log-odds for the logistic regression and lightgbm models.

We don't display shap values by default and the +'s and -'s in the report output can be interpreted as increases/decreases in the probability (an increase in the log-odds ratio is an increase in the probability, just not a linear increase) so I don't think any action is required from us.

That being said, I thought we should be aware of this since I found it confusing and users may ask us questions. In that event, we can refer them to this issue. 

FYI @rpeck

**Comment by dsherry** [comment]
@freddyaboulton I'm being dense, can we chat about this sometime?

**Comment by dsherry** [comment]
Discussed with @freddyaboulton . Intent of filing issue was to document a limitation of shap: the mathematical meaning of the shap value varies per estimator. Closing.
