### ISSUE TITLE
Handle deprecation warnings properly in the documentation

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1887]
Per the previous release and the deprecation warnings applied to explain_prediction() in #1822 , deprecation errors crop up in the user facing docs.  https://feature-labs-inc-evalml--1874.com.readthedocs.build/en/1874/demos/fraud.html. These will naturally disappear with the completion of #1832 , but it will be best to tackle this now as part of our preparation to adopt the process of deprecating functions in this way.

No bueno.  So we need to come up with a solution that handles this for all the user-facing docs.  It's good that a user sees a warning when working in their console or IDE, but we don't want this in the docs.  Curiously, when I try to reproduce locally, I do not get the warnings on my local jupyter notebook.  We should explore whether there's some global warning suppression that we can perform on the documentation.

More than likely, this issue won't be completed before the explain_prediction() is removed.  If a good test needs to be made, checkout v. 0.19.0 and see how the explain_prediction() function was deprecated and replicate that as a starting point.

![image](https://user-images.githubusercontent.com/64713315/108951412-ee66f080-7635-11eb-8379-37e0fa6d1d72.png)

**Comment by dsherry** [comment]
Yep. One idea: hidden cell in our notebooks which suppresses warnings.
