### ISSUE TITLE
v0.18.2 Perf Test Results

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1888]
In attempting to perform the 0.19.0 release, I got some weird results with respect to the 0.18.2 perf tests.  See https://alteryx.quip.com/DsyEAqnI1tRh/v0190-vs-v0182-perf-test-results#dERACA7df0O, "Anomalies" section for a description.  This should be analyzed a little more to ensure that something strange hasn't crept into the baseline.

In short, the response json from looking glass contained something like this.

`{"results": [{"dataset": "abalone.csv", "trials": [{"measurements": [{"measurement_name": "error_type", "measurement_value": "<class 'TypeError'>"}, {"measurement_name": "error_message", "measurement_value": "split_data() got an unexpected keyword argument 'random_seed'"}, {"measurement_name": "error_traceback", "measurement_value": "  File \"looking_glass/container/perf_test_runner.py\", line 228, in run\n    trial_measurements_dict = measure_evalml_automl(X, y,\n  File \"/evalml_looking_glass/looking_glass/container/evalml_runner.py\", line 50, in measure_evalml_automl\n    X_train, X_validation, y_train, y_validation = split_data(X, y, problem_type=problem_type,\n"}], "metadata": [{"metadata_name": "random_seed", "metadata_value": "0"}, {"metadata_name": "max_iterations", "metadata_value": "14"}, {"metadata_name": "max_batches", "metadata_value": "None"}, {"metadata_name": "evalml_automl_arguments", "metadata_value": "{}"}, {"metadata_name": "evalml_search_arguments", "metadata_value": "{}"}, {"metadata_name": "evalml_branch", "metadata_value": "v0.18.2"}, {"metadata_name": "evalml_hash", "metadata_value": 
`

The presence of the "random_seed" reference raises some questions.  Was the release branch modified after the perf tests were run?  Did the deprecation explain_prediction() #1822 story get merged in after the release branch was cut?

These issues seem to go away with the latests release, but we might want to investigate this a little further.

**Comment by dsherry** [comment]
This was a versioning error with LG, closing
