### ISSUE TITLE
Prediction explanations: add support for xgboost

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1890]
From @rpeck :

> I see that EvalML throws NotSupportedException if (the model is XGBoost ) or if (the problem type is multiclass and the model is CatBoost).  The SHAP library issue cited in the code says that the XGBoost problem is fixed in SHAP v0.36.0 (we're on 0.35.0); it's not clear if the CatBoost problem is also fixed, but there are some documented workarounds in blog posts. We should try upgrading. https://github.com/slundberg/shap/issues/1215 

I see the [shap 0.36 release notes](https://github.com/slundberg/shap/releases/tag/v0.36.0) mention "XGBoost 1.1 fix"

Let's try it!

@freddyaboulton FYI

**Comment by rpeck** [comment]
<3
