### ISSUE TITLE
Make data check action codes accessible via strings

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1904]
Following up from @freddyaboulton's suggestion [here](https://github.com/alteryx/evalml/pull/1896#discussion_r583770941), making data check action codes a string representation similar to what we have for problem types would make it easier for users to handle and manipulate.

**Comment by dsherry** [comment]
@angela97lin what do you think is the priority of this? Seems like a well-defined feature, but not required to get data check actions done, correct?

**Comment by angela97lin** [comment]
@dsherry Yup! Not a high priority IMO, more of a nice-to-have. :)

**Comment by angela97lin** [comment]
Unassigning since I'm not working on this right now!
