### ISSUE TITLE
Codecov GitHub Action unable to upload a report for test coverage

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#1911]
We want to ensure the ability of the team to review code coverage. This issue is to track a combination of:

- Finding a way to get codecov to identify the proper SHA so that it can create a difference report.
- Finding an alternative to codecov.io.

**Comment by dsherry** [comment]
@ParthivNaresh could you please post a status update on this issue?

**Comment by ParthivNaresh** [comment]
@dsherry This seems to be complete https://github.com/alteryx/evalml/runs/2203683942?check_suite_focus=true except for the issue that `codecov/patch` and `codecov/project` aren't updating on the PR. And since they're required checks, even if it's just a bug from codecov, they won't allow the user to merge which is definitely not something we want in `main`.

There is a possibility that it will work after merging to main but that's just conjecture. I'm still communicating with codecov because they have confirmed that they're seeing the codecov checks running in their logs when I've provided the relevant SHA. We could try merging to main in the meantime and then revert the change immediately if it doesn't work?

**Comment by dsherry** [comment]
@ParthivNaresh ok thanks! Yeah I would be fine with us trying a merge and seeing what happens. If there's a way we can leave the circleci impl in place for now, that would make it easy to switch between the two. Does it seem likely the bug will go away if the target branch is `main` instead of something else?

**Comment by ParthivNaresh** [comment]
@dsherry I will be sure to address these questions after my call with Codecov support today. I think we'll have some actionable material after.
