### ISSUE TITLE
Add demo or user guide for time series pipelines

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1924]
We should add a user guide or detailed demo to showcase our support for time series problems!

**Comment by freddyaboulton** [comment]
@angela97lin We already have #1384 ! It's been iced for a while because we wanted to wait for the detrending work 😬  I should mark it as blocked then hehe

**Comment by angela97lin** [comment]
@freddyaboulton Amazing, thank you! I'll close this as a dup then--this just came out of a conversation on the OSS Slack 😅
