### ISSUE TITLE
Numeric binary classification target warning raised when target is not numeric 

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1927]
Repro:

```python
from evalml.demos import load_breast_cancer
from evalml.automl import AutoMLSearch

X, y = load_breast_cancer()

automl = AutoMLSearch(X, y, problem_type="binary", max_batches=1)
automl.search()
```

Output:

![image](https://user-images.githubusercontent.com/41651716/109997325-17465000-7cde-11eb-914d-3de80a4f80c3.png)

The purpose of the warning is to warn users when they have a numeric binary classification target whose unique values aren't 0,1 but the warning is always raised when the target is a string. I don't think that's intended.

**Comment by dsherry** [comment]
This is probably left over from before we supported string-typed targets. I think we can remove this warning! This issue tracks verifying this is true, and if so removing the warning.
