### ISSUE TITLE
Build ensembler component

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1930]
**Background**
We currently wrap sklearn's impl.

**Proposal**
Build our own.

**Advantages over current approach**
* Use whatever metalearner we want
* Have full control over what data the pipelines and the metalearner are computed on
* Caching: avoid recomputing pipeline (or component) predictions during ensembler training
* Feature selection in ensembler

@rpeck FYI

**Comment by rpeck** [comment]
Even more important:

- optimize the way we do the splits for training the ensemble for different sizes of input data (see my text in https://alteryx.quip.com/daHLAQyVIaUC/Addressing-Ensembling-Overfitting)
- optimize scoring on the component pipelines, by doing common feature engineering steps like target encoding, date expansion, NLP processing, etc only once
