### ISSUE TITLE
Handle imbalanced target classes

### ISSUE THREAD

**Issue by kmax12** [alteryx/evalml#194]
* We can add a guardrail to detect unbalanced problems. 
* we should also discuss what is needed from a pipeline building standpoint to make sure we handle unbalanced problems well

**Comment by dsherry** [comment]
This is a dup of #973, leaving open so that #1266 or another PR for #1049 can close this

**Comment by dsherry** [comment]
We have done this! @bchen1116 added undersampler/oversampler to automl! 🎊
