### ISSUE TITLE
Default optimize_threshold to True in AutoMLSearch

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#1940]
We want to return the best binary pipeline, thresholded, in `AutoMLSearch.best_pipeline`. This will work in conjunction with the [balanced classification data splitter PR](https://alteryx.quip.com/hSg1A2sTAq4n/Balanced-Classification-data-splitter-follow-up-tests).

If a user passes in a non-thresholding objective function (Log Loss Binary, AUC), we will threshold on F1 score as the default. Otherwise, threshold on the objective function the user passes in. This is for binary classification problems only.

**Comment by freddyaboulton** [comment]
@bchen1116 What's the difference between this objective and #648?

**Comment by bchen1116** [comment]
Oh, it's the same! My bad, I didn't realize there was an issue, i'll close this out. Thanks for pointing that out!
