### ISSUE TITLE
Dask Logging

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#1972]
It seems likely that the logger needs to be refactored to accomodate a parallel, asynchronous engine.  If the current implementation writes to an actual file, the Dask or any other asynchronous implementation will struggle with writing to the same file asynchronously.

**Comment by dsherry** [comment]
@freddyaboulton is this closeable in favor of the engine redesign, in which case your PR can be marked as closing this issue? Or do we need to keep this issue open?

**Comment by freddyaboulton** [comment]
@dsherry Good point! #1975 implements new logging behavior that's more suitable to parallel engines. I will mark #1975 as closing this issue!
