### ISSUE TITLE
Make util method(s) that profiles/summarizes a table of data

### ISSUE THREAD

**Issue by kmax12** [alteryx/evalml#198]
We want table level summaries

* number of rows
* number of columns by data type
* size in memory

We also want row level summaries
* missing values row
* if numeric, min, max, std, mean, etc
* if categorical, most frequent value, num unique, etc

To discuss
* just did first pass of info we'd want in the summary. what else? 
* is this one or two functions?

**Comment by dsherry** [comment]
Closing in favor of #2391
