### ISSUE TITLE
Don't enforce pipeline class names to be in camel case

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1984]
Currently, our pipelines will raise an `IllFormattedClassNameError` when you access the name of a pipeline class whose name isn't in camel case and that doesn't have a `custom_name` field set.

```python
from evalml.pipelines import BinaryClassificationPipeline

class Mypipeline(BinaryClassificationPipeline):
    component_graph = ["Logistic Regression Classifier"]

pl = Mypipeline({})

pl.name

-------------------------------------------------------------------------
IllFormattedClassNameError              Traceback (most recent call last)
<ipython-input-10-0d7c0728e2b7> in <module>
----> 1 pl.name

~/sources/evalml/evalml/utils/gen_utils.py in __get__(self, _, klass)
    126 
    127     def __get__(self, _, klass):
--> 128         return self.func(klass)
    129 
    130 

~/sources/evalml/evalml/pipelines/pipeline_base.py in name(cls)
    102             if name == cls.__name__:
    103                 raise IllFormattedClassNameError("Pipeline Class {} needs to follow Pascal Case standards or `custom_name` must be defined.".format(cls.__name__))
--> 104         return name
    105 
    106     @classproperty

IllFormattedClassNameError: Pipeline Class Mypipeline needs to follow Pascal Case standards or `custom_name` must be defined.
```

Why do we need to enforce the class name to be camel case? I don't think any of our data structures or logic *needs* this constraint and I think it'd be nice to let users define their classes how they want.

**Comment by angela97lin** [comment]
Hahaha you're right, I don't think this is *necessary* but looking at `Mypipeline` also feels so wrong 😂

**Comment by freddyaboulton** [comment]
Hehe I feel you @angela97lin 😆  

I think the one weird thing about our current behavior is that users can train/score pipelines with "bad" names and not find out until they access the name (possibly much later). If my class name is wrong, I'd like to find out sooner rather than later but I think we should just remove the constraint entirely.

**Comment by dsherry** [comment]
@freddyaboulton lol good point. I agree. Let's not enforce camelCase
