### ISSUE TITLE
AutoMLSearch.train_pipelines does not apply undersampling 

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1987]
If users run `AutoMLSearch` with an imbalanced dataset, `AutoMLSearch` will use undersampling by default. 

Our current behavior is to train all pipelines with the undersampling. This is taken care of by the sampler's `split` method during search and in the `_find_best_pipeline` method when `AutoMLSearch` goes to train the best pipeline.

The undersampling is [missing](https://github.com/alteryx/evalml/blob/main/evalml/automl/engine/sequential_engine.py#L59) from the `train_batch` logic of the engine and should be added.

**Comment by angela97lin** [comment]
@freddyaboulton This isn't in the scope of the issue description persay, but if an ensembling pipeline is in the batch specified by `train_batch`, we should also split according to the ensembling indices, correct?

**Comment by freddyaboulton** [comment]
@angela97lin Good question! My thought is that we shouldn't. It's the same idea as https://github.com/alteryx/evalml/issues/1931 in my opinion.

I think during search, we should train the ensemble on the ensemble split but before/after search there is no longer a need for it. The `train_batch` method is orthogonal to search and we offer it to give users an easy way to train pipelines by leveraging the underlying engine.
