### ISSUE TITLE
Datetime featurizer errors when there are `nan`s

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1999]
Dataset: [boston housing](https://data.boston.gov/dataset/311-service-requests/resource/f53ebccd-bc61-49f9-83db-625f209c95f5), available [here](https://alteryx0-my.sharepoint.com/:x:/g/personal/dylan_sherry_alteryx_com/EfPD_knV9f1Auv2u99PBINkBu70DraaG42ErpcEQJ5hi6Q?e=oqPKB6)

**Repro**
```python
import evalml
import pandas as pd
import woodwork as ww
df = pd.read_csv('/Users/dylan.sherry/Downloads/bos_311_balanced.csv')
df = df.loc[:, ['reason', 'closed_dt']] # ignore other features because they produce another bug
dt = ww.DataTable(df, logical_types={'reason': 'Categorical'})
automl = evalml.automl.AutoMLSearch(X_train=dt, y_train=y, problem_type='multiclass')
automl.search()
```

Excerpt of output in the debug log:
```
  File "/Users/dylan.sherry/development/evalml/evalml/pipelines/components/transformers/preprocessing/datetime_featurizer.py", line 20, in <lambda>
    months_encoded = months.map(lambda m: _month_to_int_mapping[m])
```
This doesn't appear in the log but I saw it elsewhere at the end: `KeyError: nan`

**Comment by dsherry** [comment]
Had discussion with @jeremyliweishih @boopboopbeepboop @cmancuso

The short-term plan (tracked by this issue) is to add a data check error when datetime features contain `nan`s, asking users to either drop those rows or fill in datetimes for the missing values.

The long-term plan, which I'll file separately, is to define data check actions for this case, beyond simply dropping the missing values.

**Comment by kmax12** [comment]
i missed the discussion so perhaps this was discussed, but why not also update the Datetime featurizer to output rows with nan values for the newly created features?
