### ISSUE TITLE
LSA component errors due to `nan`s in natural language feature

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2000]
Related to #1999 

**Repro**
```python
import evalml
import pandas as pd
import woodwork as ww
df = pd.read_csv('/Users/dylan.sherry/Downloads/bos_311_balanced.csv')
dt = ww.DataTable(df, logical_types={'reason': 'Categorical'})
dt = dt.drop('closed_dt') # ignore datetime feature because nans in it produce another bug
automl = evalml.automl.AutoMLSearch(X_train=dt, y_train=y, problem_type='multiclass')
automl.search()
```

Produces:
```
  File "/Users/dylan.sherry/development/evalml/evalml/pipelines/components/transformers/preprocessing/text_featurizer.py", line 121, in transform
    X_lsa = self._lsa.transform(X[self._text_columns]).to_dataframe()
...
  File "/Users/dylan.sherry/development/evalml/evalml/pipelines/components/transformers/preprocessing/lsa.py", line 63, in transform
    transformed = self._lsa_pipeline.transform(X[col])
...
  File "/Users/dylan.sherry/.pyenv/versions/evalml/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 219, in decode
    raise ValueError("np.nan is an invalid document, expected byte or "
...
Fold 0: Exception during automl search: np.nan is an invalid document, expected byte or unicode string.
```

**Comment by dsherry** [comment]
Had discussion with @jeremyliweishih @boopboopbeepboop @cmancuso

The short-term plan (tracked by this issue) is to add a data check error when natural language features contain `nan`s, asking users to either drop those rows or fill in the missing values on their own through some other means.

Long-term we will discuss a) options for handling missing natural language features beyond simply dropping rows and b) ways our transformers and/or estimator can still benefit from the information contained in the rows with missing values for the natural language features in question.

**Comment by gsheni** [comment]
@dsherry @chukarsten @jeremyliweishih Can we look into handling NaNs in natural language columns **now**? It is a very common situation to have NaNs in NL columns, and I have seen a few Kaggle datasets with NaNs in NL columns. 
One example?
- https://www.kaggle.com/c/tweet-sentiment-extraction/overview

**Comment by freddyaboulton** [comment]
@gsheni AutoMLSearch is able to handle missing values in natural language features. We did this by placing the imputer after the natural language featurizer

```python
from evalml.automl import AutoMLSearch
import pandas as pd
import woodwork as ww

X = pd.DataFrame({"NatLang": ["This is a Natural Language Feature",
                              "I love Machine Learning", None] * 100,
                  "Double": [1.2, 3.2, 2.3] * 100,
                  "Cat": ["a", "b", "c"] * 100})
y = pd.Series([1, 0, 1] * 100)
X.ww.init(logical_types={"NatLang": "NaturalLanguage"})

automl = AutoMLSearch(X, y, "binary", verbose=True)
automl.search()
```

```
automl.best_pipeline.graph()
```

![image](https://user-images.githubusercontent.com/41651716/149377625-1ae4e0ef-3b16-45f8-a89a-0df098dd93da.png)

**Comment by gsheni** [comment]
@freddyaboulton Then why do we have a `NaturalLanguageNaNDataCheck` ?

**Comment by gsheni** [comment]
@freddyaboulton Yep sounds good.

**Comment by freddyaboulton** [comment]
Awesome, closing in favor of https://github.com/alteryx/evalml/issues/3240 !
