### ISSUE TITLE
Unclear when generating predictions

### ISSUE THREAD

**Issue by moezali1** [alteryx/evalml#2003]
It is a little bit unclear when generating predictions on the test set using the following code:

```
pipeline = automl.best_pipeline
pipeline.fit(X_train, y_train)
pipeline.predict(X_test)
```

The return from `predict` is the `woodwork.datacolumn.DataColumn`  instead of the predictions as one would expect. It is possible that users familiar with `woodwork` would be able to convert it to series by using the `to_series` function but it's not 100% clear in the README.md example. I suggest changing the above code with the following:

```
pipeline = automl.best_pipeline
pipeline.fit(X_train, y_train)
pipeline.predict(X_test).to_series()
```

**Comment by dsherry** [comment]
Thanks @moezali1 for this feedback! I agree. We'll update the docs.

#2018 will make this a lot simpler.

**Comment by angela97lin** [comment]
Since #2018, I think this is no longer an issue. Closing!
