### ISSUE TITLE
[SPIKE] Using Winsorization to cap outliers

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2004]
I'd like to be able to perform winsorization on my input data i.e. to be able to bound outliers in my numerical features to a certain value or within a certain range, as well as specify the value that these outliers should take.

A few use cases:
- To be able to specify a value range outside of which points would be considered outliers
- Provide the option to replace these outlier values with a static value
- Provide the option to cap these outliers, for example within 3 standard deviations.

**Comment by dsherry** [comment]
Agreed! It would help to have a specific dataset for which this approach is beneficial.
