### ISSUE TITLE
Spike: Add 3.9 support to sktime

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2044]
The sktime maintainers said they would like help making sktime compatible with python 3.9.

A good place to start is by updating [their CI config](https://github.com/alan-turing-institute/sktime/blob/79ac80ab65adb30fdf233e98433646c1989da2fc/CONTRIBUTING.md#infrastructure) and seeing what breaks when you try to build on 3.9. 

It's possible this can't be done if some of their dependencies do not yet support 3.9. In that case, it'd be nice to provide a report of what does and doesn't support 3.9 and if possible find out when those dependencies will support 3.9.

**Comment by dsherry** [comment]
@freddyaboulton I like it! Let's see what happens when we update their CI, and take it from there.

**Comment by freddyaboulton** [comment]
Done: https://pypi.org/project/sktime/#files
