### ISSUE TITLE
Dependency Bot: Trigger CI Tests

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#2045]
Github action workflows have a limitation where workflows cannot trigger other workflows. In this case our dependency bot putting up a PR cannot trigger our CI tests. To get around this we need to provide a personal access token instead of using the repo token.  Here is an example: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

**Comment by gsheni** [comment]
@jeremyliweishih I can provide you with a personal access token
