### ISSUE TITLE
Compute partial dependence for categorical variables 

### ISSUE THREAD

**Issue by tyler3991** [alteryx/evalml#2056]

**Comment by tyler3991** [comment]
I filed this after having a conversation with @rpeck

**Comment by freddyaboulton** [comment]
@tyler3991 Can you provide more info? I believe our partial dependence method supports categoricals

https://github.com/alteryx/evalml/issues/1509

**Comment by dsherry** [comment]
I believe #1509 fixed this! This issue tracks verifying that, make sure we have docs example in model understanding too
