### ISSUE TITLE
Add method to convert actions to a preprocessing pipeline

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2058]
Following the close of https://github.com/alteryx/evalml/pull/1981, we decided that rather than adding an `actions` parameter to allow AutoMLSearch to address actions, we will have the user address them beforehand. We will help with this process by creating a pipeline of components that can be used to address actions. 

This design choice will result in two separate pipelines which are required to take the original data to the model result: the preprocessing transformations from actions, and the pipeline generated from AutoMLSearch. Users who want to use their original data must piece together the two pipelines. We will provide a utility method to help with this.

This issue tracks creating a method that will generate a pipeline from actions, as well as a utility method to combine multiple pipelines.

**Comment by dsherry** [comment]
@angela97lin the short-term solution for this is to transform the actions into a list of component objects, yes? Meaning, we shouldn't mark this issue as blocked on #2103

**Comment by angela97lin** [comment]
@dsherry The short term solution is already merged as `_make_component_list_from_actions`; we can make this public, but this issue tracks the "longer term" solution of wrapping this in a pipeline.

**Comment by dsherry** [comment]
@angela97lin has a PR in flight which will unblock this: #2625
