### ISSUE TITLE
Data check actions: support TargetImputer in pipelines

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2059]
#1989 tracks adding the TargetImputer to EvalML. However, like the undersampler component (and the polynomial detrender?), it requires the target (y) to be passed along from component to component.

This issue is blocked by https://github.com/alteryx/evalml/issues/2053. When we complete that work, we should test and validate that we can use the TargetImputer in pipelines.

**Comment by dsherry** [comment]
We completed #2053 and have made other related improvements to the component graph. Closing!
