### ISSUE TITLE
Add support for computing scores of target data with NaN values

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2063]
Currently, our objectives do not allow us to score on target data that contain NaN values. We could be more flexible about this; one option that comes to mind is simply dropping the NaN rows.

Minimal repro:

```
from evalml.demos import load_breast_cancer
from evalml.pipelines import BinaryClassificationPipeline

class Pipeline(BinaryClassificationPipeline):
    component_graph = ["One Hot Encoder", "Random Forest Classifier"]
    
X , y = load_breast_cancer(return_pandas=True)
y[1] = np.nan
pipeline = Pipeline({})
pipeline.fit(X, y)
pipeline.score(X, y, ['log loss binary'])
```

results in 
```
---------------------------------------------------------------------------
PipelineScoreError                        Traceback (most recent call last)
<ipython-input-6-b709878a281c> in <module>
      1 # X , y = load_breast_cancer(return_pandas=True)
      2 
----> 3 pipeline.score(X, y, ['log loss binary'])

~/Desktop/evalml/evalml/pipelines/classification_pipeline.py in score(self, X, y, objectives)
    126         if y_predicted_proba is not None:
    127             y_predicted_proba = _convert_woodwork_types_wrapper(y_predicted_proba.to_dataframe())
--> 128         return self._score_all_objectives(X, y, y_predicted, y_predicted_proba, objectives)
    129 
    130     def _compute_predictions(self, X, y, objectives, time_series=False):

~/Desktop/evalml/evalml/pipelines/pipeline_base.py in _score_all_objectives(self, X, y, y_pred, y_pred_proba, objectives)
    291         if exceptions:
    292             # If any objective failed, throw an PipelineScoreError
--> 293             raise PipelineScoreError(exceptions, scored_successfully)
    294         # No objectives failed, return the scores
    295         return scored_successfully

PipelineScoreError: Log Loss Binary encountered ValueError with message (y_true contains more than two unique values):

  File "/Users/angela.lin/Desktop/evalml/evalml/pipelines/pipeline_base.py", line 286, in _score_all_objectives
    score = self._score(X, y, y_pred_proba if objective.score_needs_proba else y_pred, objective)

  File "/Users/angela.lin/Desktop/evalml/evalml/pipelines/binary_classification_pipeline.py", line 54, in _score
    return ClassificationPipeline._score(X, y, predictions, objective)

  File "/Users/angela.lin/Desktop/evalml/evalml/pipelines/pipeline_base.py", line 262, in _score
    return objective.score(y, predictions, X)

  File "/Users/angela.lin/Desktop/evalml/evalml/objectives/objective_base.py", line 80, in score
    self.validate_inputs(y_true, y_predicted)

  File "/Users/angela.lin/Desktop/evalml/evalml/objectives/binary_classification_objective.py", line 64, in validate_inputs
    raise ValueError("y_true contains more than two unique values")
```

**Comment by chukarsten** [comment]
@angela97lin let's proceed with this and drop the NaNs

**Comment by dsherry** [comment]
Two ways to do this. 1) drop nans in advance 2) update our objectives to be tolerant to nans, ignore rows with nan target or prediction

Personally I like option 2 because it still works if model predicts nan.

**Comment by angela97lin** [comment]
from https://ayx.atlassian.net/wiki/spaces/PS/pages/532971559/Adding+support+for+computing+scores+of+prediction+and+target+data+with+NaN+values:

We will close issue Add support for computing scores of target data with NaN values · Issue #2063 · alteryx/evalml  without adding support for targets with NaNs.

We are primarily concerned about the case where y_predicted contains NaN, as the first user flow is covered by data checks.
Giving users an easy and “seamless” experience where they are returned a score regardless of what the model predicts is nice, but could lead to a false sense of what is happening:

* Right now, as we develop, we have a good sense of when things are not as we expect when our pipelines produce NaN scores. If we were to change this behavior, we could be hiding underlying bugs that may have larger implications.
* Similarly, if we simply remove NaN predictions, users may not be aware of any potential underlying issues with their model, leading to a false sense of security
* Models which return a NaN score currently are ranked at the bottom of the leaderboard. However, with this update, they may jump to the top of the leaderboard--this could be a good thing (if model generally performs well but returned a NaN prediction for just a handful of rows) or a terrible thing (if model generally predicted NaN but accurately predicted just a handful of rows correctly), but it is not clear.
* Different models with different NaN rows will lead us to not have a fair apples-to-apples comparison since we are scoring on slightly different data

Most of our models are not models where we’d expect to return np.nan values. Until this is no longer the case, it is better to not overcompensate. Thus, the best thing to do for now is to keep our current behavior until we have more reason and use cases that would benefit from dropping NaNs from scoring.
