### ISSUE TITLE
Error reproducing official start tutorial

### ISSUE THREAD

**Issue by moezali1** [alteryx/evalml#2066]
Hi,

I am trying to follow through the official tutorial uploaded here: https://evalml.alteryx.com/en/stable/start.html

**My environment:**
```
Python 3.7.4 on Windows 10

evalml==0.20.0
woodwork==0.0.10
numpy==1.19.5
pandas==1.1.5
```

**Code:**

```
import evalml
from evalml import AutoMLSearch
from evalml.utils import infer_feature_types

X, y = evalml.demos.load_fraud(n_rows=1000, return_pandas=True)

X['expiration_date'] = X['expiration_date'].apply(lambda x: '20{}-01-{}'.format(x.split("/")[1], x.split("/")[0]))
X[['lat', 'lng']] = X[['lat', 'lng']].astype('str')
X = infer_feature_types(X, feature_types= {'store_id': 'categorical',
                                           'expiration_date': 'datetime',
                                           'lat': 'categorical',
                                           'lng': 'categorical',
                                           'provider': 'categorical'})

X_train, X_holdout, y_train, y_holdout = evalml.preprocessing.split_data(X, y, problem_type='binary', test_size=.2)

automl = AutoMLSearch(X_train=X_train, y_train=y_train, problem_type='binary', objective='f1', max_batches=1)

automl.search()
```

**The last line caused the error. Here is the trace:**

Batch 1: (1/9) Mode Baseline Binary Classification P... Elapsed:00:02
	Starting cross validation
	Finished cross validation - mean F1: 0.000
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-29-deb26cfd348a> in <module>
----> 1 automl.search()

~\AppData\Roaming\Python\Python37\site-packages\evalml\automl\automl_search.py in search(self, data_checks, show_iteration_plot)
    537 
    538         try:
--> 539             self._add_baseline_pipelines()
    540         except KeyboardInterrupt:
    541             if self._handle_keyboard_interrupt():

~\AppData\Roaming\Python\Python37\site-packages\evalml\automl\automl_search.py in _add_baseline_pipelines(self)
    684             baseline = pipeline_class(parameters={"pipeline": {"gap": gap, "max_delay": max_delay},
    685                                                   "Time Series Baseline Estimator": {"gap": gap, "max_delay": max_delay}})
--> 686         self._engine.evaluate_batch([baseline])
    687 
    688     @staticmethod

~\AppData\Roaming\Python\Python37\site-packages\evalml\automl\engine\sequential_engine.py in evaluate_batch(self, pipelines)
     40                 y = self.y_train.iloc[training_indices]
     41             evaluation_result = EngineBase.train_and_score_pipeline(pipeline, self.automl, X, y)
---> 42             new_pipeline_ids.append(self._post_evaluation_callback(pipeline, evaluation_result))
     43             index += 1
     44         return new_pipeline_ids

~\AppData\Roaming\Python\Python37\site-packages\evalml\automl\automl_search.py in _post_evaluation_callback(self, pipeline, evaluation_results)
    719             percent_better_than_baseline[obj_name] = percent_better
    720 
--> 721         high_variance_cv = self._check_for_high_variance(pipeline, cv_scores)
    722 
    723         pipeline_id = len(self._results['pipeline_results'])

~\AppData\Roaming\Python\Python37\site-packages\evalml\automl\automl_search.py in _check_for_high_variance(self, pipeline, cv_scores, threshold)
    760         """Checks cross-validation scores and logs a warning if variance is higher than specified threshhold."""
    761         pipeline_name = pipeline.name
--> 762         high_variance_cv = bool(abs(cv_scores.std() / cv_scores.mean()) > threshold)
    763         if high_variance_cv:
    764             logger.warning(f"High coefficient of variation (cv >= {threshold}) within cross validation scores. {pipeline_name} may not perform as estimated on unseen data.")

ZeroDivisionError: float division by zero

**Comment by dsherry** [comment]
Thanks @moezali1 ! This appears to be an example of #2023 . We'll look into that.

**Comment by angela97lin** [comment]
@moezali1 Can you try using `evalml==0.22.0` and see if you still get that error? I believe we added a fix for this issue in that version.

**Comment by angela97lin** [comment]
Confirmed that this is no longer an issue in `0.22.0`. If you have any further questions, please don't hesitate to follow up or post a new issue!

![image.png](https://images.zenhubusercontent.com/5d8384c183c48400015315ad/7e7233d6-5d31-4b27-89d4-1ab00ee5d5da)
