### ISSUE TITLE
Rename column names for automl.rankings

### ISSUE THREAD

**Issue by moezali1** [alteryx/evalml#2068]
Hi,

It seems to me that the `score` in the table below is the mean cross-validated score? If yes, It will be good to rename it to `mean_cv_score`. 

Also, in addition to showing the `high_variance_cv` check, it will be a good idea to expose the standard deviation of fold scores as a new column. 

![image](https://user-images.githubusercontent.com/54699234/113299537-fa943c80-92ca-11eb-8828-c006d419049e.png)

**Comment by dsherry** [comment]
Great suggestion, agreed!

> Also, in addition to showing the high_variance_cv check, it will be a good idea to expose the standard deviation of fold scores as a new column.
Filed separately as #2072
