### ISSUE TITLE
Time series: require user to specify a date feature

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2070]
**Background**
Currently, our `DatetimeFeaturizer` generates a few indicator features from every datetime-type input feature. 

Our `TimeSeriesSplit` currently assumes the rows have been ordered by time, but otherwise it doesn't assume to have access to the datetime index itself.

**Goal**
For time series modeling, we need to require that users tag one of their input feature as the time index which EvalML should use throughout modeling. If this hasn't been provided but the problem type is time series, the user should get a clear error.

We need this in order for us to support data splitting for time series, and to support models like ARIMA which are aware of time, and things like seasonal detrending.

**Options**
I see two approaches to this. One is to set the woodwork/pandas index to be the datetime feature in question. Another is to require for time series modeling that a "time" feature is provided alongside the other features.

@ParthivNaresh @freddyaboulton 

I think a great way to add this check is via a data check error. The action to fix would be to halt, ask the user to choose their datetime index and try again. We'll also need a good `AutoMLSearch` error for this case though.

**Comment by ParthivNaresh** [comment]
After our discussion today: [Handling a Specified DateTime Index](https://alteryx.quip.com/yclbA20rZ8ty/Handling-a-Specified-DateTime-Index)
@dsherry @freddyaboulton @angela97lin @chukarsten

**Comment by dsherry** [comment]
Outcome of our discussion was that we prefer user naming a feature as the date feature, rather than using the dataframe index.
