### ISSUE TITLE
Add support for creating pipelines without an estimator as the final component

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2103]
Currently, our pipelines assume that the final component in the component graph is an estimator. We should allow for pipelines that are just a series of transformations (ex: preprocessing pipeline) that do not have an estimator.

This issue tracks adding support for pipelines without an estimator. Right now, `fit` does not error out, but it doesn't make sense to call `predict` or `predict_proba` when we don't have an estimator. Perhaps we should define or allow a `transform` method?

This came up in #2058, where we want to create pipelines from data check actions. These pipelines would only consist of transformers, and no estimators. However, until #2103 is complete, there's not a good way to create these valid preprocessing pipelines based on actions.

**Comment by chukarsten** [comment]
@angela97lin can you update this issue with a little more of the "why?" and use case?  I know we talked about it, but I can't for the life of me remember why.

**Comment by angela97lin** [comment]
@chukarsten Updated the description! 😁

**Comment by dsherry** [comment]
I think my spike in #2110 addresses this! I added a `transform` method on `ComponentGraph`.

**Comment by dsherry** [comment]
Thanks @angela97lin ! To confirm, this is a "nice to have" for data check actions, and our workaround of using a list of components will suffice for now, correct?

**Comment by angela97lin** [comment]
@dsherry Yeah, it'll be a little tricky to deal with target transformations, but it should be doable (just very hacky and not elegant at all).

**Comment by dsherry** [comment]
For whoever picks this up: see #2151

**Comment by dsherry** [comment]
I just closed #2151 because it was stale, but the branch still exists

@angela97lin : @chukarsten has expressed interest in working on this too. I am fine with whatever you two want to do, just let me know!
