### ISSUE TITLE
Prediction explanations: add support for stacked ensemble

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2111]
We'll need XGBoost #1890 to have support first, so all estimators used in the ensemble work with shap.

**Comment by dsherry** [comment]
@freddyaboulton and I chatted about this. This will take a lot of work.

**Comment by dsherry** [comment]
I am thinking that if we assume the metalearner is a linear method, we could put together a solution for this where we sum the contributions from each input pipeline. Would be easiest if we roll our own ensemble impl first in #1930

**Comment by christopherbunn** [comment]
Resolved as part of the work in #2971.
