### ISSUE TITLE
DataCheck for TimeSeries problems - Equal interval data

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2124]
Time series estimators generally require evenly spaced data for out of the box implementation.
For example, for frequency to be properly inferred by either Pandas or the underlying package, dates have to follow their implied frequency:
- Daily (02/22/1994, 02/23/1995, 02/24/1996)
- Monthly (02/1994, 03/1994, 04/1994)
- Yearly (1994, 1995, 1996)
A date can't be missing in the dataset when the rest of the data has implied a certain frequency. Otherwise an error will be thrown. `pandas.infer_freq` can help with this.

Requirements:
- [ ] Equal interval data
- [ ] Data sorted in time order

**Comment by dsherry** [comment]
Yep, while time series support is still in beta, our code should be able to assume that the distance between each row is exactly one time unit. Adding support for more complex use-cases will be future work. So we need a data check which can enforce this constraint.

@ParthivNaresh I agree there's value to be had in having a data check which looks at issues with datetime formatting and parsing, but I think that needs to be a separate issue. This may be of interest to the woodwork team too.

**Comment by freddyaboulton** [comment]
We should also ensure that the the time series data is properly sorted!
