### ISSUE TITLE
AutoMLSearch can't tune pipeline with custom hyperparameters if default param not in custom range

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2131]
Repro

```python
from evalml.demos import load_breast_cancer
from evalml.pipelines import BinaryClassificationPipeline
from skopt.space import Categorical
from evalml.automl import AutoMLSearch
import pytest


class PipelineDict(BinaryClassificationPipeline):
    custom_hyperparameters = {"One Hot Encoder": {"top_n": Categorical([20])}}
    component_graph = {"One Hot Encoder": ["One Hot Encoder"],
                       "Random Forest Classifier": ["Random Forest Classifier", "One Hot Encoder"]}
    
X, y = load_breast_cancer()
automl = AutoMLSearch(X, y, problem_type="binary", allowed_pipelines=[PipelineDict],
                      max_batches=2)
with pytest.raises(ValueError,
                   match="Default parameters for components in pipeline Pipeline Dict not in the hyperparameter ranges"):
    automl.search()
```

I think the problem is that the first batch uses the default parameters. When we call `add_result` with a set of hyperparameters that are not in the range that we use to create the tuner, skopt will throw an error.

We have a [mechanism to deal with this](https://github.com/alteryx/evalml/blob/main/evalml/automl/automl_algorithm/iterative_algorithm.py#L141) when the user specifies custom parameters with `pipeline_params` AutoMLSearch argument but we don't use it for custom_hyperparameter ranges.

I think this is a point in favor of deprecating the custom hyperparameters for pipelines like we discussed doing for #2091. In my opinion, the root cause is that we have two apis for overriding the hyperparameters used in search and we're struggling to maintain both of them.

**Comment by christopherbunn** [comment]
@freddyaboulton I'm having trouble reproducing this on our current main branch. I adjusted the example to work with our current API below. Am I missing something?

```
from evalml.demos import load_breast_cancer
from evalml.pipelines import BinaryClassificationPipeline, MulticlassClassificationPipeline
from skopt.space import Categorical
from evalml.automl import AutoMLSearch
import pytest

X, y = load_breast_cancer()
automl = AutoMLSearch(X, y, problem_type="binary", 
                      allowed_component_graphs={"Pl": ["One Hot Encoder", "Random Forest Classifier"]}, 
                      custom_hyperparameters={"One Hot Encoder": {"top_n": Categorical([20])}}, 
                      max_iterations=2)
automl.search()
```

![image](https://user-images.githubusercontent.com/8752455/124184902-3ab0ba00-da88-11eb-8796-a1636d071a55.png)
![image](https://user-images.githubusercontent.com/8752455/124184936-44d2b880-da88-11eb-98fc-4abb0228a41d.png)

**Comment by freddyaboulton** [comment]
@christopherbunn I think this was fixed in https://github.com/alteryx/evalml/pull/2317 so we can close out!
