### ISSUE TITLE
TimeSeries support for datetime frequency not of unit 1

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2137]
Currently sktime has trouble with predicting datetime values in datasets that have a frequency other than unit 1.
For example, if the data is separated by datetime values at the granularity level of 1 second, 1 minute, 1 day, or 1 month, there is no issue.
However with frequencies of 10 minutes, 2 hours, or 3 months, the `ForecastingHorizon` within sktime runs into issues.
A [bug has been filed with sktime](https://github.com/alan-turing-institute/sktime/issues/805) for more context.

We should have an in-house check for time series data that is passed in with a frequency that falls under this issue, with the intention that the minimum frequency should be used for the data. i.e. 10 minute intervals should be reduced to 1 minute intervals.

**Comment by dsherry** [comment]
@ParthivNaresh yeah I agree. Not including this in the "beta" epic, however I do agree it is important that we support datasets where rows are spaced by intervals not in the specific set you mentioned. But for now, let's punt on this support.
