### ISSUE TITLE
Flaky Windows tests on main

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2141]
I noticed that the Windows unit tests flaked out once or twice on main. Unfortunately, I can't access the runs that failed because I retriggered the tests, but here's a failure I saw on my branch. This issue tracks these failures in case there are more or they become more prevalent. 

https://github.com/alteryx/evalml/runs/2337664211

**Comment by dsherry** [comment]
Got it, I see a dask stack trace. Lol the exception message is "Yikes" 😂

**Comment by dsherry** [comment]
Got [another one](https://github.com/alteryx/evalml/pull/2261/checks?check_run_id=2614687361) today on a trivial PR. Stack trace looked interesting, dask unit test having to do with the error callback.

**Comment by freddyaboulton** [comment]
The links here reference `test_automl_immediate_quit` whose flakiness is tracked by #2341 so I will close this issue out!
