### ISSUE TITLE
CV fold for ensembler after ensembling_indices split

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2144]
Currently in AutoML, if we want to train an ensemble, we create an ensemble split (https://github.com/alteryx/evalml/blob/16c30b85765046ccac0ab587b9a7b525a329fac0/evalml/automl/engine/engine_base.py#L220). This is to prevent overfitting, by not training the ensemble on the same data that the metalearners are trained on.

Then, in `train_and_score_pipeline`, we split the ensembling indices data using our data splitter and train/validate on one fold of the data (https://github.com/alteryx/evalml/blob/16c30b85765046ccac0ab587b9a7b525a329fac0/evalml/automl/engine/engine_base.py#L145). Is this necessary? The [ensemble](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.StackingClassifier.html) internally already does cross-validation. For small datasets, this means we're scoring on 1/3 * 0.2 (ensemble indices size) of data. For the happiness dataset with 128 rows (#2093), the mean_cv_score is calculated using just 8 rows. 😬  Perhaps we can remove these lines of code and just train the ensemble on the full `ensemble_indices`.

@dsherry @bchen1116 @rpeck FYI

**Comment by dsherry** [comment]
Marking this as blocked on #2093. Its possible the fix for #2093 includes fixing the code described here!

**Comment by angela97lin** [comment]
Closed by #2260
