### ISSUE TITLE
ComponentGraph list input: allow users to specify custom component names

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2146]
This came up during #2133. The use case we have in mind is that when users define a component graph as a list with duplicate components, the component names in the `ComponentGraph` object get appended with indices in a way that users may find confusing. 

One possible solution is to let users provide tuples of `(component name, component glass)` in the list. See the comment from #2133 below. 

One thing to keep in mind is that we already allow for this when using the dict api. Is it time to deprecate the list api?

> I agree it's weird. One thing I thought about doing was be able to specify custom component names for the list api by using tuples. Something like
> 
> ```python
> class MyPipeline(BinaryClassificationPipeline):
>      component_graph = [("My Imputer", "Imputer"), ("Cool Classifier", "Logistic Regression Classifier")]
> ```
> 
> but I thought that too big a change for what the original issue asked for. Plus, not sure how long the list api will be around 😅  I will file an issue so we can decide if this is worth doing and prioritize if so.

_Originally posted by @freddyaboulton in https://github.com/alteryx/evalml/pull/2133#discussion_r614887291_

**Comment by angela97lin** [comment]
We've deprecated the list API so I think we can close this issue!
