### ISSUE TITLE
Update ``generate_pipeline_code`` to create instances instead of pipeline subclasses

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2160]
Post work done in #2091, we will no longer need `generate_pipeline_code` to create a pipeline subclass. We should update the method to create an instance instead. This will address this comment as well: https://github.com/alteryx/evalml/pull/2091#discussion_r616044177

**Comment by dsherry** [comment]
Note that as part of this issue, we will want to add back some of the tests which were removed in #2091 . [Example](https://github.com/alteryx/evalml/pull/2091/files#diff-e4378e6e13b665211595128d707f4670da6254c82a90fec42dcc324377db9b8aL1770).
