### ISSUE TITLE
Pipeline API redesign followup work

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2161]
This epic tracks issues that fell out of this PR: https://github.com/alteryx/evalml/pull/2091

**Comment by dsherry** [comment]
@angela97lin and I just reviewed these issues. Top priority is #2158 (docs updates from #2091 ), #2130 (API for automl freezing/hyperparams) and #2159 (automl allowed pipelines). Everything else in this epic is smaller and/or blocked on those three issues. So, closing this epic.
