### ISSUE TITLE
Address need to duplicate pipeline parameters for time series pipelines in automl

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2166]
Post #2091, we pass pipeline instances to `allowed_pipelines` for AutoMLSearch. For time series pipelines, we have to specify `gap` and `max_delay`. However, in AutoMLSearch, we also have a `problem_configuration` parameter where we expect `max_delay` and `gap` as well. This means that the user has to duplicate these parameters (when initializing pipelines to pass to `allowed_pipelines` and when passing to AutoMLSearch). 

We should see if we can remove this redundancy. My guess is that we introduced `problem_configuration` before because we were working with pipeline classes and needed to store the parameters we wanted to use when creating our pipelines. Now that we're passing around pipeline instances, this should no longer be necessary, but we may need to verify this and change any logic that looks at `problem_configuration` to use the `gap` and `max_delay` of the input pipelines to `allowed_pipelines` instead.

**Comment by freddyaboulton** [comment]
@angela97lin will a combination of #2159 and #1637 fix this problem?

**Comment by dsherry** [comment]
@freddyaboulton I agree that #2159 will fix this. Let's keep it open until that issue is resolved.
