### ISSUE TITLE
Pipeline: support ComponentGraph instance as input

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2168]
In #2091 our pipelines now require a `component_graph` parameter. This parameter can either be a) a list of components, either by string name for our core set or a component class, or b) a dictionary describing the component graph in the format required by `ComponentGraph`

I think we should support a third option: providing a `ComponentGraph` instance directly to the pipeline init. It should be a small change :)
https://github.com/alteryx/evalml/pull/2091/files#diff-e3cc5bc8079883f5d6d5d526a2e769765d139a49d1c6528dbb0f6ccd83aa75d2R72

**Comment by angela97lin** [comment]
This might be added by #2332. I'll take this issue, and use it to make sure that we have test coverage for this :)

**Comment by angela97lin** [comment]
Note: this was added via https://github.com/alteryx/evalml/blob/19025c81fb00b23ef4a43f9a9dc355474f300fc2/evalml/pipelines/pipeline_base.py#L76, but we should make sure we have good coverage and add tests as necessary. We should also update docstrings accordingly.
