### ISSUE TITLE
Printing component graph fails

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#2204]
Trying to print the component graph for pipelines in AutoMLSearch fails. This probably is related to the `repr` method for the components generated through `make_pipelines`, since we don't see the same behavior when calling a component graph in regular pipelines. This is run with Jupyter Lab

![image](https://user-images.githubusercontent.com/22552445/116477447-9f625500-a84a-11eb-8f59-5dcfca38c061.png)

![image](https://user-images.githubusercontent.com/22552445/116477542-c456c800-a84a-11eb-9c7d-a07f87eaf598.png)

**Comment by dsherry** [comment]
Thanks for filing!

One question which @chukarsten had: do we get the same behavior in python/ipython as we do in jupyter? Perhaps jupyter uses `repr` but python/ipython don't.

**Comment by bchen1116** [comment]
Good question!
Looks like it works in Python:
![image](https://user-images.githubusercontent.com/22552445/116604850-ac3f8100-a8fc-11eb-89a7-c1541cd6f104.png)

As well as IPython:
![image](https://user-images.githubusercontent.com/22552445/116604975-d3964e00-a8fc-11eb-988e-40f3e5f3148c.png)

This seems to be just a jupyter thing, as jupyter notebook also fails:
![image](https://user-images.githubusercontent.com/22552445/116605167-11937200-a8fd-11eb-92a8-e988e75f44f0.png)
