### ISSUE TITLE
Use max_depth=1 in code that uses featuretools to avoid warning

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2219]
The latest featuretools release issues a warning when there is only one entity in the set and `max_depth` > 1. We should manually set `max_dept=1` in our components that use featuretools (DFSTransformer, TextFeaturizer) to avoid a warning. 

You can see this in the l[atest release changes CI](https://github.com/alteryx/evalml/runs/2480031411#step:9:234):

```
 Only one entity in entityset, changing max_depth to 1 since deeper features cannot be created
```

**Comment by Juliodonadello** [comment]
and if we want to create more features using a single entity in entityset? max_depth=1 makes dfs() useless in this case.

**Comment by thehomebrewnerd** [comment]
> and if we want to create more features using a single entity in entityset? max_depth=1 makes dfs() useless in this case.

@Juliodonadello If you only have a single dataframe in your EntitySet, you should get the same number of features, even with a larger `max_depth` setting since Featuretools does not do any feature stacking for single table EntitySets. DFS will still generate transform features on the table with `max_depth=1`.

**Comment by Juliodonadello** [comment]
Maybe i'm doing something wrong but dfs isn't generating transform features. My entity is:

train_set = ft.EntitySet(id = 'train')
train_set.add_dataframe(
    dataframe_name='df_train',
    dataframe=df_tr,
    index='CODIGO_CLIENTE'
)

Entityset: train
  DataFrames:
    df_train [Rows: 20000, Columns: 65]
  Relationships:
    No relationships

And my dfs is: 
feature_matrix, feature_defs =  ft.dfs(entityset=train_set,
                                                           target_dataframe_name='df_train',
                                                           agg_primitives= ['count','sum'],
                                                           max_depth=1)

I'd tried the same code with the examples datasets and it works fine with 1 table, i appreciate your help.

**Comment by thehomebrewnerd** [comment]
@Juliodonadello In your code above you are trying to create aggregation features using the `count` and `sum` primitives, but aggregations only work with multi-table EntitySets where values can be aggregated across tables. You will not be able to generate aggregation features using a single table EntitySet (or with `max_depth=1`).

It is also possible that the default transform primitives are not finding any columns in your dataset that are valid inputs for the default primitives, depending on the data types of your input columns.

**Comment by thehomebrewnerd** [comment]
@Juliodonadello Also, if you have questions or issues with Featuretools those would be best asked in the Featuretools repo. If you have not already seen them, you might want to review some of the Featuretools documentation for more details on how Featuretools DFS works: https://featuretools.alteryx.com/en/stable/getting_started/getting_started_index.html

**Comment by Juliodonadello** [comment]
> @Juliodonadello In your code above you are trying to create aggregation features using the `count` and `sum` primitives, but aggregations only work with multi-table EntitySets where values can be aggregated across tables. You will not be able to generate aggregation features using a single table EntitySet (or with `max_depth=1`).
> 
> It is also possible that the default transform primitives are not finding any columns in your dataset that are valid inputs for the default primitives, depending on the data types of your input columns.

Thanks for your answer :)
