### ISSUE TITLE
Fix Lead Scoring Demo

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#2221]
Currently, our lead_scoring demo doesn't use sampling in order to avoid a model that predicts all positive values, as seen [here](https://github.com/alteryx/evalml/pull/2128#discussion_r625120090). However, we have seen these trivial models in past docs, primarily [here](https://evalml.alteryx.com/en/v0.17.0/demos/lead_scoring.html) and [here](https://evalml.alteryx.com/en/v0.19.0/demos/lead_scoring.html).

This issue tracks looking into this demo, figuring out why the performance is poor, and setting up a fix for it.

**Comment by dsherry** [comment]
Thanks for filing @bchen1116 !

Similar task to #2145
