### ISSUE TITLE
Rename `HighlyNullDataCheck` to `HighlyNullColumnsDataCheck`

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#2233]
With the addition of `HighlyNullRowsDataCheck` in #2222 we should rename `HighlyNullDataCheck` for clarity and issue a deprecation warning as well.

**Comment by dsherry** [comment]
Let's wait to move on this until we resolve the conversation in #2222

**Comment by dsherry** [comment]
We can close this because we took a different direction in #2222.
