### ISSUE TITLE
Pmdarima can't be installed via conda alongside sktime

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2237]
Currently `pmdarima` and `sktime` are incompatible when installing through conda. Therefore `pmdarima` can't be included in the feedstock as it will fail to install all dependencies due to conflicts.

This issue tracks [that conflict](https://github.com/alan-turing-institute/sktime/issues/860).

**Comment by dsherry** [comment]
Yep. Thanks for filing. Tracks known limitation. Hopefully the community can resolve this. Let's check back on this soon.

**Comment by freddyaboulton** [comment]
May be fixed. Marking as tech debt. 

https://github.com/alkaline-ml/pmdarima/issues/429

Closing criteria is to add pmdarima to our feedstock recipe?
