### ISSUE TITLE
Uncap version for Sphinx

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#2246]
Sphinx 4.0.0 introduces new api calls that replace `sphinx.add_javascript` and `sphinx.add_stylesheet`. Additionally, it created a few errors in the doc builds with cross references, such as `/home/docs/checkouts/readthedocs.org/user_builds/feature-labs-inc-evalml/envs/2244/lib/python3.8/site-packages/evalml/automl/automl_search.py:docstring of evalml.automl.automl_search.search:: WARNING: more than one target found for cross-reference 'ProblemTypes': evalml.problem_types.ProblemTypes, evalml.problem_types.problem_types.ProblemTypes`

An example of the doc build fail is [here](https://readthedocs.com/projects/feature-labs-inc-evalml/builds/629821/).

This issue tracks uncapping the Sphinx version and fixing the documentation

**Comment by dsherry** [comment]
@bchen1116 closed this in #2244 , closing
