### ISSUE TITLE
Handling of BaseSampler's Transform

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2273]
Connected to the hotfix for 0.24.0 #2272  this issue covers the proper handling of BaseSampler's transform() return and how it's being changed to return None for y.

Successful completion of this involves proper testing to replace `test_undersampler` in `tests/model_understanding_tests/test_permutation_importance.py`.

**Comment by chukarsten** [comment]
@dsherry @freddyaboulton @angela97lin placeholder for now...too tired to put in the rest of the details, haha.

**Comment by dsherry** [comment]
My spike #2210 would fix this!
