### ISSUE TITLE
Perf test and deep dive into Elastic Net

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#2289]
PR [2269](https://github.com/alteryx/evalml/pull/2269) put up a fix for the Elastic Net classifier that partially solves the issues we had for fraud/lead-scoring demos. However, we want to look further into this Elastic Net classifer. We have 2 main questions:
- Are we incurring a double shrinkage using this classifier, as specified [here](https://en.wikipedia.org/wiki/Elastic_net_regularization#Specification)? This could explain the poor performance we have been seeing.
- Can we use SKLearn's [impl of Elastic Net](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html) rather than our current use of SGDClassifier? How does this change the performance of our classifier (run perf tests here)

Discussion chain in the comments on [this doc](https://alteryx.quip.com/xOV6A0uLg7aX/Fraud-and-Lead-Scoring-Jupyter-Notebook-changes)

TODO:
- Perf test new Elastic Net
- Figure out which to use moving forward, and look more into the performance to ensure we aren't subjecting our estimator to double shrinkage

**Comment by freddyaboulton** [comment]
The new default values for elastic net introduced in #2269 make AutoMLSearch throw an error on one of the training folds for the elastic net pipeline on the cjs dataset.

Repro
```python
import pandas as pd
from evalml import AutoMLSearch

X = pd.read_csv("/Users/freddy.boulton/Downloads/cjs.csv")
y = X.pop("TR")
automl = AutoMLSearch(X, y, "multiclass", pipeline_parameters={"Elastic Net Classifier": dict(alpha=0.5, l1_ratio=0.5)})
automl.search()
```

![image](https://user-images.githubusercontent.com/41651716/119043517-1e990380-b987-11eb-926b-b1a48566d143.png)

Using the old values fixes the issue:
```python
automl = AutoMLSearch(X, y, "multiclass", pipeline_parameters={"Elastic Net Classifier": dict(alpha=0.5, l1_ratio=0.5)})
automl.search()
```

Looks like it's tough to come up with reasonable defaults for this classifier. @bchen1116 I like the idea of switching the estimator class but I don't think the sklearn estimator you linked to has a `predict_proba` method. 

Can you we use `LogisticRegressionClassifier` but hard-code the `penalty` to be [elasticnet](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)? Do we even need `ElasticNetClassifier` if `LogisticRegressionClassifier` can do what it can do?

[cjs.csv](https://github.com/alteryx/evalml/files/6518573/cjs.csv)

**Comment by bchen1116** [comment]
Good point @freddyaboulton! I'll look into it and see if the performance is similar!
