### ISSUE TITLE
Test Profiling

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2298]
Goal:

1. Identify top 10 maximum run time tests
2. Identify top 10 memory usage tests
3. Evaluate the impact of streamlining fake test data into singular test fixtures within conftest
4. @dsherry what did I miss?

**Comment by freddyaboulton** [comment]
Did some work for point 1 about a week ago:

https://github.com/alteryx/evalml/issues/1815#issuecomment-837379777

**Comment by dsherry** [comment]
Looks good to me!

The primary goal of this spike is to speed up our unit tests. Memory usage is secondary.

The "top 10" is fuzzy, haha. Basically we wanna know which of our tests are the worst offenders when it comes to runtime.

**Comment by chukarsten** [comment]
@freddyaboulton thanks a ton for doing that and bringing it back up.  That already seems to reveal a lot of pain points.  I think ultimately we're going to want to profile the tests themselves and see which function calls are the big hitters as well, so we'll need to drill down into that.  I look forward to it.

**Comment by dsherry** [comment]
@freddyaboulton I believe you've completed this, correct?

**Comment by freddyaboulton** [comment]
Yes! Closing.
