### ISSUE TITLE
Small data: use 10-fold CV instead of 3-fold

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2312]
TBD: size threshold. Perhaps 500 rows?

**Comment by dsherry** [comment]
@christopherbunn should this be in review instead of in progress?

**Comment by christopherbunn** [comment]
@dsherry Yes! That's my bad, it looks like ZenHub doesn't automatically link a PR to an issue if the PR notes references more than one issue 😬

**Comment by christopherbunn** [comment]
After running the performance tests on the #2414, it's evident that this change would not directly translate into an increase in model performance and increase the fit time. We'll close this out unless there is a change to EvalML in the future such that increasing the CV folds will result in model performance.
