### ISSUE TITLE
Fix SMOTE Oversampler k_neighbors arg

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#2324]
In some imbalanced tests, SMOTE ran into errors where the default `k_neighbors` value was too high (below)

We had initially chosen to use the default `k_neighbors` value provided by SMOTE, but it might be useful to lower this default. This issue tracks creating a fix for this issue, whether that be lowering the value and providing a better error message, or something else. 

**Repro**
```python
from evalml import AutoMLSearch
from evalml.demos import load_fraud
X_train, y_train = load_fraud(n_rows=100)
automl = AutoMLSearch(X_train=X_train, y_train=y_train, problem_type='binary')
automl.search()
```

![image](https://user-images.githubusercontent.com/22552445/120675359-fcad7f80-c462-11eb-8194-82fc9a0de888.png)
![image](https://user-images.githubusercontent.com/22552445/120675378-01723380-c463-11eb-8f7c-1fe9160fa877.png)

**Comment by chukarsten** [comment]
@bchen1116 thanks for filing this.  I think we'll want a reproducer added to our SMOTE test coverage.  Can we add that to the acceptance criteria of this issue?
