### ISSUE TITLE
Upgrade to Woodwork v0.4.1

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2327]
- We released a [new version](https://woodwork.alteryx.com/en/latest/release_notes.html#v0-4-0-may-26-2021) of Woodwork (with no breaking changes).

**Comment by freddyaboulton** [comment]
I think we should just upgrade to 0.4.1 at this point to make use of `concat_columns`!

**Comment by jeremyliweishih** [comment]
@gsheni I like @freddyaboulton's plan to utilize the new features 0.4.0 and 0.4.1 has in EvalML but this would make #2329 redundant (as we would need to pin on 0.4.1). What do you think of moving forward with upgrading to 0.4.1 (and adding the new features to EvalML) and closing #2329?

**Comment by gsheni** [comment]
@jeremyliweishih can do the upgrade and un-pin at the same time? Make it so the requirements say `woodwork>=0.4.0`?

**Comment by jeremyliweishih** [comment]
@gsheni yup I can give that a go!
