### ISSUE TITLE
Add CI test to install Woodwork from main and run the unit tests

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2328]
- We prevent Woodwork release breaking changes OR know about they ahead of time, by setting up a workflow that does the following.
  1. Every few hours, if there as been a recent commit to `main` of Woodwork, run the below steps. 
  2. git clone the latest code from Woodwork, and run the EvalML unit tests
  3. If there is a failure notify the dev team  (OR some other action)

> Note: By recent commit I mean in the last few hours

**Comment by chukarsten** [comment]
@gsheni is this an ask for the EvalML team to complete?

**Comment by gsheni** [comment]
@chukarsten My team will be handling this (@jeff-hernandez will be doing it). We are planning to do it in the upcoming sprint (June 8).

**Comment by gsheni** [comment]
Closing this for now, as Woodwork will be treated as other dependencies.
