### ISSUE TITLE
Make Woodwork version less restrictive

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2329]
- We had originally pinned the Woodwork version because new versions of Woodwork were being released, with breaking changes. These would break the EvalML unit tests
- Once #2328, has been added, this can be mitigated.
- Therefore the Woodwork version should be made less restrictive `woodwork >= _____` (rather than `==`)

**Comment by jeremyliweishih** [comment]
Closing in favor of #2327 and doing the unpinning there.
