### ISSUE TITLE
Add alteryx_open_src_update_checker as an extras_require package

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2333]
- The alteryx_open_src_update_checker supports EvalML and can be added to setup.py
- https://github.com/FeatureLabs/alteryx-open-src-update-checker/
- Example PR: https://github.com/alteryx/woodwork/pull/959

**Comment by chukarsten** [comment]
@gsheni let us know when @frances-h is ready to do this work and we'll assign it to a sprint!

**Comment by gsheni** [comment]
@chukarsten @frances-h should be able to do this during the upcoming sprint (June 8)
