### ISSUE TITLE
Partial dependence fails if computed percentiles are too close together

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2336]
Repro

```python
from evalml.pipelines import RegressionPipeline
from evalml.model_understanding import partial_dependence
import pandas as pd
import pytest

pl = RegressionPipeline(["Random Forest Regressor"])
X = pd.DataFrame({"a": list(range(30)), "b": list(range(-10, 20))})
y = 10*X['a'] + X['b']

pl.fit(X, y)

X_pd = X.copy()
X_pd['a'] = X['a'] * 1.e-10

with pytest.raises(ValueError, match="percentiles are too close to each other"):
    partial_dependence(pl, X_pd, "a", grid_resolution=5)
```

This is similar to https://github.com/alteryx/evalml/issues/1923. The error is being raised by [sklearn](https://github.com/scikit-learn/scikit-learn/blob/15a949460dbf19e5e196b8ef48f9712b72a3b3c3/sklearn/inspection/_partial_dependence.py#L94). 

I think we should still raise an error but perhaps it should be its own exception class and make it clear that partial dependence cannot be computed for these kinds of features. I think the same change should be made for the logic we added for #1923.

**Comment by chukarsten** [comment]
I think we need to do a little investigation into `partial_dependence()` to determine why the scale is an issue.   The outcome of this spike should be a recommendation about how to properly handle/or communicate the issue to the user.
