### ISSUE TITLE
Allow test_saving_png_file to run during build_conda_pkg job

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2337]
In #2323, we disabled `test_saving_png_file` during the conda build because we were getting `out of memory` from `Popen` commands issued by graphviz (see image below). This is pretty confusing and my guess is that the directory where the png files are stored in the docker container (pytest tmpdir fixture) is running out of space. The fact that this is all happening within docker may make debugging a bit more complicated.

One possible thing to try is to have each test delete any files it creates once the test finishes and see if it fixes the problem.

![image](https://user-images.githubusercontent.com/41651716/120659663-90c41a80-c454-11eb-9cb7-ea8f649d6542.png)

**Comment by chukarsten** [comment]
Outcome of this is replacement test coverage for saving .png for graphing.  Hopefully, creating this test helps us figure out what the original issue was and the mystery behind "test_env_placehold_placehold_..."
