### ISSUE TITLE
Flaky Dask test

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2341]
I've seen the `test_automl_immediate_quit` dask test flake intermittently on my prs, on a [merge to main](https://github.com/alteryx/evalml/runs/2738729795), and on #2317 [link](https://github.com/alteryx/evalml/pull/2317/checks?check_run_id=2749351258). 

Rerunning the tests usually makes the failure go away but that's not ideal.

The expected outcome of this issue is an explanation of why the test is flaking and/or a solution to make the test not flake anymore!

**Comment by chukarsten** [comment]
I can't seem to recover the specific test runs but this *seems* to always flake on Python 3.7.  I saw it at least 4 times flaking on 3.7.

**Comment by chukarsten** [comment]
Just to add some more information on this, `build_conda_pkg` has failed on Python 3.7 on `test_submit_training_job_single()`, [here](https://github.com/alteryx/evalml/pull/2370/checks?check_run_id=2830544484).

**Comment by chukarsten** [comment]
[Here](https://github.com/alteryx/evalml/pull/2382/checks?check_run_id=2832272083) is an instance of the flake happening on Python 3.8.  First time I've seen it on this version, so I guess the 3.7/dask version disagreement is out.
