### ISSUE TITLE
Component graph improvements

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2349]
We've had a few bugs with our component graph lately. There's a few things we've started doing which the original component graph code didn't support when it was first written, including:
* Components which modify the target, or both the features and the target
* Components which drop rows (the samplers)
* Components which accept input from estimators, transformers, or both
* Ability to have a `transform` method on the component graph
* Ability to pass features through to the output

 This epic tracks improving the component graph implementation and test coverage so that it works properly for these cases and others.

**Comment by angela97lin** [comment]
All the issues are complete! Closing this epic 🥳
