### ISSUE TITLE
Prediction explanations cannot be written to json when target is of type bool

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2366]
Repro

```python
from evalml.model_understanding import explain_predictions_best_worst
from evalml.pipelines import BinaryClassificationPipeline
from evalml.demos import load_fraud
import json
import pytest

pipeline = BinaryClassificationPipeline(["Text Featurization Component", "DateTime Featurization Component",
                                         "One Hot Encoder", "CatBoost Classifier"])
X, y = load_fraud(1000)
pipeline.fit(X, y)

report = explain_predictions_best_worst(pipeline, X, y, output_format="dict")

with pytest.raises(TypeError, match="keys must be str, int, float, bool or None, not numpy.bool_"):
    json.dumps(report)
```

The issue here is that the column names for the predicted probabilities dataframe when the target is boolean changed from base python bools to numpy bool_ dtype.

On the left is main and on the left is 0.24.2:

![column_dtypes](https://user-images.githubusercontent.com/41651716/121538965-389c9380-c9d3-11eb-98cd-638fe3b9dcf5.png)

This is the [line](https://github.com/alteryx/evalml/blob/main/evalml/pipelines/classification_pipeline.py#L107) that is causing this change.

I think there are two fixes here:

1. Update `predict_proba` to not have `np.bool_` types in the column names
2. Apply `_make_json_serializable` to the keys of the probabilities dictionary in the explain predictions module. Probably [here](https://github.com/alteryx/evalml/blob/main/evalml/model_understanding/prediction_explanations/_user_interface.py#L63)

**Comment by dsherry** [comment]
Root cause: can't use default python JSON serializer to serialize numpy bool type. So we need to sanitize the types before trying to serialize, as @freddyaboulton wrote in description.
