### ISSUE TITLE
Add documentation for using ComponentGraphs

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2367]
We should add some sort of documentation for how to use component graphs. Specifically, how does a user specify a DAG-like component graph? How is compute order calculated? How should the user specify the connections and the flow of data throughout the graph?

I think some of these things are not really clear even as a developer, and it would be great to have this for us to have, too.

**Comment by dsherry** [comment]
👍  
ComponentGraph class doesn't currently show up in our API ref

Idea from refinement: let's add this to our user guide. One idea was to add a new page "Component Graph"
