### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'map'

### ISSUE THREAD

**Issue by esitharth** [alteryx/evalml#2380]
Getting this error while running automl.search()

**Comment by freddyaboulton** [comment]
Hi @esitharth ! Thanks for filing. Can you provide a code reproducer so we can dig further? 

My guess is that the `y` is a dataframe instead of a series?

**Comment by esitharth** [comment]
Yes, here is the code that I used.

features = df1.drop(['New_Target'], axis=1)
target = df1[['New_Target']]
X_train, X_test, y_train, y_test=evalml.preprocessing.split_data(features, target, problem_type='multiclass',  test_size=.25)

from evalml import AutoMLSearch
automl=AutoMLSearch(X_train=X_train,y_train=y_train,problem_type='multiclass')

automl.search()
The error occurs here.

**Comment by esitharth** [comment]
Full error is as follows:

*****************************
* Beginning pipeline search *
*****************************

Optimizing for Log Loss Multiclass. 
Lower score is better.

Using SequentialEngine to train and score pipelines.
Searching up to 1 batches for a total of 9 pipelines. 
Allowed model families: decision_tree, linear_model, lightgbm, xgboost, random_forest, catboost, extra_trees

Evaluating Baseline Pipeline: Mode Baseline Multiclass Classification Pipeline
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-37-deb26cfd348a> in <module>
----> 1 automl.search()

c:\users\sitharth\pycharmprojects\lac_reco\venv\lib\site-packages\evalml\automl\automl_search.py in search(self, show_iteration_plot)
    578 
    579         try:
--> 580             self._add_baseline_pipelines()
    581         except KeyboardInterrupt:
    582             if self._handle_keyboard_interrupt():

c:\users\sitharth\pycharmprojects\lac_reco\venv\lib\site-packages\evalml\automl\automl_search.py in _add_baseline_pipelines(self)
    749         logger.info(f"Evaluating Baseline Pipeline: {baseline.name}")
    750         computation = self._engine.submit_evaluation_job(self.automl_config, baseline, self.X_train, self.y_train)
--> 751         evaluation = computation.get_result()
    752         data, pipeline, job_log = evaluation.get('scores'), evaluation.get("pipeline"), evaluation.get("logger")
    753         self._post_evaluation_callback(pipeline, data, job_log)

c:\users\sitharth\pycharmprojects\lac_reco\venv\lib\site-packages\evalml\automl\engine\sequential_engine.py in get_result(self)
     34         Raises Exception: If computation fails. Returns traceback.
     35         """
---> 36         return self.work(**self.kwargs)
     37 
     38     def cancel(self):

c:\users\sitharth\pycharmprojects\lac_reco\venv\lib\site-packages\evalml\automl\engine\engine_base.py in evaluate_pipeline(pipeline, automl_config, X, y, logger)
    221     y.ww.init(schema=automl_config.y_schema)
    222 
--> 223     return train_and_score_pipeline(pipeline, automl_config=automl_config,
    224                                     full_X_train=X, full_y_train=y,
    225                                     logger=logger)

c:\users\sitharth\pycharmprojects\lac_reco\venv\lib\site-packages\evalml\automl\engine\engine_base.py in train_and_score_pipeline(pipeline, automl_config, full_X_train, full_y_train, logger)
    143         y_mapping = {original_target: encoded_target for (encoded_target, original_target) in
    144                      enumerate(full_y_train.value_counts().index)}
--> 145         full_y_train = ww.init_series(full_y_train.map(y_mapping))
    146     cv_pipeline = pipeline
    147     for i, (train, valid) in enumerate(automl_config.data_splitter.split(full_X_train, full_y_train)):

c:\users\sitharth\pycharmprojects\lac_reco\venv\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5463             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5464                 return self[name]
-> 5465             return object.__getattribute__(self, name)
   5466 
   5467     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'map'

**Comment by freddyaboulton** [comment]
@esitharth Thanks! Can you try:

```python
features = df1.drop(['New_Target'], axis=1)
target = df1['New_Target']

X_train, X_test, y_train, y_test=evalml.preprocessing.split_data(features, target, problem_type='multiclass', test_size=.25)

from evalml import AutoMLSearch
automl=AutoMLSearch(X_train=X_train,y_train=y_train,problem_type='multiclass')

automl.search()
```

The problem is that `df1[['New Target']]` creates a dataframe but evalml needs `y` to be a pandas series. Using `df1['New Target']` should create a series and fix the error you're currently seeing.

**Comment by esitharth** [comment]
@freddyaboulton : yes. Tried it. It worked. Thanks for the quick response.

**Comment by freddyaboulton** [comment]
No problem @esitharth !

**Comment by esitharth** [comment]
Hi @freddyaboulton, does evalml handle multi-output and chained multi-output problems?
