### ISSUE TITLE
Multiple AutoML Instances & Thread Contention

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2383]
**Description**
What happens when we run multiple AutoML searches at the same time?  We'd like to investigate what happens when two separate python instances are running AutoML search simultaneously with max_iterations at 4 and 9 so that both AutoML objects are searching through LightGBM and XGBoost.  The intent is to demonstrate a marked reduction in performance with a hypothesized thread contention between the two instances.  

If we can reproduce this performance decrease, we will generate follow up issues for exposing any additional parallelism parameters to allow multiple AutoML searches to run without conflict.

**Acceptance criterion**
Learn what it will take to update all of our components (the estimators in particular) which use multithreading to respect a thread limit.

This will allow us to move on to completing #1475 and any other issues we find in this spike.

**Notes**
My suggestion for how to start: Make a list of all our components. Identify the ones which use multithreading under the hood. For each, verify by hand that running with a thread limit of 1 is much slower than running with a thread limit of 8 or of -1. Use that to check off components which appear to respect thread limit vs those which don't. If the component uses an object from a third-party library, don't be afraid to go read the code and API ref from the third-party library.

Extra credit if you write an integration testing script we can save in looking glass which iterates through all our components and checks that 1 thread is slower to run than max threads, so that we can easily check this again in the future.

**Comment by freddyaboulton** [comment]
For whoever picks this up, this issue may be relevant https://github.com/alteryx/evalml/issues/1475. Basically, catboost and xgboost do not have `n_jobs` parameter so they always run with all threads I believe. Also, I believe our estimators use different parallelism - sklearn uses processes via [joblib](https://joblib.readthedocs.io/en/latest/parallel.html#thread-based-parallelism-vs-process-based-parallelism) xgboost/catboost may be using threads.

**Comment by dsherry** [comment]
+1

Idea for a stress test to prove our fix works: run automl with only catboost, two automl runs in parallel, max iterations 100 or something, and check for no errors.

**Comment by dsherry** [comment]
@chukarsten to coordinate with Cedar -- he said he's been able to repro this.

**Comment by dsherry** [comment]
@angela97lin is about to fix the catboost/xgboost `n_jobs` issue #1475 (via PR #2410). So, the release we cut next week should have the property that all our components which perform multithreading respect the `n_jobs` parameter set by `AutoMLSearch`. That is good news!

@chukarsten let's leave this spike open to track confirming the problem has been resolved.

**Comment by dsherry** [comment]
All signs indicate that this has been resolved. We have not been able to repro this since the `n_jobs` merges. @ryan-s will report back if this reappears. 👍
