### ISSUE TITLE
 Speed up partial dependence for date-time features

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2385]
In PR #2365, we noticed that one of our slowest tests are those that compute partial dependence on datetimes. The reason is that those tests had a date feature with 100 unique dates, and our current partial dependence implementation will compute the partial dependence on every unique date. This means that the `grid_resolution` parameter is not respected for dates and will be slow for datasets with many unique dates.

The underlying problem is that scikit-learn's partial_dependence implementation computes the grid for you and it cannot compute a grid from date features. 

I think it's time we move to our own partial dependence implementation so that we can control how the grid is computed. I sketched out how this could work in the original partial-dependence-for-dates issue #1963 

https://github.com/alteryx/evalml/issues/1963#issuecomment-810628780

**Comment by dsherry** [comment]
@freddyaboulton what sort of performance improvement would we see in the unit tests if we fixed this?

Agreed we should fix this :) and good eye
