### ISSUE TITLE
Record runtime of each unit test as a test artifact

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2396]
It would be awesome if we generated a junit yml or something which recorded the runtime of each test. I am pretty sure pytest has a flag for this.

This would make it easy for us to check if a test is running longer than we expect. It also opens the door for us to write a job which scans for changes in test runtimes and errors out if any tests start running long for some reason. There are certainly other ways to solve the problem of unit test runtime creep--we can discuss that later, independently of this issue.

**Comment by chukarsten** [comment]
Connected to #2411 #CI!
