### ISSUE TITLE
Handle woodwork's Unknown Logical Type

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2426]
Woodwork is planning on releasing an `Unknown` logical type soon (https://github.com/alteryx/woodwork/pull/992).

Some our of unit tests and demos may break:

> The PR that adds the Unknown logical type will also come with the behavior that no columns will be inferred as NaturalLanguage since we don’t have an inference function for NaturalLanguage currently.
> So, if you have any tests/demos/code that relies on the NaturalLanguage logical type being set by default by Woodwork, an update will be needed to explicitly set the appropriate columns as NaturalLanguage after the Unknown update is released.

I also think `AutoMLSearch` will break if users pass in data with `Unknown` logical types given that our components don't know how to handle them. 

Closing criteria:
- [ ] Green CI on a branch that installs the latest woodwork release with Unknown logical type.
- [ ] Design and implementation of how evalml should handle `Unknown` logical type. I think we should ignore these features but down to discuss alternatives and/or how to best achieve that!

**Comment by bchen1116** [comment]
@freddyaboulton I've written a short list of options that we can do [here](https://alteryx.atlassian.net/wiki/spaces/PS/pages/643268717/Handle+Unknown+types+from+Woodwork+in+EvalML), but agreed that we can just drop `Unknown` type in `AutoMLSearch`.
