### ISSUE TITLE
Test compatibility with pandas release 1.2.5

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2432]
- Woodwork plans to change the minimum pandas required version to 1.2.5. See [this PR](https://github.com/alteryx/woodwork/pull/1012)
- EvalML should verify that the pandas release 1.2.5 does not break anything.

**Comment by chukarsten** [comment]
EvalML looks good to move up to pandas 1.2.5 per [these](https://github.com/alteryx/evalml/pull/2441/checks?check_run_id=2906713099) checks.
