### ISSUE TITLE
Update default n_jobs used by XGBoost to not be -1

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2437]
https://github.com/alteryx/evalml/pull/2410 updates XGBoost by exposing the `nthread` parameter passed to XGBoost as `n_jobs`. However, while profiling I noticed that the default value of nthreads=-1 (use all threads) performs slower than using 2 threads. Upon further testing, it seems like after a certain number of threads, the performance drops significantly. In my case, the performance dropped after 16 threads (probably because I have 8-cores, 2 threads per core).

XGBoost docs mention that thread contention could significantly slow down performance of the algorithm: https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.core

This issue tracks investigating this and determining if we should change our default value of -1 to something generally more performant. It alarms me that in my example, having just two threads cut the runtime of `fit` in half.

![image](https://user-images.githubusercontent.com/5422235/123152253-67ceee00-d432-11eb-818a-84a2fee1148a.png)

I initially had this issue tracking CatBoost too, but after running a few more tests, I think the CatBoost differences are just due to variance, and not too concerning.

**Comment by dsherry** [comment]
That is super weird!! Good eye

Yep, perhaps we should a) add logic to our xgboost estimator(s) which if n_jobs is set to -1 detects how many cores are on the box and sends that number to xgboost itself and b) file an issue with xgboost. Does that sound right? Tagging @chukarsten too

**Comment by dsherry** [comment]
Just synced with @tyler3991 on this. #2410 is highest priority to get merged, because it allows an upstream user to set the number of cores used by all our components (in that case, xgboost/catboost are missing from `n_jobs` control). This issue is totally valid/true but also is not required for that, so let's not treat it as highest priority.

@tyler3991 raised another interesting idea for a fix here: we could change our default to a negative number, i.e. "-5". [This stackoverflow post](https://stackoverflow.com/a/62131985) describes how that works.

**Comment by angela97lin** [comment]
After doing some perf testing as part of #2486, we came to the conclusion that XGBoost `n_jobs=-1` does indeed increase runtime. In both 0.27.0 and 0.28.0, we use XGBoost v.1.2. The default for `n_jobs` in XGBoost 1.2 is `1` if the user does not specify. That means that prior to #2410, we were always using the default value of 1. However, in after #2410 was merged in 0.28.0, our XGBoost component now respects the `n_jobs` parameter set by AutoMLSearch. We set, by default, `n_jobs=-1`. Perf tests between 0.27.0 and 0.28.0 show an increase in runtime, meaning that updating XGBoost from using `n_jobs=1` to `n_jobs=-1` caused an increase in runtime.

This is more validation that we should not use the default `n_jobs=-1` for XGBoost!

There's a larger design choice in AutoMLSearch to be discussed here:
We want to help users with unifying multiple libraries under AutoMLSearch. We want our estimators to run as quickly as possible, so setting a default of `n_jobs=1` doesn't make sense if it'll slow down the computation for our other estimators. What should we do then? 

One suggestion could be to have an `n_jobs='auto` setting, which tries to smartly detect what the best n_jobs parameter should be for each estimator. This would require a decent amount of work looking into how each library we support handles threading. XGBoost and LightGBM come to top of mind, through this great Medium post: https://medium.com/data-design/getting-the-most-of-xgboost-and-lightgbm-speed-compiler-cpu-pinning-374c38d82b86


(Here's the Confluence doc: https://alteryx.atlassian.net/wiki/spaces/PS/pages/643235884/Expose+n+jobs+as+a+keyword+argument+for+XGBoost+and+CatBoost)

**Comment by bchen1116** [comment]
Did some initial perf tests on looking glass, which I put [here](https://alteryx.atlassian.net/wiki/spaces/PS/pages/881066744/XGBoost+njobs+parameter+testing). I believe we need to address [this looking glass issue](https://github.com/alteryx/evalml_looking_glass/issues/261) before we can move forward with this.

**Comment by bchen1116** [comment]
@freddyaboulton @chukarsten @angela97lin [here](https://alteryx.atlassian.net/wiki/spaces/PS/pages/881066744/XGBoost+njobs+parameter+testing) are the perf test results that I collected with XGBoost n_jobs. The ultimate conclusion that I came up with was to use `n_jobs=12` as the default for XGBoost. Let me know what your thoughts are, and we can get to closing this issue out!
