### ISSUE TITLE
Design spike: automl and featuretools feature engineering

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2439]
**Background**
There's been [discussion recently](https://alteryx.quip.com/120hAOlhXOg8/AutoML-Upgrade-Feature-EngineeringFeature-Selection) about how featuretools fits in with automl. We currently ask users to run featuretools before running automl. We've been exploring ways to have featuretools run as part of automl, or for a feature store to allow information to be shared between the two.

**Challenges**
One of the things we'd like to do in our new automl algorithm is to run a baseline pipeline without any engineered features. Doing so will give us the ability to show users how much adding featuretools' feature engineering will improve modeling. In order to do this, automl needs a) access to all original unmodified features b) access to all featuretools' engineered features c) a clear way to tell which is which. Q: How can we give automl the ability to ?

An additional related challenge has to do with where we run certain types of feature engineering. Currently, automl adds our text featurizer and datetime featurizer components to our pipelines if needed, and under the hood those components use featuretools primitives. Q: Should we be doing all our feature engineering in the pipelines created by automl, should we be doing all our feature engineering before automl runs, or is it ok to continue to have a hybrid approach?

There may also be implications here from time series. Automl owns data splitting during model training. When we add time series support ( @freddyaboulton ), we'll need to run time-based operations like windowed moving averages and delayed features, which share information between the rows. Q: do our goals for time series mean that we must run those feature engineering steps in automl, after data splitting?

**Comment by freddyaboulton** [comment]
@jeremyliweishih FYI I'm adding this to our "Supporting All WW Types" Epic (#2443) because featuretools will soon adopt ww typing and the question of where we should run featuretools computations is directly related to supporting the full set of ww types. 

This spike is also related to Spike #2423

**Comment by dsherry** [comment]
Another illustrative example for this: #2444 . FT is planning to add url and email address primitives.

**Comment by dsherry** [comment]
One more point to drop: we don't run featuretools in LG currently. We should discuss that.

**Comment by gsheni** [comment]
@jeremyliweishih We have added URL and EmailAddress primitives to Featuretools and released them.
- https://github.com/alteryx/featuretools/releases/tag/v0.26.0

**Comment by jeremyliweishih** [comment]
Initial design spike has been completed [here](https://alteryx.atlassian.net/wiki/spaces/PS/pages/654442499/Feature+engineering+featuretools+and+evalml). Will continue and fully flesh out a design doc moving forward.
