### ISSUE TITLE
Define Behavior for Woodwork's EmailAddress and URL logical types

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2444]
We've identified the `EmailAddress` and `URL` logical types as high priority logical types in #2423 so we're pulling them into their own issue.

Closing Criteria:

- [ ] A proposal for how to handle these types in AutoMLSearch, e.g. detect them and add specific components to handle them, modifying our existing components to handle them
- [ ] Implementation of the proposal

**Comment by dsherry** [comment]
Hey @freddyaboulton , @gsheni mentioned to me that featuretools is planning to add URL and email address primitives. So please sync with the featuretools team before you start in on this.

**Comment by gsheni** [comment]
Here is the MR in progress
- https://github.com/alteryx/featuretools/pull/1508
