### ISSUE TITLE
Fix formatting of objective API reference

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#2447]
This issue tracks fixing the formatting of the objective API reference (examples below). My hypothesis is that using `Arguments` instead of `Parameters` is causing this and is most likely the result of using the pandas theme.

Example of weird formatting:
https://feature-labs-inc-evalml--2433.com.readthedocs.build/en/2433/generated/methods/evalml.objectives.AUC.objective_function.html#evalml.objectives.AUC.objective_function

![Screen Shot 2021-06-25 at 11.27.36 AM.png](https://images.zenhubusercontent.com/5d711d30e994807edd6408da/b17d5c69-5087-4118-aad9-1ea6e3bbed5a)

Example of normal formatting:
https://feature-labs-inc-evalml--2433.com.readthedocs.build/en/2433/generated/methods/evalml.pipelines.components.DropNullColumns.fit.html#evalml.pipelines.components.DropNullColumns.fit

![Screen Shot 2021-06-25 at 11.27.40 AM.png](https://images.zenhubusercontent.com/5d711d30e994807edd6408da/26aaf909-81e4-4a25-9556-0016da2b9309)

**Comment by dsherry** [comment]
@jeremyliweishih great suggestion! I noticed those links appear to be coming from an RTD PR build. Do you have a PR or a branch which should be attached to this issue?
