### ISSUE TITLE
Add support for Unknown Logical Type

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2459]
- The **Unknown** Logical Type has been merged into `main` of Woodwork. 
- It is the default inferred Logical Type, and uses string as the representation.
  - Before NaturalLanguage was the default inferred type. 
- EvalML should be able to handle this Logical Type, and correctly ignore it during AutoML search.

**Comment by freddyaboulton** [comment]
@gsheni I think this is a dup of #2426 !

**Comment by gsheni** [comment]
Dpu
