### ISSUE TITLE
ModuleNotFoundError: No module named 'shap'

### ISSUE THREAD

**Issue by esitharth** [alteryx/evalml#2468]
I get this error when I import evalml in my notebook.

**Comment by freddyaboulton** [comment]
Hi @esitharth thank you for filing an issue! Are you running on windows? I think something must have gone wrong during the shap installation that happens when `pip install evalml` is run.

What happens when you run `pip install shap` and then restart your notebook?

**Comment by esitharth** [comment]
Yes I am running on windows. pip install shap throws an error message as well during setup.py install for shap. Error is ' ERROR Command errored out with exit status 1:

**Comment by freddyaboulton** [comment]
Hi @esitharth, yea shap has poor support for windows. Can you try installing evalml with conda, `conda install -c conda-forge evalml` ?

**Comment by esitharth** [comment]
I tried conda install -c conda-forge evalml.
evalml got installed.
But when I tried
 X_train, X_test, y_train, y_test = evalml.preprocessing.split_data(features, target, problem_type='regression',  test_size=.25)
It throws an error 
TypeError: split_data() got an unexpected keyword argument 'problem_type'

**Comment by esitharth** [comment]
Code is as follows:
import evalml
df = pd.read_csv('TrainingData-PymtDate-Pred.csv')
features = df.drop(['Unique Invoice & Date', 'Transaction Type Description', 'Follow Up Date', 'Service Date' ], axis=1)
target = df['delta']
X_train, X_test, y_train, y_test = evalml.preprocessing.split_data(features, target, problem_type='regression',  test_size=.25)

**Comment by chukarsten** [comment]
@freddyaboulton @dsherry putting this in this sprint.  If no action is required, we can close.

**Comment by bchen1116** [comment]
@freddyaboulton @chukarsten I tried running this on windows with python 3.8.10 and a fresh virtualenv, and I wasn't able to reproduce the `shap` issue that @esitharth ran into. Additionally, I was able to split the data without problem. 
![image](https://user-images.githubusercontent.com/22552445/129977715-890e8a35-3841-4e65-aacd-323308387d6c.png)

**Comment by freddyaboulton** [comment]
Thank you @bchen1116 ! Closing.
