### ISSUE TITLE
Exception during automl search: 'NAType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by esitharth** [alteryx/evalml#2469]
Hi,
When I run the automlSearch for Regression I get this exception for all the pipelines.
What do I do?

Regards,
Sitharth

**Comment by esitharth** [comment]
Hi Can anyone resolve this issue for me. Thanks :)

**Comment by freddyaboulton** [comment]
Hi @esitharth ! Can you please share a code snippet so we can find the root cause? Thank you!

**Comment by esitharth** [comment]
Yes. Find the code Below:

features = df.drop(['Unique Invoice & Date', 'Transaction Type Description', 'Follow Up Date', 'Service Date' ], axis=1)
target = df['delta']
X_train, X_test, y_train, y_test=evalml.preprocessing.split_data(features, target, problem_type='regression',  test_size=.25)
from evalml import AutoMLSearch
automl=AutoMLSearch(X_train=X_train,y_train=y_train,problem_type='regression')
automl.search()

**Comment by esitharth** [comment]
This is the output I get:

*****************************
* Beginning pipeline search *
*****************************

Optimizing for R2. 
Greater score is better.

Using SequentialEngine to train and score pipelines.
Searching up to 1 batches for a total of 9 pipelines. 
Allowed model families: extra_trees, xgboost, lightgbm, decision_tree, random_forest, catboost, linear_model

Evaluating Baseline Pipeline: Mean Baseline Regression Pipeline
Mean Baseline Regression Pipeline:
	Starting cross validation
	Finished cross validation - mean R2: -0.000

*****************************
* Evaluating Batch Number 1 *
*****************************

			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
Linear Regressor w/ Imputer + Text Featurization Component + One Hot Encoder + Standard Scaler:
	Starting cross validation
	Finished cross validation - mean R2: nan
			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
Decision Tree Regressor w/ Imputer + Text Featurization Component + One Hot Encoder:
	Starting cross validation
	Finished cross validation - mean R2: nan
			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
Random Forest Regressor w/ Imputer + Text Featurization Component + One Hot Encoder:
	Starting cross validation
	Finished cross validation - mean R2: nan
			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
LightGBM Regressor w/ Imputer + Text Featurization Component + One Hot Encoder:
	Starting cross validation
	Finished cross validation - mean R2: nan
			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
Elastic Net Regressor w/ Imputer + Text Featurization Component + One Hot Encoder + Standard Scaler:
	Starting cross validation
	Finished cross validation - mean R2: nan
			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
XGBoost Regressor w/ Imputer + Text Featurization Component + One Hot Encoder:
	Starting cross validation
	Finished cross validation - mean R2: nan
			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
Extra Trees Regressor w/ Imputer + Text Featurization Component + One Hot Encoder:
	Starting cross validation
	Finished cross validation - mean R2: nan
			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
CatBoost Regressor w/ Imputer + Text Featurization Component:
	Starting cross validation
	Finished cross validation - mean R2: nan
---------------------------------------------------------------------------
AutoMLSearchException                     Traceback (most recent call last)
~\AppData\Local\Temp\7/ipykernel_14380/3397775500.py in <module>
----> 1 automl.search()

d:\sitharth\pycharmprojects\paymentdateprediction1\venv\lib\site-packages\evalml\automl\automl_search.py in search(self, show_iteration_plot)
    832                 and current_batch_pipeline_scores.isna().all()
    833             ):
--> 834                 raise AutoMLSearchException(
    835                     f"All pipelines in the current AutoML batch produced a score of np.nan on the primary objective {self.objective}."
    836                 )

AutoMLSearchException: All pipelines in the current AutoML batch produced a score of np.nan on the primary objective <evalml.objectives.standard_metrics.R2 object at 0x0000019F1A924520>.

**Comment by leahmcguire** [comment]
I have the same issue with trying to run a regression pipeline, using the default autoML search functionality.

It runs through the whole pipeline producing these errors on every fold. The errors I see are: 

```
INFO:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/automl_search.py:*****************************

INFO:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/automl_search.py:
			Fold 0: Encountered an error.
INFO:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/callbacks.py:			Fold 0: Encountered an error.
			Fold 0: All scores will be replaced with nan.
INFO:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/callbacks.py:			Fold 0: All scores will be replaced with nan.
			Fold 0: Please check the log file for the current hyperparameters and stack trace.
INFO:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/callbacks.py:			Fold 0: Please check the log file for the current hyperparameters and stack trace.
			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
INFO:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/callbacks.py:			Fold 0: Exception during automl search: 'NAType' object has no attribute 'lower'
DEBUG:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/callbacks.py:			Fold 0: Parameters:
	{'Imputer': {'categorical_impute_strategy': 'most_frequent', 'numeric_impute_strategy': 'mean', 'categorical_fill_value': None, 'numeric_fill_value': None}, 'DateTime Featurization Component': {'features_to_extract': ['year', 'month', 'day_of_week', 'hour'], 'encode_as_categories': False, 'date_index': None}, 'One Hot Encoder': {'top_n': 10, 'features_to_encode': None, 'categories': None, 'drop': 'if_binary', 'handle_unknown': 'ignore', 'handle_missing': 'error'}, 'Linear Regressor': {'fit_intercept': True, 'normalize': False, 'n_jobs': -1}}
DEBUG:/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/callbacks.py:			Fold 0: Traceback:
  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/engine/engine_base.py", line 204, in train_and_score_pipeline
    cv_pipeline = train_pipeline(

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/automl/engine/engine_base.py", line 131, in train_pipeline
    cv_pipeline.fit(X, y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/utils/base_meta.py", line 16, in _set_fit
    return_value = method(self, X, y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/regression_pipeline.py", line 26, in fit
    self._fit(X, y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/pipeline_base.py", line 228, in _fit
    self.component_graph.fit(X, y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/component_graph.py", line 198, in fit
    self._compute_features(self.compute_order, X, y, fit=True)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/component_graph.py", line 336, in _compute_features
    output = component_instance.fit_transform(input_x, input_y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/utils/base_meta.py", line 16, in _set_fit
    return_value = method(self, X, y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/components/transformers/transformer.py", line 73, in fit_transform
    return self.fit(X, y).transform(X, y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/components/component_base_meta.py", line 31, in _check_for_fit
    return method(self, X, y)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/components/transformers/preprocessing/text_featurizer.py", line 129, in transform
    X_lsa = self._lsa.transform(X_ww.ww[self._text_columns])

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/components/component_base_meta.py", line 29, in _check_for_fit
    return method(self, X)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/evalml/pipelines/components/transformers/preprocessing/lsa.py", line 59, in transform
    transformed = self._lsa_pipeline.transform(X_ww[col])

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/sklearn/pipeline.py", line 560, in _transform
    Xt = transform.transform(Xt)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1870, in transform
    X = super().transform(raw_documents)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1254, in transform
    _, X = self._count_vocab(raw_documents, fixed_vocab=True)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1114, in _count_vocab
    for feature in analyze(doc):

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 104, in _analyze
    doc = preprocessor(doc)

  File "/Users/lmcguire/.pyenv/versions/3.8.8/envs/mlplayground/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 69, in _preprocess
    doc = doc.lower()

```

**Comment by freddyaboulton** [comment]
@esitharth and @leahmcguire , thank you for letting me know you've had difficulties running search on your datasets.

The errors you are posting make me think that your datasets have missing values in columns that we are inferring as "natural language".

For context, EvalML uses a package called [woodwork](https://woodwork.alteryx.com/en/stable/) to set and infer a data type (called a "logical type" in woodwork) for each column. We do this because different types need different feature engineering steps before we can actually fit a model. For example, natural language columns get fed to our `TextFeaturizer` to convert the text into numeric values. Similarly, categorical columns get fed to our `OneHotEncoder`. 

The issue you are facing is that the EvalML `Imputer` does not impute missing values for natural language columns, and so these missing values are making their way to the `TextFeaturizer` component, which cannot handle NaN values.

I think we can do the following to fix your issue:

### 1. Identify which features are inferred as natural language and have missing values

```python
import woodwork as ww

# X is your feature matrix
X.ww.init()

# This tells you the number of missing values 
na_count = X.ww.describe().loc['nan_count']
columns_with_missing_values = na_count[na_count > 0].index

# This tells you the columns that are natural language
nat_lang_columns = X.ww.select("NaturalLanguage").columns

nat_lang_with_nan = set(nat_lang_columns).intersection(columns_with_missing_values)
```

### 2. Decide what to do with these features
I think you can either drop from your dataset:

```python
X.ww.drop(list(nat_lang_with_nan), inplace=True)
```

or convert to categorical types - these get handled by the `Imputer` so the missing values should not be a problem.

```python
X.ww.set_types({col: "Categorical" for col in nat_lang_with_nan})
```

You can also drop the rows that have missing values for these columns.


I hope this resolves the issue, please keep us updated! 

### P.S: Using DataChecks prior to running search

EvalML has a concept of [DataChecks](https://evalml.alteryx.com/en/stable/user_guide/data_checks.html) to check the health of your data before running `AutoMLSearch`. It's usually a good idea to run the data checks before search.

In your case, it would look like this:

```python
from evalml.data_checks import DefaultDataChecks

DefaultDataChecks(problem_type="regression", objective="R2").validate(X, y)
```

You should see something like this in the output, letting you know that there are natural language columns in your dataset.

```python
{'message': 'Input natural language column(s) (a) contains NaN values. Please impute NaN values or drop these rows or columns.',
   'data_check_name': 'NaturalLanguageNaNDataCheck',
   'level': 'error',
   'code': 'NATURAL_LANGUAGE_HAS_NAN',
```

**Comment by leahmcguire** [comment]
Hi Freddy, thank you for the explanation that is really helpful! If I added a step to fill natural language column nans with empty strings would that be a good contribution to the project? I like your interface a lot better than the other AutoML projects I am evaluating right now :-)

**Comment by freddyaboulton** [comment]
@leahmcguire thanks for the suggestion! We're still debating the best way to handle missing values in natural language (we're tracking that problem here https://github.com/alteryx/evalml/issues/1587) so we don't think it's a good first issue to tackle.

That being said, your feedback made the team realize that we need to update our automl documentation and tutorials to be louder about our data checks and a new function called [search](https://evalml.alteryx.com/en/stable/generated/evalml.automl.search.html#evalml.automl.search) that runs the datachecks before modeling.

One of our team members will be working on doing that in the next two weeks (issue here https://github.com/alteryx/evalml/issues/2500) and we'd love your input on the changes we make. So we'll tag you as a reviewer on the PR!

Thanks for contributing - if you would like to tackle an issue yourself you can filter issues by "good first issue". These two stood out to me

https://github.com/alteryx/evalml/issues/1801
https://github.com/alteryx/evalml/issues/2102
