### ISSUE TITLE
help: How do I replicate the processed version of the data from pipeline of AutoMLSearch.search()?

### ISSUE THREAD

**Issue by naveen-marthala** [alteryx/evalml#2472]
It still is not clear to me that how I can get the version of data that was transformed and passed to the pipeline and pipeline descriptions are very vague as well. 

here's all that I have done:
```
>>> from evalml import AutoMLSearch
>>> automl = AutoMLSearch(X_train=Xy_3.drop(columns='target'), y_train=Xy_3.loc[:,'target'],
                                                 problem_type='regression', objective='root mean squared error', n_jobs=-1)
>>> automl.search()
>>> print(automl.describe_pipeline(automl.rankings.iloc[0]["id"]))

*********************************************************************************
* XGBoost Regressor w/ Imputer + Text Featurization Component + One Hot Encoder *
*********************************************************************************

Problem Type: regression
Model Family: XGBoost

Pipeline Steps
==============
1. Imputer
	 * categorical_impute_strategy : most_frequent
	 * numeric_impute_strategy : median
	 * categorical_fill_value : None
	 * numeric_fill_value : None
2. Text Featurization Component
3. One Hot Encoder
	 * top_n : 10
	 * features_to_encode : None
	 * categories : None
	 * drop : if_binary
	 * handle_unknown : ignore
	 * handle_missing : error
4. XGBoost Regressor
	 * eta : 0.053613563977506225
	 * max_depth : 20
	 * min_child_weight : 6.470576304373694
	 * n_estimators : 688
	 * n_jobs : -1
>>> best_pipeline = automl.best_pipeline
>>> type(best_pipeline)
evalml.pipelines.regression_pipeline.RegressionPipeline
```

There are columns like these below, which I have no idea on how to replicate.
```
 'DIVERSITY_SCORE(original_column_name)', 'LSA(original_column_name)[0]', 'LSA(original_column_name)[1]',, 'POLARITY_SCORE(original_column_name)
```

There is APi available to get all the column names but that is still not helping me with understanding thing like which imputation method was used, how columns were encoded etc,..

If i am missing something here please tell me. Or include API to be able to reproduce the pre-processing.

**Comment by angela97lin** [comment]
Hi @naveen-9697! Thanks for your questions.

RE figuring out which imputation method was used, how columns were encoded: What you're currently looking at is our pipeline description which lists out the different components in the pipelines and their parameters in a readable format. For example, the imputer has `categorical_impute_strategy` set to `most_frequent`, meaning that it uses the most frequent value to impute categorical columns. If you'd like to dive into the parameters specifically, you can also call ``automl.get_pipeline(automl.rankings.iloc[0]["id"]).parameters``. 

This probably isn't ideal, but you can see the input feature names to each component via the `input_feature_names` attribute on a pipeline after its been fit. So in your example:
```
pipeline = automl.get_pipeline(automl.rankings.iloc[0]["id"])
# fit pipeline on your original training data:
pipeline.fit(X_train, y_train)
pipeline.input_feature_names # returns a dictionary mapping component names to columns
```

If you see something like:
```
{'TextFeaturization': [original_column_name],
'XGBoost Regressor': [LSA(original_column_name)[0]}
```
from calling `.input_feature_names`, that means the XGBoost Regressor got the LSA(original_column_name)[0] column as an output of the TextFeaturization component.


I hope this helps! Let us know if you have any other questions :)

**Comment by naveen-9697** [comment]
Thanks @angela97lin.

I do understand that `LSA(original_column_name)` has been passed to XGBoost Regressor, but i would like to know how it has been created. Not just that, how were  `LSA(original_column_name)[0]`, `LSA(original_column_name)[1]`, `POLARITY_SCORE(original_column_name)`, `DIVERSITY_SCORE(original_column_name)` created. 

I would also like to know which columns were one hot encoded?

How are "numeric_impute_strategy" and "numeric_fill_value" different? why was the former set to median while the latter to None. And aren't we filling the gaps(or Nans) in both the cases?

Please tell me if there's any page in the documentation I can refer to understand all that?

**Comment by angela97lin** [comment]
Glad to help, @naveen-9697 !

To understand your first question, those columns were created via our TextFeaturization component which generates features via the nlp-primitives package. You can learn more about that package [here](https://github.com/alteryx/nlp_primitives), but EvalML leverages the LSA, Polarity Score, and Diversity Score primitives from that package to create those columns.

RE your second question: one way to determine that could be to dig further into the OHE. For example, you could use the `categories` attribute (ex: `pipeline.component_graph.component_instances["One Hot Encoder"].categories('Country')`) to get the different categories for the "Country" column that were created, or `pipeline.component_graph.component_instances["One Hot Encoder"]._get_feature_provenance()` to get a mapping of the original column to the columns created (note: this is available only after fitting).

To answer your third question, hopefully this documentation helps: https://evalml.alteryx.com/en/stable/generated/methods/evalml.pipelines.components.Imputer.__init__.html#evalml.pipelines.components.Imputer.__init__

Specifically, "numeric_impute_strategy" determines the strategy to use (ex: most_frequent, mean, median, etc.). As our docs say: 
``
numeric_fill_value (int, float) – When numeric_impute_strategy == “constant”, fill_value is used to replace missing data. The default value of None will fill with 0.
``
We're filling in NaNs in both cases, it's a matter of *how* we're filling them in!

**Comment by naveen-marthala** [comment]
I have dug into the code of `RegressionPipeline`'s `predict()` method and all the methods it calls.

Here's how you can get the same dataframe that will be passed to the model:

```
# this code does the equivalent of sklearn's transform method and for that you need to have a dataframe that was passed as X to AutoMLSearch; and let's call it test
>>> from evalml.utils import infer_feature_types
>>> test_ifted = infer_feature_types(test)
>>>
>>>
# this is a dictionary and the values are all the dataframes that will be passed to each of the step in your pipeline.
>>> outputs_outputs = best_pipeline.component_graph._compute_features(best_pipeline.component_graph.compute_order, test_ifted )
# doing outputs_outputs.keys() will print to stdout, all the keys, it may look like this
>>>
dict_keys(['Imputer.x', 'Imputer.y', 'Text Featurization Component.x', 'Text Featurization Component.y', 'One Hot Encoder.x', 'One Hot Encoder.y', 'XGBoost Regressor'])
# and each of the key will have the dataframe as transformed by that step of the pipeline.
```
So, for example, in my case, doing `outputs_outputs['One Hot Encoder.y']` will return the final dataframe, as it was passed to the  xgboost model of my pipeline.

And about the replication, you would need to check the documentation for the imputation method that was used in your pipeline and replicate the imputation method.

And as @angela97lin mentioned in her previous comment, "nlp-primitives" should help you with replicating or engineering the text based columns.


Huge thanks to @angela97lin for the help and for making eval-ml.

**Comment by angela97lin** [comment]
Glad I could help, @naveen-marthala 😁 

I'll mark this issue as closed now, feel free to open another if you have any other questions or issues!
