### ISSUE TITLE
Remove _put_in_original_order()

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2473]
A function, `_put_in_original_order()` was introduced in [this PR](https://github.com/alteryx/evalml/pull/2465) to preserve the original order of a DataFrame's columns in the corresponding WW TableSchema. A [WW issue ](https://github.com/alteryx/woodwork/issues/1039) was filed to allow us to remove this function by requesting WW retain this order.

Blocked by: https://github.com/alteryx/woodwork/issues/1039

**Comment by freddyaboulton** [comment]
I'm going to assign myself but this is blocked by #2543 !
