### ISSUE TITLE
Add more information about our TextFeaturization component in our docs

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2474]
Fallout of #2472, let's add a little more information on our TextFeaturization and what it does (cleans text, uses featuretools) to our docs: https://evalml.alteryx.com/en/stable/generated/evalml.pipelines.components.TextFeaturizer.html

**Comment by dsherry** [comment]
Agreed! We should at least say what features the component engineers in the API ref, linked above.

It would also be great if the text featurizer tutorial highlighted which features we are building. Perhaps it can show the full list of features passed to the estimator of the best pipeline.
