### ISSUE TITLE
Partial dependence errors with column with string and NaN values

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#2475]
Partial dependence errors when a column contains both string values and `NaN. There seems to be some failure in generating the grid as `np.unique()` cannot run on mixed values.

```python
import pandas as pd
from evalml import AutoMLSearch
from evalml.model_understanding import partial_dependence

df = pd.read_csv('1625078186889-mushroom_subset.csv')
y_train = df['class']
X_train = df.drop('class', axis=1)

aml = AutoMLSearch(X_train, y_train, 'binary')
aml.search()

pipeline = aml.best_pipeline

holdout = pd.read_csv('mushroom_holdout.csv')
partial_dependence(pipeline, holdout, 3)
```

![Screen Shot 2021-07-08 at 11 24 07 AM](https://user-images.githubusercontent.com/15271480/124948803-06d11980-dfdf-11eb-8929-df6295411b0c.png)

Notebook and datasets:
[string_nan_ex.zip](https://github.com/alteryx/evalml/files/6785630/string_nan_ex.zip)

**Comment by freddyaboulton** [comment]
I'm not sure if there's much we can do here until we compute the grid for partial dependence ourselves for categoricals, which is what I think #2502 is tracking or we can wait for sklearn to let us provide the grid ourselves: https://github.com/scikit-learn/scikit-learn/issues/20890

**Comment by freddyaboulton** [comment]
Chatted with @dsherry and the team at OH. We agree that in order to fix this bug we need to be able to compute our own grid for partial dependence values. That is what #2502 is tracking.

FYI @chukarsten since you werent at OH. This might affect the current sprint scope.
