### ISSUE TITLE
Create a new component which selects using feature types

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2479]
We currently have the `SelectColumns` component which allows us to select specific columns based on column names. However, it would be useful to also have a component which filters / selects columns by (Woodwork logical) type. This could help us enable specific subgraphs / pipelines that handle certain data types (ex: select categorical cols --> pass to OHE).

**Comment by dsherry** [comment]
@angela97lin should this be part of the component graph epic? Or is it "not required"?
