### ISSUE TITLE
Revert Pandas 1.3.0 Compatibility Patch

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2485]
Once xgboost releases to > 1.4.2 with [this fix](https://github.com/dmlc/xgboost/pull/7074), the changes made to estimator.py [here](https://github.com/alteryx/evalml/pull/2442) to force dataframe columns to a list of integers can be reverted as xgboost's DMatrix will be able to properly handle RangeIndex rather than just Int64Index.  

estimator.py L72-73
```
# These two lines can be removed.
if isinstance(X.columns, range.RangeIndex):
    X.columns = [x for x in X.columns]

```

**Comment by angela97lin** [comment]
@chukarsten Are we looking for XGBoost to release to >1.4.2? I see that the most recent release is 1.4.2, and I'm working on https://github.com/alteryx/evalml/pull/2484 to unpin our XGBoost version (which would install 1.4.2) so I was curious!
