### ISSUE TITLE
Add a model understanding function for visualizing target variable over time for ts regression

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2509]
The expected output of this feature is something like this:

![image](https://user-images.githubusercontent.com/41651716/125647286-ffd98a9e-33c7-454b-b334-1ca9c9890ee4.png)

**Comment by ParthivNaresh** [comment]
I got halfway through this before I realized it looks a lot like #[1258](https://github.com/alteryx/evalml/issues/1258)

It was fixed by https://github.com/alteryx/evalml/pull/1483. Is there a different implementation to this issue?
