### ISSUE TITLE
Spike - Handle known-in-advance features

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2511]
We have received feedback that we want our time series pipelines to be aware of features that are "known in advance". 

The outcome of this spike is a design document detailing know to do that. I think there are two important pieces

- [ ] What are "known in advance" features?
- [ ] I think we'll want to definitely cover well-known holidays with the ability to add custom holidays. Can we add transformers that compute indicator for `is_holiday`? Or should we be more granular and add `is_july_4th`, `is_christmas` holidays?

**Comment by dsherry** [comment]
Yep, another term I've heard for these features are "key date indicators" or "key event indicators". They can be generated from a list of holidays, a list of key events or both.

**Comment by dsherry** [comment]
@freddyaboulton what's the status of this? Is it safe to assume this is on hold until we complete our time series MVP work? Should it be moved from "In Progress"?
