### ISSUE TITLE
Update `OutlierDataCheck` to use Woodwork's implementation of outlier detection

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2529]
https://github.com/alteryx/woodwork/pull/1048 has been merged, so once Woodwork gets a release out, we should update EvalML to use Woodwork's outlier detection implementation :)

**Comment by gsheni** [comment]
@angela97lin Woodwork v0.5.1 was release with outlier detection
- https://github.com/alteryx/woodwork/releases/tag/v0.5.1
