### ISSUE TITLE
Upgrade to Woodwork 0.5.1

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2543]
WW release 0.5.1 introduced a breaking change regarding inference for columns that are all NaN. Here is a possibly  incomplete list of the breakages:

- Prior to 0.5.0, partial dependence would work on numeric columns with missing values. It would fill the entire column with NaNs but the physical type would still be float so the imputer could handle it. Now the physical type changes to string and the Imputer cannot handle missing values in string physical types. I think this one requires discussion?
- Our data checks action for all null columns are broken cause they also pull in the "Unknown" data check message.
- The imputers can no longer handle all null columns for the same reason as why the partial dependence is broken.

I think someone should go through the tests that fail and propose some changes to our behavior regarding unknown columns!

**Comment by dsherry** [comment]
@chukarsten assigning to you since you set it to "In Progress"

**Comment by chukarsten** [comment]
Working on this : https://alteryx.atlassian.net/wiki/spaces/PS/pages/957415541/EvalML+Woodwork+0.5.1+Upgrade
