### ISSUE TITLE
Our make_pipeline tests don't actually verify the pipeline is correct!

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2553]
I just noticed that `test_make_pipeline_*` doesn't actually assert the pipeline is correct! These tests could fail and we wouldn't know. Let's add the `assert` back in.

https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L149
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L206
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L261
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L309
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L370
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L438
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L492
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L535
https://github.com/alteryx/evalml/blob/main/evalml/tests/pipeline_tests/test_pipeline_utils.py#L591

**Comment by angela97lin** [comment]
Good catch, I'm going to take this on to make sure I didn't break anything in my updates to `make_pipeline` :)
