### ISSUE TITLE
DaskEngine and CFEngine: Make client optional arg

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2561]
Currently, `DaskEngine` and `CFEngine` require a client explicitly provided to run AutoML.  Perhaps, for OS user's convenience, it might be nice to make client an optional argument and instead instantiate a DaskEngine and CFEngine using threaded parallelism using max threads.

Currently:
```
from dask.distributed import Client, LocalCluster
from evalml.automl.engine import DaskEngine

cl = LocalCluster()
client = Client(cl)
e = DaskEngine(client=client)
```

Proposed
```
from evalml.automl.engine import DaskEngine

e = DaskEngine()
```

Currently:
```
from concurrent.futures import ThreadPoolExecutor
from evalml.automl.engine import CFEngine
from evalml.automl.engine.cf_engine import CFClient

p = ThreadPoolExecutor()
client = CFClient(p)
e = CFEngine(client=client)
```

Proposed
```
from evalml.automl.engine import DaskEngine

e = CFEngine()
```

**Comment by chukarsten** [comment]
@freddyaboulton let me know your thoughts on this.  I know we had certain consumer driven reasons for not doing it this way off the bat, but let me know if you think this violates what we had in mind for the Engine.  Was just trying to simplify for the OS user.

**Comment by dsherry** [comment]
Sounds good to me! I like the idea of doing both, exposing input param but also having good defaults. A good way to encode default is to have the arg default to None, and then use that to set the default setting.
