### ISSUE TITLE
Local dev: update lint tools to check/remove notebook cell output

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2566]
As a developer, If I want to add content to our notebook-based documentation, I typically modify the notebooks locally and then push changes up and open a PR. 

The problem is that we don't want to check-in notebooks with cell outputs into our repo because it makes it harder to analyze the diff during PR reviews and it makes the notebooks larger. 

This makes developing the notebooks a pain because I need to hit `Restart Kernel and Clear Outputs` on jupyter and then `Save` before I want to commit a change.

The proposal is for `make lint` to throw an error if any of the jupyter notebook cells in our docs have outputs. This will make it harder for developers to check in notebooks with output. The second part is for `make lint-fix` to automatically clear the outputs from the notebook cells.

For inspiration, look at the `notebook-version-standardizer`: https://github.com/alteryx/evalml/blob/main/docs/notebook_version_standardizer.py

**Comment by gsheni** [comment]
@freddyaboulton Can we use `nbsphinx_execute` option to resolve this?
- https://nbsphinx.readthedocs.io/en/0.8.2/usage.html#nbsphinx_execute

**Comment by freddyaboulton** [comment]
@gsheni I'm not sure! We currently have `nbsphinx_execute` set to `always`. Are you suggesting we change the setting?

I was envisioning we'd write a script to iterate over the notebooks and set the `outputs` field to `[]` on `lint-fix` but there could be other ways of doing it! I think the main requirement is to make it harder for developers to push/check-in notebooks with outputs because it makes reviewing them harder.

**Comment by gsheni** [comment]
@freddyaboulton I thought that setting would help with the documentation building, but this issue is more about cell outputs during code review, so disregard my comment.
