### ISSUE TITLE
Define behavior when user attempts to use .y for a component that does not produce a y output

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2569]
We should define the behavior when user attempts to use .y for a component that does not produce a y output. For example, if the user specifies:
```
ComponentGraph(
            {
                "Imputer": [Imputer, "X", "y"],
                "One Hot Encoder": [OneHotEncoder, "Imputer.x", "Imputer.y"],
                "Random Forest Classifier": [
                    RandomForestClassifier,
                    "One Hot Encoder.x",
                    "One Hot Encoder.y",
                ],
            }
        )
```
using `Imputer.y` when the Imputer does not produce a y output, what should happen? I think we should error out given that the graph is not properly formed. Note that this might not be necessary if we tackle #1945, but this issue tracks ensuring proper behavior, as well as adding the appropriate tests.

**Comment by dsherry** [comment]
> I think we should error out given that the graph is not properly formed
Agreed
