### ISSUE TITLE
Warning from XGBoostClassifier about evaluation metric changing in release 1.3.0

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2570]
Repro

```python
from evalml.demos import load_breast_cancer
from evalml.pipelines import BinaryClassificationPipeline
from evalml import AutoMLSearch
from skopt.space import Categorical

X, y = load_breast_cancer()
automl = AutoMLSearch(X, y, "binary")
automl.search()
```

You should see:

```
WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
```

The goal of this issue is to determine if this has changed the performance of our xgboost classifier and correctly set the parameters so that the warning goes away.

**Comment by dsherry** [comment]
Yep. Next step
* Get a branch up where we set the `binary:logistic` xgboost parameter to "logloss"
* Compare xgboost performance before vs after
* Ideally merge change to update default parameter for xgboost to "logloss". If not, suppress warning
