### ISSUE TITLE
Upgrade to support Woodwork 0.5.1

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2576]
Woodwork was pinned to 0.5.0 after the latest release due to a lot of breakages surrounding the Unknown data type.  We need to perform the proper upgrade to support the new version.

**Comment by thehomebrewnerd** [comment]
@chukarsten FYI, I think WW 0.6.0 will be release this week and will contain some additional potentially breaking changes related to type inference: https://github.com/alteryx/woodwork/blob/main/docs/source/release_notes.rst

Just thought I'd mention in case you want to wait and tackle the 0.5.1 and 0.6.0 fixes at the same time.

**Comment by angela97lin** [comment]
@chukarsten I think this is a dup of https://github.com/alteryx/evalml/issues/2543, where @freddyaboulton left some useful comments if you're looking to tackle this today!

**Comment by chukarsten** [comment]
@thehomebrewnerd thanks for the heads up!  I think we'll still be going incrementally, however!

Closing as it's a dupe.
