### ISSUE TITLE
Prophet: speed up CI

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2588]
With the merge of Prophet in #2242, cmdstanpy will install and compile stan for the automl and "other" test jobs. This can add about 6 minutes to the installation time. 

Is it worth it to separate prophet tests into their own job?

If we only install stan for the tests that need it, the run time of the prophet tests will be 6-8 minutes, which is on par with the run time of the automl tests before the Prophet merge. 

This would mean there would not be a noticeable increase in the time to go through a full CI cycle.

Of course there could be downsides, like increasing the total number of jobs and hitting the limit of number of concurrent github actions.

The desired outcome of this issue is to investigate whether it's worth it to split the Prophet tests into their job and doing the split if so.

**Comment by angela97lin** [comment]
I like this idea a lot! I don't think it'd be too different from the pattern we've already adopted with dask tests, even if the reason for separating out the tests are different here.

**Comment by dsherry** [comment]
Next steps
* Parthiv will look into cmdstan-builder and see if that can speed up our CI overall
* If not, we should look into splitting prophet tests into a separate job to avoid slowing down the other jobs and overall CI time
