### ISSUE TITLE
Withholding ARIMA from AutoML if time unit is not supported by sktime

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2592]
Certain frequencies are not supported in `sktime` due to inconsistency, such as month (28 vs 30 vs 31 days) and year (365 vs 366 days).

This issue tracks two things:

1. Researching which frequencies are allowed in `sktime`
2. Checking the frequency of the time series dataset and if it isn't supported, then disabling ARIMA from running in AutoML.

**Comment by freddyaboulton** [comment]
@ParthivNaresh I wonder if this would still be a problem if we used a relative forecasting frequency?

https://www.sktime.org/en/latest/examples/01_forecasting.html#step-2---specifying-the-forecasting-horizon

**Comment by ParthivNaresh** [comment]
@freddyaboulton We actually currently leverage a ForecastingHorizon for ARIMA. I think the fix that `sktime` put out doesn't address this issue with ForecastingHorizon yet, but I need to dig deeper.

**Comment by freddyaboulton** [comment]
I guess I'm wondering if the error would go away if we used:

```
fh_ = forecasting_.ForecastingHorizon(dates, is_relative=True)
```

rather than

```
fh_ = forecasting_.ForecastingHorizon(dates, is_relative=False)
```

As far as I understand it, a relative forecasting horizon specifies "forecast the next k points in the series". I think that's in line with our requirements.
