### ISSUE TITLE
`sktime`'s AutoARIMA doesn't run seasonal detection by default 

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2611]
This issue tracks setting a "period for seasonal differencing" in ARIMA based on the number of periods in each season that are expected. Due to AutoARIMA's inability to iterate over the period for seasonal differencing parameter, we're limited in our default implementation when tackling seasonal issues, and would therefore be unable to adapt to use cases with AML.

```
from sktime.forecasting.arima import AutoARIMA
from sktime.datasets import load_airline

y = load_airline()
forecaster = AutoARIMA(suppress_warnings=True)
forecaster.fit(y=y[:100])
preds = forecaster.predict(fh=[i+1 for i in range(44)])

preds.plot()
```
![no_sp](https://user-images.githubusercontent.com/29577911/128764222-e772da3d-6b02-4759-9959-99fd016c4abb.png)

```
y = load_airline()
forecaster = AutoARIMA(sp=12, suppress_warnings=True)
forecaster.fit(y=y[:100])
preds = forecaster.predict(fh=[i+1 for i in range(44)])

preds.plot()
```
![yes_sp](https://user-images.githubusercontent.com/29577911/128764368-d99b1aa0-b22e-4de6-b137-192aa12b3916.png)

Based on that granularity of intervals that we decide to separate the data with, this parameter will have to be updated prior to running AutoML.

**Comment by freddyaboulton** [comment]
This could be related to why ARIMA does not perform well on the user guide dataset. This came up in #2697

**Comment by freddyaboulton** [comment]
Closing in favor of #2922
