### ISSUE TITLE
Handle scaling for SVM

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#2615]
**Issue**:
We currently allow a linear kernel as a tunable parameter for SVM classifiers. However, allowing a linear kernel turns the SVM model into a linear model. Linear models require input data with features that are on the same order of magnitude as each other, which is not a requirement for other types of functions (and therefore not a requirement for other SVM kernels).

**Repro**:
Run `fit` with `kernel='linear'` set in an `SVMClassifier` on [this dataset](https://evalml-looking-glass-datasets.s3.amazonaws.com/space_ga_1.csv), the computation will hang and never complete. Note that the `XCOORD` column is on the 10^7 order of magnitude, while all others are in single digits.

**Options**: 
- Remove `"linear"` from the kernel hyperparameter range for our SVM classifier
- Add a `StandardScaler` to any SVM pipelines with `"linear"` as the kernel

Note: the same probably holds for SVM regressors, but I haven't done that experimenting explicitly.

**Comment by freddyaboulton** [comment]
So cool that you found this @eccabay !

My vote is to disallow the linear kernel for SVM since we treat SVM as a different ModelFamily than linear models.

However, would the performance of the "non-linear" SVM kernels improve if we scaled the features prior to fitting? 

If so, we may want to consider adding a standard scaler to SVM models anyway?

**Comment by eccabay** [comment]
Very good point @freddyaboulton! I can explore that as part of my current performance tests for adding SVM to AutoML.

**Comment by eccabay** [comment]
Performance tests (found [here](https://alteryx.atlassian.net/wiki/spaces/PS/pages/981991444/Adding+SVM+to+AutoML)) show that adding a standard scaler to SVM models did not help with the significant fit time increase incurred by the estimator, even when the kernel was set to "linear". From that, I think it makes the most sense to simply remove linear as a hyperparameter option altogether.
