### ISSUE TITLE
Nightlies failing on ModelUnderstanding

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2635]
The nightlies [failed](https://github.com/alteryx/evalml/runs/3332341681#step:8:83) over the weekend on model-understanding.

The issue seems to be related to `numpy`, which had a release over the weekend along with `Pandas`, `plotly`, and `seaborn`. It started Friday night, after `Dask` had its release.

```
plot_data = fig.to_dict()["data"][0]
        assert plot_data["type"] == "bar"
>       assert plot_data["x"] == ["0", "1", "2"]
E       ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by dsherry** [comment]
Thanks for filing. I think first step is to merge [this deps update PR](https://github.com/alteryx/evalml/pull/2630) as soon as @chukarsten finishes with the v0.30.2 release
