### ISSUE TITLE
Spike: Determine which frequencies are not supported by ARIMA/Sktime/Prophet

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2646]
In #2632, we had to prevent AutoMLSearch from running ARIMA if the inferred frequency was "month- start". 

The problem is because "month-start" is not a uniform time length because months have different number of days. There are other non-uniform frequencies supported by pandas, e.g. semi-month-start frequency, so we should figure out what frequencies will cause problems for ARIMA.

The outcome of this issue is a document detailing which frequencies are not supported by ARIMA, prophet, and other time series estimators as well as a design for how to handle that in EvalMl, e.g. with a data check.

Resource on time frequency aliases supported by pandas, https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases

**Comment by ParthivNaresh** [comment]
@freddyaboulton Should this be added to the DatetimeFormatDataCheck?

**Comment by tyler3991** [comment]
Can you include a spreadsheet that shows what "frequencies" each model supports?

**Comment by ParthivNaresh** [comment]
My research can be found [here](https://alteryx.atlassian.net/wiki/spaces/PS/pages/1011777698/Comparing+Offsets+Across+TimeSeries+Estimators).
