### ISSUE TITLE
AutoMLSearch raises AttributeError when TargetDistributionDataCheck issues UserWarning and only one estimator family is allowed

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2652]
Repro

```python
import pandas as pd
from evalml.automl import AutoMLSearch
import woodwork as ww
from evalml.preprocessing import split_data
import pytest

X = pd.read_csv("/Users/freddy.boulton/sources/tempo2-server/testData/stones_encoded.csv")
y = X.pop("total_sales_price")
X_train, X_test, y_train, y_test = split_data(X, y, "regression")

with pytest.raises(AttributeError, match="'UserWarning' object has no attribute 'components'"):
    automl = AutoMLSearch(X_train, y_train, "regression", allowed_model_families=["xgboost"],
                      max_batches=3)
```

The problem is that the `TargetDistributionDataCheck` (called during make_pipeline) is issuing a UserWarning about the p-value. This then gets caught by our [warnings filter](https://github.com/alteryx/evalml/blob/main/evalml/automl/automl_search.py#L543) and then `_catch_warnings` tries to access the `components` attribute of the warning (which doesn't exist because it's not a ParameterNotUsedWarning). 

We need to improve `_catch_warnings` to only look at `ParameterNotUsedWarnings`.

**Comment by tyler3991** [comment]
We should suppress the warning and file an additional issue to make sure the target distribution data check holds up for large data sets.

**Comment by dsherry** [comment]
Filed #2652 to track
