### ISSUE TITLE
Fix the CF Engine (ProcessPoolExecutor) flake

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2669]
Completing this issue involves determining, with some degree of certainty, the root cause behind the flaky CFEngine test that uses the ProcessPoolExecutor.  [This PR](https://github.com/alteryx/evalml/pull/2666) took out the specific changes that utilized process level parallelism with respect to the `test_cancel_job()` test.  We're not sure why it failed, only that process level parallelism, either using `concurrent.futures` or dask are similarly flaky.

**Comment by dsherry** [comment]
Could be a CI flake, could be an actual bug, unclear.

First step: try to change/improve the `test_cancel_job` test.
