### ISSUE TITLE
Uncap Numba version

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2671]
In #2668 , we capped the Numba version to prevent needing to cap the numpy version to < 1.21.  We will want to revisit this and unrestrict Numba from 0.53 when [this numba PR](https://github.com/numba/numba/issues/7176) gets released and Numba supports numpy >= 1.21.

**Comment by freddyaboulton** [comment]
I'm going to move this to the latest available sprint (Nov 9) since numba still has not released a version that's compatible with numpy 1.21

**Comment by dsherry** [comment]
The numba support has been merged! Now waiting for them to do a new release. Their cadence is relatively infrequent so it may be a couple months.

**Comment by chukarsten** [comment]
It looks like a numba 0.55rc2 is [coming soon](https://github.com/numba/numba/releases/tag/0.55.0rc1) with a 0.56dev tag also in existence.  We might consider evaluating an upgrade to this version.

**Comment by dsherry** [comment]
numba [0.55.0](https://github.com/numba/numba/releases/tag/0.55.0) has been released. This issue is now unblocked I believe!
