### ISSUE TITLE
Support training-only components in ComponentGraph

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2681]
Right now, we support samplers as training-only components by checking if the component is a sampler component and not taking any action if so: https://github.com/alteryx/evalml/blob/4afe6dde123c59386d792f17c07664f1c836bcfd/evalml/pipelines/component_graph.py#L323

Once we add other components that are train-only (ex: drop rows), we should verify our behavior holds for other components by updating this line to be more general.

**Comment by dsherry** [comment]
One idea: tagging. All training-only components get static attribute `TRAINING_ONLY`, and we update this elif to check that static tag.
