### ISSUE TITLE
Support time series in new automl algo

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#2691]
The new automl algo has specific batches where ensembling is run but our implementation of _make_stacked_ensemble_pipeline() does not support time series as a problem type. This issue tracks either:

- support time series problems in _make_stacked_ensemble_pipeline()
or
- disabling ensembling for time series problems

**Comment by chukarsten** [comment]
Per our discussion, I ran into this lack of support in the resolution of #3124 .  The PR creates integration tests in `integration_tests/test_nullable_types.py` and uses some datasets that have dates in them, prompting `AutoMLSearch()` to create time series pipelines.  The `DefaultAlgorithm` was unable to pass through the time series parameters into the generated pipelines.

#3124 makes a basic fix to allow the first 3 batches of `DefaultAlgorithm` to generate the proper pre-processing pipelines for time series, but we should add to the acceptance criteria of this issue the increasing of the number of batches  in the `test_nullable_types` integration test to the maximum to ensure all the proper time series pipelines are created with the transformer.

Additionally, this suggests we need more testing around time series/ensembling.  We can actually write these tests and use `pytest.xfail` since we know that this support doesn't exist yet.

```
../../automl/automl_algorithm/default_algorithm.py:322: in next_batch
    next_batch = self._create_fast_final()
../../automl/automl_algorithm/default_algorithm.py:260: in _create_fast_final
    pipelines = [
../../automl/automl_algorithm/default_algorithm.py:261: in <listcomp>
    self._make_split_pipeline(
../../automl/automl_algorithm/default_algorithm.py:432: in _make_split_pipeline
    numeric_pipeline = make_pipeline(
../../pipelines/utils.py:355: in make_pipeline
    return base_class(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[AttributeError("'TimeSeriesMulticlassClassificationPipeline' object has no attribute 'component_graph'") raised in repr()] TimeSeriesMulticlassClassificationPipeline object at 0x1515dd160>
component_graph = {'DateTime Featurization Component': [<class 'evalml.pipelines.components.transformers.preprocessing.datetime_featuriz...pelines.components.transformers.imputers.imputer.Imputer'>, 'Drop Null Columns Transformer.x', 'Label Encoder.y'], ...}
parameters = {'Select Columns Transformer': {'columns': None}}
custom_name = None, random_seed = 0

    def __init__(
        self,
        component_graph,
        parameters=None,
        custom_name=None,
        random_seed=0,
    ):
        if not parameters or "pipeline" not in parameters:
>           raise ValueError(
                "date_index, gap, and max_delay parameters cannot be omitted from the parameters dict. "
                "Please specify them as a dictionary with the key 'pipeline'."
            )
E           ValueError: date_index, gap, and max_delay parameters cannot be omitted from the parameters dict. Please specify them as a dictionary with the key 'pipeline'.

../../pipelines/time_series_pipeline_base.py:35: ValueError
```

**Comment by jeremyliweishih** [comment]
On merge of #3149, this issue should also look into adding support for known in advance features in time series.

**Comment by jeremyliweishih** [comment]
> Per our discussion, I ran into this lack of support in the resolution of #3124 . The PR creates integration tests in `integration_tests/test_nullable_types.py` and uses some datasets that have dates in them, prompting `AutoMLSearch()` to create time series pipelines. The `DefaultAlgorithm` was unable to pass through the time series parameters into the generated pipelines.
> 
> #3124 makes a basic fix to allow the first 3 batches of `DefaultAlgorithm` to generate the proper pre-processing pipelines for time series, but we should add to the acceptance criteria of this issue the increasing of the number of batches in the `test_nullable_types` integration test to the maximum to ensure all the proper time series pipelines are created with the transformer.
> 
> Additionally, this suggests we need more testing around time series/ensembling. We can actually write these tests and use `pytest.xfail` since we know that this support doesn't exist yet.
> 
> ```
> ../../automl/automl_algorithm/default_algorithm.py:322: in next_batch
>     next_batch = self._create_fast_final()
> ../../automl/automl_algorithm/default_algorithm.py:260: in _create_fast_final
>     pipelines = [
> ../../automl/automl_algorithm/default_algorithm.py:261: in <listcomp>
>     self._make_split_pipeline(
> ../../automl/automl_algorithm/default_algorithm.py:432: in _make_split_pipeline
>     numeric_pipeline = make_pipeline(
> ../../pipelines/utils.py:355: in make_pipeline
>     return base_class(
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <[AttributeError("'TimeSeriesMulticlassClassificationPipeline' object has no attribute 'component_graph'") raised in repr()] TimeSeriesMulticlassClassificationPipeline object at 0x1515dd160>
> component_graph = {'DateTime Featurization Component': [<class 'evalml.pipelines.components.transformers.preprocessing.datetime_featuriz...pelines.components.transformers.imputers.imputer.Imputer'>, 'Drop Null Columns Transformer.x', 'Label Encoder.y'], ...}
> parameters = {'Select Columns Transformer': {'columns': None}}
> custom_name = None, random_seed = 0
> 
>     def __init__(
>         self,
>         component_graph,
>         parameters=None,
>         custom_name=None,
>         random_seed=0,
>     ):
>         if not parameters or "pipeline" not in parameters:
> >           raise ValueError(
>                 "date_index, gap, and max_delay parameters cannot be omitted from the parameters dict. "
>                 "Please specify them as a dictionary with the key 'pipeline'."
>             )
> E           ValueError: date_index, gap, and max_delay parameters cannot be omitted from the parameters dict. Please specify them as a dictionary with the key 'pipeline'.
> 
> ../../pipelines/time_series_pipeline_base.py:35: ValueError
> ```

This will be done in #3191 as #3177 will not add ensembling support for time series.
