### ISSUE TITLE
Failing Windows Unit Tests - Unable to install certain dependencies

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2708]
All of the nightlies [failed](https://github.com/alteryx/evalml/runs/3460517506?check_suite_focus=true) for Windows when they were unable to import `sklearn`. This issue seems to be occurring [across](https://github.com/alteryx/evalml/actions/runs/1181932280) the CI for Windows unit tests.

After adding `python -m pip install scikit-learn` in `Install EvalML with test requirements` within the `windows_uit_tests`, the `ModuleNotFoundError ` error was pushed to `woodwork`, and then to `texttable`. All of these modules seem to be missing from `pip freeze` in the CI despite being collected:
```
Collecting scikit-learn>=0.24.0
  Downloading scikit_learn-0.24.2-cp37-cp37m-win_amd64.whl (6.8 MB)
Collecting scikit-optimize>=0.8.1
  Downloading scikit_optimize-0.8.1-py2.py3-none-any.whl (101 kB)
```

**Comment by freddyaboulton** [comment]
My guess is that numba 0.54 got pushed to conda yesterday so the numba version conflicts with the one in our core-requirements.txt

https://anaconda.org/conda-forge/numba/files

Will try that out in our Dependencies Bot PR that is also failing for the same error: https://github.com/alteryx/evalml/pull/2707/checks?check_run_id=3457347653
