### ISSUE TITLE
Support woodwork's nullable types

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2745]
When we first did the woodwork integration, we expected users to convert their nullable types to non-nullable types prior to running any code in EvalML. That made sense because we didn't expect these types to be very common.

However, featuretools 1.0.0 will start returning feature matrices with woodwork nullable types. Even without that change, I think it's fair to re-evaluate our previous design decisions.

It's worth pointing out that because our dependencies (sklearn and co.) don't support nullable types, EvalML will likely not support nullable types in all use cases. For example, I don't think we can support the case of a user passing a data with `IntegerNullable` to an estimator outside of a pipeline/AutoMLSearch.

**Comment by dsherry** [comment]
@gsheni when is featuretools 1.0.0 going to come out? Is there a pre-release candidate we can start testing against?

**Comment by gsheni** [comment]
@dsherry @chukarsten @freddyaboulton If you go to https://featuretools.alteryx.com/en/latest/, you will see a banner that provides you with a guide on how to upgrade as well as how to install the upcoming release:
```
pip install https://github.com/alteryx/featuretools/archive/woodwork-integration.zip
```
We are close to getting a release candidate out on PyPI soon.

**Comment by gsheni** [comment]
One aspect of this is support integer with null (**Int64**) and integers without null (_int64_). 
- If a user passes a column with **Int64**, EvalML should have a component to convert the column to float64 (Double Logical Type). 
- If a user passes a column with _int64_, EvalML should not convert this column (keep at Integer Logical Type)

**Comment by freddyaboulton** [comment]
Great point @gsheni . The other conversion that component should do is `BooleanNullable` to `Categorical`.
