### ISSUE TITLE
Find a more consistent way to detect lognormal distributions for larger datasets

### ISSUE THREAD

**Issue by ParthivNaresh** [alteryx/evalml#2749]
Our current implementation for identifying lognormal distributions relies on the Shapiro test. This was decided after comparing the Shapiro test with the Kolomogorov-Smirnov 1 sample and 2 sample tests, and based on consistency and flexibility, the Shapiro test was chosen.

For larger datasets (5000< observations) the test starts to break down, especially for distributions that are significantly skewed. This issue tracks finding a more consistent way to identify a lognormal distribution.

**Comment by chukarsten** [comment]
Acceptance criteria: For the fifteen or so potentially log-normal datasets to be detected, look for the probability of log-normalness to increase with the implementation of our new detection tests.
