### ISSUE TITLE
Support Featuretools 1.0.0

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2816]
- Featuretools 1.0.0 is just around the corner (~2 weeks). The release candidate is out on PyPI and conda
It can be installed via:
```bash
pip install featuretools==1.0.0rc1
``` 
- Related Issue: https://github.com/alteryx/evalml/issues/2745

### Release Notes
- https://featuretools.alteryx.com/en/latest/release_notes.html#v1-0-0rc1-sep-17-2021

### Transition Guide
- https://featuretools.alteryx.com/en/latest/resources/transition_to_ft_v1.0.html

**Comment by dsherry** [comment]
Note that while its possible to start working on this using the 1.0.0 release candidate, the simplest thing to do is to wait for the featuretools 1.0.0 release to go out.

**Comment by dsherry** [comment]
Goal is to complete this this week before @chukarsten goes on vacation!

**Comment by freddyaboulton** [comment]
Nice @chukarsten ! I feel like this will inevitable touch this issue as well https://github.com/alteryx/evalml/issues/2745 .

FYI there's a discussion there between myself and @gsheni about how we can use a component to convert from nullable to non-nullable types. Hopefully that's useful for this issue.
