### ISSUE TITLE
Speed up ensembler component fit time

### ISSUE THREAD

**Issue by christopherbunn** [alteryx/evalml#2835]
This issue tracks finding ways to speed up the time it takes to do the following operations
1. Train an ensembler pipeline during automl
2. Generate predictions from an ensembler pipeline

I think we should focus on the first point first, since it probably has higher time impact. An outcome of this spike could be to file speeding up ensembler predict-time as future work.

Our ideas so far for how to achieve faster ensembler fit-time during automl search:
* Add caching of fitted components to our component graph. This is tracked by #2348 
    * If the input pipelines each use a particular component with the same parameters, fit-caching would mean that component is only fit once with those parameters across the entire ensemble pipeline training step (per training dataset of course).
    * If we implement and calibrate this well, this actually gets us another benefit which is even better: ensembler training during automl would only need to fit the metalearner! This is because the fitted estimators sitting at the end of each input pipeline would all be cached, and could be loaded to generate predictions during TV or CV split 😎 
    * One implication (or future feature request) for #2348 : when ensembling is enabled in automl, that should increment the priority of keeping the pipeline estimators in the fit-cache. Depending on the base caching strategy we choose, this could help us avoid completely missing the benefit of caching! Lots of tricky questions to unpack here, in #2348 :)
* Add caching of component predictions to our component graph. Currently untracked.
    * Similarly to the above, if we implement and calibrate this well, as we train and score the components from each input pipeline on each CV or TV fold, the predictions will be saved in the cache and we'll only have to generate predictions from the metalearner itself!

These optimizations will become important once we update the automl algo to run ensembling more frequently as part of our "long" mode.

**Comment by dsherry** [comment]
Updated description. Related issues: #1897 #1739

Possible dup of #1688

**Comment by dsherry** [comment]
Note one compelling solution to this is to explore caching of fitted pipelines (#2348) and of predictions (unfiled) during automl training

**Comment by gsheni** [comment]
test
