### ISSUE TITLE
AttributeError: Woodwork has no attribute 'select'

### ISSUE THREAD

**Issue by ahmadalsharef994** [alteryx/evalml#2839]
Hello,

While using evalml with time series regression problem, I get an error in AutoMLSearch.
`
automl = AutoMLSearch(X_train, y_train, problem_type="time series regression",
                      max_batches=1,
                      problem_configuration={"gap": 0, "max_delay": 7,
                                             "forecast_horizon": 7, "date_index": None},
                      allowed_model_families=["xgboost", "random_forest", "linear_model", "extra_trees",
                                              "decision_tree"]
                      )
`
My data was splited with eval.ml.preprocessing.split_data as:
`X_train, X_test, y_train, y_test = preprocessing.split_data(X, y, problem_type='time series regression',test_size=.3)`

I am following exactly the documentation but with new data and I am getting this error.

> _AttributeError                            Traceback (most recent call last)
> 
> <ipython-input-11-eb7c27d468d6> in <module>()
>       6                                              "forecast_horizon": 7, "date_index": None},
>       7                       allowed_model_families=["xgboost", "random_forest", "linear_model", "extra_trees",
> ----> 8                                               "decision_tree"]
>       9                       )
>      10 automl.search()
> 
> 2 frames
> 
> /usr/local/lib/python3.7/dist-packages/woodwork/column_accessor.py in __getattr__(self, attr)
>     224             return self._make_series_call(attr)
>     225         else:
> --> 226             raise AttributeError(f"Woodwork has no attribute '{attr}'")
>     227 
>     228     @_check_column_schema
> 
> AttributeError: Woodwork has no attribute 'select'_

Could you please help me???

**Comment by ahmadalsharef994** [comment]
Update 1:
                **Converted** the **dataframe** into **data-series**. **Same issue.**

**Comment by freddyaboulton** [comment]
@ahmadalsharef994 Sorry you're having difficulties! Thanks for filing the issue.

What versions of EvalML and Woodwork do you have? Did you install via conda or pip?

Also, is this the code you ran?

```python
X_train, X_test, y_train, y_test = preprocessing.split_data(X, y, problem_type='time series regression',test_size=.3)
automl = AutoMLSearch(X_train, y_train, problem_type="time series regression", max_batches=1, problem_configuration={"gap": 0, "max_delay": 7, "forecast_horizon": 7, "date_index": None}, allowed_model_families=["xgboost", "random_forest", "linear_model", "extra_trees", "decision_tree"]
automl.search()
```

If so, where does the error come from? Is it from the definition of `automl` or when you called `automl.search`?

**Comment by ahmadalsharef994** [comment]
@freddyaboulton  Thank you for your reply.
The version of evalml is **0.33.0** and I installed it via**pip**.
The problem happened in the creation of `automl`.

It was solved by:
- changing the **input data type**s from data-frames to a **data-frame (X_train which is the date)** 
- and a **pandas.series (y_train which is the value to be predicted)**
as in the documentation example.

It worked after that.

However, I am facing a new problem in `automl.search` this time saying
>   raise ValueError("y_predicted contains NaN or infinity")
Although that my data doesn't have null values or infinity values.

Thanks for help.

**Comment by ahmadalsharef994** [comment]
@freddyaboulton 
Again, I am facing a new error when importing evalml version 0.33.0 saying:
> ImportError: cannot import name 'MaskedArray' from 'sklearn.utils.fixes' (/usr/local/lib/python3.7/dist-packages/sklearn/utils/fixes.py)

Although tat it was fixed in an earlier  version.

Thank you for your help.

**Comment by freddyaboulton** [comment]
Hi @ahmadalsharef994. Yes, I think that error is because of the new scikit-learn version 1.0. It introduced a lot of breaking changes. Related Issue here: https://github.com/alteryx/evalml/issues/2843

Can you please install sklearn 0.24.2 and trying again?
