### ISSUE TITLE
What X_train and y_train should be in search_iterative ('time series regression')

### ISSUE THREAD

**Issue by ahmadalsharef994** [alteryx/evalml#2845]
Hello,

I tried too different datasets and APIs and while checking the data using `search_iterative`.
I either get DATETIME_HAS_UNEVEN_INTERVALS or  DATETIME_INFORMATION_NOT_FOUND.

**Comment by freddyaboulton** [comment]
@ahmadalsharef994 Thanks for filing an issue. Time series data needs to meet certain criteria in order for `AutoMLSearch` to work correctly: 

1. Dates need to be evenly spaced by a uniform time interval. For example, all rows should be separated by a day, or 7 days.
2. Dates need to be sorted in ascending order.

When you run `search_iterative`, we perform some automated checks to make sure your data meets these criteria. The errors you are getting are coming from [DateTimeFormatDataCheck](https://evalml.alteryx.com/en/stable/autoapi/evalml/data_checks/index.html#evalml.data_checks.DateTimeFormatDataCheck). 

It raises `DATETIME_HAS_UNEVEN_INTERVALS`, when your data violates criteria 1. `DATETIME_INFORMATION_NOT_FOUND` is raised when we can't infer the frequency of your dates, as determined by `pd.infer_freq`. 

To fix `DATETIME_HAS_UNEVEN_INTERVALS`, make sure your data is evenly spaced. 

To fix `DATETIME_INFORMATION_NOT_FOUND`, make sure the index of `X_train` or the `date_index` column specified in `problem_configuration` contains valid dates as determined by [pd.infer_freq](https://pandas.pydata.org/docs/reference/api/pandas.infer_freq.html)
