### ISSUE TITLE
Log transform regression target: update automl to try both ways when applicable

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2866]
Had convo with @bchen1116 and @chukarsten today about #2749, which tracks trying to improve the mathematical method we use in the log normal data check to recommend to users (and to automl) when to enable/disable log transformation for regression targets.

That work will continue, but filing a separate idea for improvement here:
If the data check recommends we apply log transform, perhaps automl should still try pipelines with both transformed and un-transformed targets, place all of those on the rankings leaderboard and let users select between them.

There's probably more complex heuristics we can try too now that we're moving towards @jeremyliweishih 's work on "DefaultAlgorithm": before scanning estimators, as part of the preprocessing/selection/eng discovery step, pick a pipeline to try both with and without log transform, and use the outcome of that experiment to decide whether automl should continue applying log transform for other pipelines or should just stop exploring that option.

**Comment by freddyaboulton** [comment]
Is this actually blocked by the automl algorithm upgrade? What if we add a hyperparameter to the LogTransform component called `do_transform` whose space is `skopt.categorical(['yes', 'no'])`. 

If `no` the AutoMLAlgorithm does not do the transform and if `yes` it does it. 

The benefit of this approach is that it's not tied to a particular automl algorithm implementation and we delegate the decision of whether or not to do the transform to the tuner/optimizer as opposed to the `DefaultAlgorithm`.

**Comment by freddyaboulton** [comment]
Bumping my comment above. I don't think this is blocked by the automl algorithm upgrade and I don't think we need to manually add heuristics to determine whether or not the log transformer is worth exploring. If we expose wether or not the log transformer is run as a tunable hyperparameter,  the algo should make that decision for us? 

@dsherry @bchen1116

**Comment by angela97lin** [comment]
Just wanted to document some thoughts and notes from our discussion during OH:

I love this idea a lot! I think this is a pretty nifty solution that would allow us to take advantage of the underlying optimizing algorithm without duplication of pipelines and without waiting for any additional algorithm changes. My main concern is that it might be difficult from a UX perspective to see a log transformer / detrender in the pipeline and understand that because `do_transform` is False, we don't actually do any transformations.

I also wonder if giving control to the optimizer means that it'll be difficult to bake in heuristics or our own decision-making about whether or not we want to add a specific component. @dsherry suggested that in a long, more extensive search, adding this hyperparameter might be harder to converge on an optimal solution.

**Comment by freddyaboulton** [comment]
@angela97lin Thanks for documenting the key points of our office hours discussion!

My plan is to write a design document that details/fleshes the proposals we talked about at OH:

1. The `do_transform` approach above.
2. Add pipelines with and without the component to the first batch of AutoMLSearch.
3. Add heuristics to our algorithm to pick out whether or not to add the component.

I'm planning to eventually meet with @dsherry to talk about what he has in mind for 3. I'll be happy to add you to that meeting if you'd like. My concern with 3 is that defining heuristics for whether or not to add these components is what prompted this issue in the first place! 

My hope is that these approaches are not mutually exclusive. Maybe our UX ambitions for "fast" and "long" mode are compatible with 1. It's just a matter of which one we prioritize for "fast mode" (maybe by setting the default value of `do_transform`).

**Comment by freddyaboulton** [comment]
Another use case I just thought that is related to this issue:  the encoding strategy to use. 

We have one hot encoding by default but target encoding may work better for some problems. I think we should eventually try both in AutoMLSearch and that will require making the same decision as LogTransformer/Detrender/etc.
