### ISSUE TITLE
Doctests do not run on CI

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2935]
Currently, our doctests do not run on our Github CI! This is because the `--doctest-modules` flag is only set on `git-test-parallel` and `git-test-minimal-deps-parallel` commands. Since these commands run pytest on test directories, the doctests in our python modules (that is, not under the test directory) are never run!

**Comment by freddyaboulton** [comment]
@angela97lin Wasn't this fixed by #2933 ? Maybe we can close this out?
