### ISSUE TITLE
Remove `EnsembleMissingPipelinesError` exception

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2954]
The `EnsembleMissingPipelinesError` exception was introduced for our scikit-learn based ensembler components which required input pipelines as a valid input. Brief scan showed that this isn't used except in our tests?

This issue tracks determining whether or not we can entirely delete the `EnsembleMissingPipelinesError` exception.

**Comment by dsherry** [comment]
SGTM! Let's use our deprecation pattern.
