### ISSUE TITLE
Which features should we pass to ARIMA? 

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2960]
Currently, if the time series problem is multivariate, ARIMA will receive an exact copy of the input data to to fit on.

Reproducer,

```python
from evalml.automl import AutoMLSearch
from unittest.mock import patch
from evalml.demos import load_weather
import pandas as pd

ARIMA_PATH = "sktime.forecasting.arima.AutoARIMA"

SIZE_OF_FIRST_SPLIT = 914

X, y = load_weather()
X.ww["other_feature"] = y - 1

automl = AutoMLSearch(X, y, "time series regression", verbose=True,
                      problem_configuration={"date_index": "Date",
                                             "forecast_horizon": 1,
                                             "gap": 0,
                                             "max_delay": 10})

with patch(f"{ARIMA_PATH}.fit") as mock_fit, \
    patch(f"{ARIMA_PATH}.predict", side_effect=lambda fh, X: pd.Series(range(X.shape[0]))):
    automl.search()

expected_answer = X.ww.copy()
expected_answer = X.ww.iloc[:SIZE_OF_FIRST_SPLIT, :]
expected_answer.index = pd.DatetimeIndex(expected_answer['Date'], "D")
expected_answer = expected_answer.ww.drop(["Date"])

pd.testing.assert_frame_equal(mock_fit.call_args_list[0].kwargs['X'], expected_answer)
```

I think this is problematic because the `other_feature` in this case may not be known in advanced and this could be a case of data leakage - training a model on data that would not be available at predict time.

The other pipelines receive the input features after feature-engineering, namely lagging and soon-to-be rolling windows, so the `other_feature` would not be given as-is to the pipeline. For that reason, the other pipelines do not suffer from the same problem as ARIMA.

We need to decide:

- Should we even pass features to ARIMA? Why not just pass in the target values
- If we want to pass in some features, we need to make sure there is no leakage.

Step 1 of this issue is reaching consensus on the above decision, then we can decide how to best implement that.

**Comment by ParthivNaresh** [comment]
This was fixed in #3313
