### ISSUE TITLE
Stacked Ensemble Prediction Explanations: Input Pipeline Explanations

### ISSUE THREAD

**Issue by christopherbunn** [alteryx/evalml#2964]
This issue tracks adding in prediction explanations for stacked ensemblers. This iteration will focus on generating explanations for individual input pipelines. This will require adding in a new `estimator` parameter and adding in a function to get a sub-pipeline given a single estimator. 

Related doc [here](https://alteryx.atlassian.net/l/c/u93vxXN5)

**Comment by dsherry** [comment]
Discussed with @christopherbunn . Every pipeline used inside the stacked ensembler pipeline will already have its own set of model understanding results which you can access by grabbing each of those pipelines from the leaderboard. Closing!

**Comment by angela97lin** [comment]
@dsherry @christopherbunn  Is there a good way for us to grab the ids of the input pipelines that were used to create the ensemble? I feel like the answer is yes, but it's not the most intuitive.

Also, what about ensembles that are not created from AutoML search? Should the user just run the model understanding results on the input pipelines?
