### ISSUE TITLE
Time Series Problems with Categoricals Score Nan

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2967]
Currently, if you pass a time series dataset with a categorical feature to AutoMLSearch, many of the models will score `nan`.

Repro
```python
from evalml.automl import AutoMLSearch
from evalml.demos import load_weather
import pandas as pd

X, y = load_weather()
X.ww["categorical_feature"] = pd.Series(["a", "b", "c"]).sample(X.shape[0], replace=True).reset_index(drop=True)

automl = AutoMLSearch(X, y, "time series regression",
                      problem_configuration={"max_delay": 5, "gap": 3, "forecast_horizon": 2,
                                             "date_index": "Date"},
                     verbose=True)
automl.search()

assert automl.rankings.mean_cv_score.isna().any()
```

This is because we currently place the `OneHotEncoder` after the `DelayedFeatureTransformer` and since the `DelayedFeatureTransformer` creates NaN in some features, the `OneHotEncoder` errors out because it cannot handle NaN.

However, I don't think simple `OneHotEncoding` prior to `DelayedFeatureTransformer` should close this issue.

I think what we should do is do is compute some or all following features:
1. Most common category seen in the past window of observations
2. How often each category comes up in the past window of observations.
3. Most common category in the previous k days

etc.

**Comment by dsherry** [comment]
@freddyaboulton I agree with your assessment on what we should do! I like the idea of supporting windowed features for categoricals.

I do wonder what belongs in scope for our time series beta.

Shouldn't we also make it so that we can compute lagged features of categorical features? Should we update our OHE to be tolerant to nans / pass them on in the created features?

Let's chat about this sometime soon.

**Comment by freddyaboulton** [comment]
Yea @dsherry I also wonder what's in scope for the beta. It's not just categoricals we have to worry about. For URL/email/any-non-numeric feature we have to ask ourselves how we should compute "time series aware" features. 

The thing that I'm struggling with is that I don't know how frequent categoricals/URL/email/secondary date features are in time series problems.

In the document @ParthivNaresh showed yesterday at sprint review all the features are numeric. My hunch is that most categorical/URL/email/secondary date features that come up in time series will be known-in-advanced. Do you agree? If so, maybe this kind of issue is low priority.

**Comment by dsherry** [comment]
@freddyaboulton ah yep that's an interesting observation. Let's treat it as a high-priority item for after MVP status

**Comment by freddyaboulton** [comment]
Renamed the issue to be reflective of our long-term goal of creating better features from categoricals (see list in original issue comment for ideas). For V1, we already have support via the `DelayedFeatureTransformer`.
