### ISSUE TITLE
Limit BinaryClassificationPipeline to binary problems only.

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#2975]
Repro:
```python
from evalml.demos import load_diabetes
from evalml.pipelines import BinaryClassificationPipeline

X, y = load_diabetes()
bcp = BinaryClassificationPipeline(["Simple Imputer", "Logistic Regression Classifier"])

bcp.fit(X, y)
```
This also works with `load_wine`, a multiclass dataset.

Should this be allowed? This could introduce wild bugs with `optimize_thresholds`, and it seems like we should enforce the data to be binary for the binary pipelines.

**Comment by dsherry** [comment]
I agree its confusing for users to be able to fit/predict a binary pipeline on multiclass data!

My guess on what's happening: the model is treating class 0 as class 0 and classes 1 - n as class 1.

It would be nice if training binary pipelines with multiclass data resulted in an exception.
