### ISSUE TITLE
Determine if DefaultAlgorithm is subject to memory usage issues

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2985]
In #2976 , three estimators were filtered based on excessive memory usage.  This filtering is done in the current IterativeAlgorithm, but can be extended to the DefaultAlgorithm.  This issue tracks the testing of the DefaultAlgorithm and a refactor to publicize and refactor `_filter_estimators()` so that both algorithms can use it, as necessary.

**Comment by dsherry** [comment]
My gut tells me:
* Copy the heuristics @bchen1116 added to the old `IterativeAlgorithm` into the new `DefaultAlgorithm`
* Run perf tests
* Confirm that we're seeing the same improvement as from @bchen1116 's original work in #2982 
* Merge
