### ISSUE TITLE
Deprecate the CLI

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2993]
We've seen an example of someone uninstalling featuretools because of it's psutil dependency: https://github.com/intel-analytics/analytics-zoo/issues/3051#issuecomment-724528724

We currently also use psutil only for our cli. I wonder if we can get rid of the cli? How much value does it add? Maybe we can slim down our dependencies in doing so.

Just wanted to start the conversation!

**Comment by angela97lin** [comment]
@freddyaboulton I like this a lot! Just saw on scikit-learn that they use python to show the scikit-learn version, but something similar could be done to show all our dependencies (since our CLI is just calling python versions anyways):

```
python -m pip show scikit-learn  # to see which version and where scikit-learn is installed
python -m pip freeze  # to see all packages installed in the active virtualenv
python -c "import sklearn; sklearn.show_versions()"
```
