### ISSUE TITLE
Default Algorithm: fully split numeric and categorical columns in preprocessing split 

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#3020]
#2986 introduces a split preprocessing pipeline where categorical columns are treated in a separate chain and numeric columns in another. However, the current behavior is that categorical columns selected by the feature selector is treated by one chain and the numerical columns + non-FS selected categorical columns are treated in another. The non-FS selected categorical columns do not make it to the final estimator as the numeric chain selects the FS selected numeric columns at the end.  This issue tracks only selecting numeric columns in the numeric chain so that we do not introduce unnecessary preprocessing components in the other chain. 

The most logical solution would be to move the numeric `SelectColumns` component to the front but doing so would void the exact reasoning we introduced the split preprocessing pipeline. The main reasoning was that if we move the numeric `SelectColumns` component to the front, like the categorical preprocessing pipeline, we would select all original text/date time columns if their derivatives are chosen by the feature selector. Thus we could do the following:

1. Select numerical columns at the beginning of the numeric chain and verify performance difference in selecting original numerical columns instead of their derivatives.
2.  Add another `SelectColumns` component at the beginning of the numeric chain. However, it is currently difficult to pass parameters to  two of same components using our current pipelines API. Another approach would be to add a type exclusion component (the opposite of `SelectByType`) and exclude all categorical columns.
  

Closing criteria: 
- all categorical columns go into categorical preprocessing chain and all numeric columns go into numeric preprocessing chain

------------------------------------------------------------------------------------
Full context:

1.   We wanted to add FS to pipelines
2.   FS with select columns transformer would error out on categorical columns because it was placed last and not every “category” was passed in (https://github.com/alteryx/evalml/issues/2904)
3.   Tried re-creating the empty columns but scratched that in favor of only selecting available columns. (https://github.com/alteryx/evalml/pull/2912 and https://github.com/alteryx/evalml/pull/2944)
4.   This still left the issue of selecting a couple encoded columns but not the original column
5.   Tried to fix this by moving column selector first but ran into the issue of the column selector not selecting anything as the “selected columns” are post-encoding columns 
6.   Solution to this was to find the original columns and then move column selector to the front (https://github.com/alteryx/evalml/pull/2966)
7.   Couldn’t move selector to the front because it'll drop features created by TextFeaturizer/DateTimeFeaturizer (I think the "select the original feature if any of the sub-features are selected" should only apply to categorical. For time series problems, it probably makes sense to ignore the sub-features created by DateTimeFeaturizer that are NOT selected by FS. For example, if the data is all from the same year, you probably want to drop YEAR(date) or if HOUR(date) turns out to not be informative. By moving FS to the beginning, you'll always select date so all the sub features will always be generated)
8.   Therefore we need the split, and cannot move numeric FS to front for exact same reasoning in the previous point (https://github.com/alteryx/evalml/pull/2986)

**Comment by chukarsten** [comment]
@jeremyliweishih we might need to hash through this.  Let's talk about it at OH tomorrow (Thursday?)

**Comment by chukarsten** [comment]
@dsherry will setup a meeting

**Comment by dsherry** [comment]
Chatted with @chukarsten @jeremyliweishih 

The problem this issue tracks is that now that we have separate pathways for numeric and categorical features in our pipelines, the "numeric" branch in the current implementation has the feature selector at the end of the path instead of the beginning. This means the operations on that branch will be applied to all features, not just to numeric features, which is wasted computation.

We're getting confused why we can't just go with option 1 and have both the "select categorical" and "select numeric" feature selectors be placed at the very beginning of the pipeline. @jeremyliweishih is gonna dig up the context on this and clarify.
