### ISSUE TITLE
Parameterize test_datasets 

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#3025]
- The following file can be parameterized
  - [evalml/evalml/tests/demo_tests/test_datasets.py](https://github.com/alteryx/evalml/blob/8896cdd29e5dfd2e67820a1ffd1c89d56ddbefe4/evalml/tests/demo_tests/test_datasets.py)
- The file just runs the same unit test over and over again, with different demo datasets

**Comment by chukarsten** [comment]
@angela97lin Merry Xmas!
