### ISSUE TITLE
Require date_index for time series problems

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#3031]
## Motivation
Currently, EvalML has a `date_index` parameter for time series problems that users pass in as part of the `problem_configuration`. There is an example here in the user [guide](https://evalml.alteryx.com/en/stable/user_guide/timeseries.html#Running-AutoMLSearch). However, as you can tell from the user guide, this parameter can be None.

I think it's time we make this a required parameter:

* The time series primitives that are being added to featuretools will only be applied in dfs is there is a time index in the data. We had agreed with them about this point so that we could support both integer and date time string parameters. Although we can get away with not using a time index yet, we may as well set ourselves up for easily using the date_index in dfs. This will make it easy to use date offset strings.
* In designing the above feature, the EvalML team agreed that we should require all of our time series users to provide us with a proper date time index. 
* It will help us clean up some code in Arima and Prophet implementations that look for date values in the dataframe index when the `date_index` parameter is missing. 

If we follow through with this, it will mean that time series pipelines and components cannot operate with a `None` feature matrix. I'm personally ok with that. I think it's an awkward break with the rest of our component/pipeline api that I don't think gives us a lot of value. Plus, it's in line with point 2 above.

## How to implement this

One thing to keep in mind is that we'll want to avoid doing any feature engineering to the time index prior to the DelayedFeatureTransformer but we're going to want to do some feature engineering on it prior to the estimator.

We can do this by:
* Changing the DelayedFeatureTransformer to not operate on the time index - reasonable thing to do.
* Put the DateTimeFeaturizer prior to the estimator

### Current pipeline structure
![current_ts_pipeline.png](https://images.zenhubusercontent.com/5ef0fc259b404dbc3f292b37/8bc17b97-4ac7-4055-abc8-65c5775a439f)

### Proposed pipeline strucutre
![proposed_ts_pipeline_structure.png](https://images.zenhubusercontent.com/5ef0fc259b404dbc3f292b37/79d4619d-de88-42c6-8d01-b8cf556441fb)

For ARIMA and Prophet there will be no change to the pipeline structure.

One final thing to decide is how we'll identify the time_index.
* We can continue using a parameter denoting a column_name
* We can use the time_index semantic tag.

I think we can leave the second option for a follow-up issue.

**Comment by freddyaboulton** [comment]
One benefit of this approach is that it will also take care of #2959

**Comment by gsheni** [comment]
@freddyaboulton should this be called `time_index`? Is this similar to the `time_index` in Featuretools?
- https://featuretools.alteryx.com/en/latest/getting_started/handling_time.html#What-is-the-Time-Index?
- https://featuretools.alteryx.com/en/latest/resources/frequently_asked_questions.html?highlight=time_index#last_time_index-vs.-time_index

**Comment by freddyaboulton** [comment]
We called it `date_index` in EvalML because the first time series work predated the woodwork accessor. We can rename it to `time_index` though to make the connection clearer between the libraries!

**Comment by gsheni** [comment]
@freddyaboulton I agree, let's name it `time_index`
