### ISSUE TITLE
Access Raw Results Output is too long

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#3032]
Just reviewing the docs and found this under the AutoML User Guide:

![image](https://user-images.githubusercontent.com/64713315/141158424-be0f2270-defd-44f7-90d3-8a746e0fe7ec.png)

We should figure out a way to deal with this kind of thing.  I think a couple of options here are:

1. Modifying the cell to only show the first few keys or so of the output.
2. Modifying the output cell so that it's a scrollable window that's limited in size.

**Comment by bchen1116** [comment]
Similar issue occurs right above the cell [here](https://evalml.alteryx.com/en/stable/user_guide/data_actions.html#Addressing-all-warnings-and-errors) in the `Data Check Actions` doc
![image](https://user-images.githubusercontent.com/22552445/142261550-78ae1be7-487c-46e6-b41e-a20a8b229148.png)

**Comment by freddyaboulton** [comment]
Adding a scrollbar for long vertical output is an open issue in nbsphinx. 

It's probably better to manually truncate the output?

https://github.com/spatialaudio/nbsphinx/issues/417
