### ISSUE TITLE
Bug: force plots show incorrect feature values

### ISSUE THREAD

**Issue by peterataylor** [alteryx/evalml#3045]
The force plots features values are incorrect and actually only show the feature values from the first row of training data. This makes for incorrect interpretation of the graphic in terms of feature values. 

**Reproduction steps**

Run any force plot using `graph_force_plot` over two different rows (e.g. rows to explain) and compare the feature values shown in the force plots. The values are only showing the first row where it should show the feature values corresponding to the row being visualised/explained. 

Example notebook showing 2 rows in force plots

```
import shap
from evalml.model_understanding.force_plots import graph_force_plot
import evalml
from evalml.pipelines import BinaryClassificationPipeline
X, y = evalml.demos.load_breast_cancer()

X_train, X_holdout, y_train, y_holdout = evalml.preprocessing.split_data(X, y, problem_type='binary',
                                                                         test_size=0.2, random_seed=0)


pipeline_binary = BinaryClassificationPipeline(component_graph = {
            "Label Encoder": ["Label Encoder", "X", "y"],
            "Imputer": ["Imputer", "X", "Label Encoder.y"],
            "Random Forest Classifier": [
                "Random Forest Classifier",
                "Imputer.x",
                "Label Encoder.y",
            ],
        })
pipeline_binary.fit(X_train, y_train)

rows_to_explain = [3, 14, ] # Should be a list of integer indices of the rows to explain.

results = graph_force_plot(pipeline_binary, rows_to_explain=rows_to_explain,
                           training_data=X_holdout, y=y_holdout)

for result in results:
    for cls in result:  
        display(result[cls]["plot"])
```

You can see in the plots the two rows have the _same_ feature values, despite being different rows in the training data. 

![image](https://user-images.githubusercontent.com/1000827/141722668-0c7cbefe-67b9-4d62-ae11-e116d42293b5.png)

**Root cause**

The issue is here: https://github.com/alteryx/evalml/blob/4b4bd4e2a9b69c4b321a456c76f9dac7aa475b6e/evalml/model_understanding/force_plots.py#L35 where it takes the first row from the training data every time. 

**Proposed solution**

Create the force plots using the actual row from the training data as specified by the rows_to_explain parameter. I've got a PR that shows a potential fix: https://github.com/alteryx/evalml/pull/3044.

**Comment by freddyaboulton** [comment]
Closed by #3044
