### ISSUE TITLE
Pipeline graphs: refactor to use data generation vs viz methods

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#3073]
As discussed in #3049, [returning a JSON representation of a graph may not be the best choice moving forward](https://github.com/alteryx/evalml/pull/3049#discussion_r750585608), especially since we can't guarantee this method will always succeed. Things to consider:
- Should we return a python dictionary instead, and leave it to the user to handle JSON serialization?
- We should have a function that converts our component graph representation into one that's easy to pass to graphing libraries. Right now, that task is handled by `graph_json`. However, we use a lot of the same logic within `graph` as well. Should we refactor the `graph_json` and `graph` functions so that the latter calls the former?

**Comment by freddyaboulton** [comment]
Thanks for filing @eccabay ! My vote is yes for both!
