### ISSUE TITLE
Optimize_threshold not working as expected

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#3086]
Repro (in test file):
```python
def test_find_confusion_matrix_pipeline_threshold_tester(
    logistic_regression_binary_pipeline_class, X_y_binary
):
    bcp = logistic_regression_binary_pipeline_class({})
    X, y = X_y_binary
    y = pd.Series(y)
    bcp.fit(X, y)
    preds = bcp.predict_proba(X).iloc[:, 1]
    bcp.optimize_threshold(X, y, preds, AccuracyBinary())
    print(bcp.threshold)
    print(bcp.score(X, y, [AccuracyBinary()]))
    bcp.threshold = 0.5
    print(bcp.score(X, y, [AccuracyBinary()]))
```
Note that here, the accuracy is higher when we use a threshold of 0.5 versus the threshold we optimized with. A summary of this finding can be seen [here](https://github.com/alteryx/evalml/pull/3080). 

We see that our optimize threshold method isn't able to find this better threshold, which we can note as a performance bug. We expect that we should be able to find the 0.5 threshold as the optimal, but currently do not. This issue tracks resolving this performance discrepancy and fixing our `optimize_threshold` method.

**Comment by chukarsten** [comment]
@bchen1116 serves you right for reporting this!
