### ISSUE TITLE
Rankings: when CV is used, have "validation" score be the CV score

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#3097]
**Background**
We have two scoring columns in our automl rankings, `mean_cv_score` and `validation_score`. Currently, `mean_cv_score` is only populated if CV was run. And `validation_score` is always the validation score from the 1st training-validation split -- if CV was used this is the first CV fold, and if a training-validation split was used this is the validation split from that partitioning.

From [our automl user guide](https://evalml.alteryx.com/en/stable/user_guide/automl.html#View-Rankings):
> A summary of all the pipelines built can be returned as a pandas DataFrame which is sorted by score. The score column contains the average score across all cross-validation folds while the validation_score column is computed from the first cross-validation fold.

**Problem**
If CV was used, it is misleading to report the "validation" score as coming from only one of the CV folds. If that fold for some reason had better or worse performance than the mean, and also different performance vs the same model trained on the entire training data, we'd be giving users a pessimistic or optimistic view of model generalizability.

This came up in discussion with @rpeck this week. 

**Proposed Change**
If the data splitting strategy used is a cross-validation strategy, fill the `validation_score` column with the value from `mean_cv_score`.

Also in this case, use the value from `mean_cv_score` to compute the value for `percent_better_than_baseline`.
Users can still access detailed per-CV-fold info via the `automl.results` structure.

And if the data splitting strategy used is not a cross-validation strategy, the `mean_cv_score` column should be unpopulated. I believe this is our current behavior.

I believe all of the above can be applied for time series

**Impl notes**
I think the class hierarchy of our data splitters can be used to determine whether or not a data splitter counts as a CV splitter, e.g. `issubclass(data_splitter, OurMainCVClass)`. But I'm not sure if that will work for time series without some changes. We could change to use a mixin pattern instead of standard inheritance. We could also flatten the inheritance hierarchy completely and store metadata as class attributes set per-class, similar to how we organize our objectives and the behavior flags supported by each specific objective.

**Comment by freddyaboulton** [comment]
Companion issue for time series: https://github.com/alteryx/evalml/issues/3105

**Comment by dsherry** [comment]
Note from #3105: make sure this solution works for time series too!
