### ISSUE TITLE
Rankings: Improve validation_score for time series

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#3105]
@dsherry and I were discussing that the current behavior of `validation_score` for time series is not ideal. 

For context, with a CV splitter, AutoMLSearch will display the `validation_score` in the rankings as the score on the first CV fold.

In time series problems, this means the validation_score is computed from the oldest (and smallest) subset of data since we use rolling origin cv to compute sequential cv folds. 

We just change this to be the `mean_cv_score` or the score on the last cv fold (most recent/relevant data).

**Comment by chukarsten** [comment]
Closing this as it will be taken care of by #3097
