### ISSUE TITLE
Add `make_pipeline_from_data_check_output()` method

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#3117]
Add `make_pipeline_from_data_check_output()` method to directly take output from data check's validate method and return recommended actions

After #3116 is complete, we will no longer be able to easily take the output of data check's `validate` method to feed into `make_pipeline_from_actions`. Let's add a new method that will enable us to do so by taking the default recommended actions.

**Comment by chukarsten** [comment]
Can we return to #3072 when this is done?  We dev backlogged the issue and don't want to forget it.
