### ISSUE TITLE
Default algorithm: remove `pipeline_params` parameter and move functionality into `custom_hyperparameters`

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#3153]
In #3149, there's [a discussion](https://github.com/alteryx/evalml/pull/3149#discussion_r768846634) noticing divergent behavior around pipeline parameters in `DefaultAlgorithm` and `IterativeAlgorithm`. Currently the implementation is as follows for the two algorithms: 

- Default: pipeline parameters are [passed down to every pipeline of every batch](https://github.com/alteryx/evalml/blob/main/evalml/automl/automl_algorithm/default_algorithm.py#L419-L421)
- Iterative: pipeline parameters are [passed down only on the initial batch](https://github.com/alteryx/evalml/blob/main/evalml/automl/automl_algorithm/iterative_algorithm.py#L427-L429)

Closing criteria of this issue should be as follows:

1. Determine whether pipeline parameters should be passed only on the first batch or for every batch
2. If pipeline parameters should be passed only on the first batch - fix `DefaultAlgorithm` to do so
3. If pipeline parameters should be passed to every batch - fix `IterativeAlgorithm` to do so

This may just be a fundamental misunderstanding on my part when I implemented `DefaultAlgorithm` but happy to discuss further in this issue.  Tagging @ParthivNaresh and @freddyaboulton here!

---------------------------------------------------------------------------------------------
Edit Jan 13th 2022:
After discussion we've decided to do the following:

1. Remove `pipeline_params` as a parameter of `DefaultAlgorithm`
2. Add functionality so that if a user wants to statically define a parameter for a component they can do so by specifying a single parameter for a hyperparameter. For example: `{'Random Forest Regressor: {"n_estimators": [10]}}`.

This was decided to minimize the confusion of having two parameters (`pipeline_params` and `custom_hyperparameters`) do similar things in different stages of the algorithm. For example, in `IterativeAlgorithm`, `pipeline_params` would function in the first batch but `custom_hyperparameters` would take over the same functionality afterwards. 

An added note of complexity is detailed [here](https://github.com/alteryx/evalml/pull/2317/files#r644079909) where we noticed that our tuner would error out if we passed values to the tuner that was not defined in the hyperparameter ranges for the tuner.

Another open question: should we do the same with `IterativeAlgorithm`?

**Comment by jeremyliweishih** [comment]
@chukarsten @dsherry filed as a bug since implementation of one algorithm will have to change depending on what we decide for pipeline parameters.

**Comment by chukarsten** [comment]
@jeremyliweishih I moved this into the first sprint of the new year.  Hopefully that's not too far away for a discussion.  Let's take an action to schedule a discussion sometime during the sprint to see what the ramifications might be.  I think we've touched a little on this already in....
