### ISSUE TITLE
Error in automl.search()

### ISSUE THREAD

**Issue by AhmedEwis** [alteryx/evalml#3154]
Hello All,
I am getting the below error in the last step (version 0.39.0)
 All pipelines in the current AutoML batch produced a score of np.nan on the primary objective <evalml.objectives.standard_metrics.R2 object at 0x7fb46d99eb50>.
My data has no nans, and it is a regression problem.
X_train:
![image](https://user-images.githubusercontent.com/65680238/146183675-e28625a6-98d2-461e-af6c-829534ec9734.png)
y_train:
![image](https://user-images.githubusercontent.com/65680238/146183725-169ade9f-9b25-4436-9976-808c7fbb4157.png)
The measurementdatetime is just an index

**Comment by AhmedEwis** [comment]
#Update:
I have managed to solve the issue by making the following:
set the output y to: 
After:
y = df['O3']  --> series (Accepted)
Before:
y = df[['O3']]  --> Dataframe (error)

**Comment by angela97lin** [comment]
@AhmedEwis Thanks for posting your update! That sounds about right: we expect a `pd.DataFrame` object for our `X` input and a `pd.Series` object for our `y` input.

Closing since it seems like you've resolved your issue, but feel free to create a new issue (or reopen) for followup!
