### ISSUE TITLE
Time Series: Sample data to a regular frequency

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#3165]
We know that our time series pipelines require data with a regular frequency so that we can correctly specify the values of `gap`, `max_delay`, `forecast_horizon` and build features from these parameters.

Naturally, we need to ask how to handle irregularly spaced data. One thing we can try is sampling to a regular frequency in a component.

https://github.com/dataiku/dss-plugin-timeseries-forecast/blob/main/python-lib/timeseries_preparation/preparation.py

**Comment by dsherry** [comment]
Love it. Moving to icebox pending further time series discussions
