### ISSUE TITLE
[Discuss] Should we move towards a config/dict-based model for Auto(*) parameters?

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#319]
Per discussion in the guard rails design doc, @dsherry made this comment:

"seeing that AutoBase code snippet for adding the boolean arg made me think... there's so many params, perhaps passing around a configuration dict makes more sense?"

Could be useful discussing pros/cons for this approach but out of scope for guardrails so tracking it here :)

**Comment by dsherry** [comment]
@angela97lin ok if I close this? I'm always down to discuss this further, but at this point the way we handle component and pipeline parameters feels pretty good to me in general.
