### ISSUE TITLE
NaturalLanguageDataCheck should raise an error for highly null columns and a warning for columns with nulls

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#3240]
As a user of `NaturalLanguageDataCheck`, I would like for this data check to
- Raise a `DataCheckError` if a natural language column has more NaNs than a given threshold
- Rase a `DataCheckWarning` if a natural language column has NaNs but is below the given threshold

This is basically changing the `NaturalLanguageDataCheck` to behave like the `NullDataCheck` (formerly `HighlyNullDataCheck`)
#### Code Example

```python
X = pd.DataFrame({"some_null": ["Natural Language", None, "Is great"],
                                  "highly_null": ["I am happy", None, None]})
data_check = NaturalLanguageNaNDataCheck(pct_null_col_threshold=0.5)
validation = data_check.validate(X)
```

Closing Criteria:
- DataCheckWarning for `some_null`
- DataCheckError for `highly_null`
- Recommended action of dropping `highly_null`

**Comment by angela97lin** [comment]
Amazing, thank you for filling me in and filing this @freddyaboulton!

Just a heads up that https://github.com/alteryx/evalml/pull/3197 is currently just merged into my separate branch but will hopefully be merged in soon via https://github.com/alteryx/evalml/pull/3182, after one more PR 🤞

**Comment by freddyaboulton** [comment]
If we go with my approach for how to handle this in #3242 ([comment](https://github.com/alteryx/evalml/issues/3242#issuecomment-1015555642)) then this would be handled by `NullDataCheck` and we would get rid of `NaturalLanguageNaNDataCheck`

**Comment by angela97lin** [comment]
@chukarsten `NullDataCheck` supports that in this branch: https://github.com/alteryx/evalml/pull/3182/, but I assigned myself to this issue and can close it out when everything is merged.
