### ISSUE TITLE
``PerColumnImputer`` fails if the input dataframe has datetime columns

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#3241]
``PerColumnImputer`` fails if the input dataframe has datetime columns.

I think similar to our `Imputer`, we should allow datetime columns to be part of the input, even if we take no actions on them.

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
from evalml.demos import load_fraud
from evalml.pipelines.components import PerColumnImputer

X, y = load_fraud(n_rows=1500)
X.head()

pci = PerColumnImputer()
pci.fit(X, y)
```

gives us this stack trace:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-7f4dae7e2db2> in <module>
      1 pci = PerColumnImputer()
----> 2 pci.fit(X, y)

~/Desktop/evalml/evalml/utils/base_meta.py in _set_fit(self, X, y)
     17         @wraps(method)
     18         def _set_fit(self, X, y=None):
---> 19             return_value = method(self, X, y)
     20             self._is_fitted = True
     21             return return_value

~/Desktop/evalml/evalml/pipelines/components/transformers/imputers/per_column_imputer.py in fit(self, X, y)
     89 
     90         for column, imputer in self.imputers.items():
---> 91             imputer.fit(X.ww[[column]])
     92 
     93         return self

~/Desktop/evalml/evalml/utils/base_meta.py in _set_fit(self, X, y)
     17         @wraps(method)
     18         def _set_fit(self, X, y=None):
---> 19             return_value = method(self, X, y)
     20             self._is_fitted = True
     21             return return_value

~/Desktop/evalml/evalml/pipelines/components/transformers/imputers/simple_imputer.py in fit(self, X, y)
     64             X = X.astype("category")
     65 
---> 66         self._component_obj.fit(X, y)
     67         return self
     68 

~/Desktop/evalml_venv/lib/python3.7/site-packages/sklearn/impute/_base.py in fit(self, X, y)
    317             Fitted estimator.
    318         """
--> 319         X = self._validate_input(X, in_fit=True)
    320 
    321         # default fill_value is 0 for numerical input and "missing_value"

~/Desktop/evalml_venv/lib/python3.7/site-packages/sklearn/impute/_base.py in _validate_input(self, X, in_fit)
    295                 "categorical data represented either as an array "
    296                 "with integer dtype or an array of string values "
--> 297                 "with an object dtype.".format(X.dtype)
    298             )
    299 

ValueError: SimpleImputer does not support data with dtype datetime64[ns]. Please provide either a numeric array (with a floating point or integer dtype) or categorical data represented either as an array with integer dtype or an array of string values with an object dtype.
```

**Comment by freddyaboulton** [comment]
@angela97lin I think the problem is the `impute_all=tTrue` default parameter. This works

```python
from evalml.demos import load_fraud
from evalml.pipelines.components import PerColumnImputer

X, y = load_fraud(n_rows=1500)
X.head()
pci = PerColumnImputer(impute_all=False,
                                           impute_strategies={"amount": {"impute_strategy": "mean"}})
pci.fit(X, y)
```

> we should allow datetime columns to be part of the input, even if we take no actions on them.

I think that's already the case so I think we should instead get rid of the `impute_all` parameter. `impute_all=True` is what the Imputer does. I think the intention of this component is to handle imputation on specific columns with varying strategies for each column?

**Comment by chukarsten** [comment]
@freddyaboulton has a good solution.  Acceptance criteria for this one will be to get rid of `impute_all` to make this a true PerColumnImputer, which should get rid of the exception.  We will need to file a separate issue to make sure that date time columns using fill-forward or fill-backward strategies .

**Comment by angela97lin** [comment]
@eccabay @freddyaboulton @chukarsten The reason why `impute_all` was added was because we want to be able to impute specific columns (for example, via the data checks) without needing to impute all of the columns. It was set to `True` because that's the default behavior, but in the case of data checks we want that parameter to be False.

**Comment by eccabay** [comment]
@angela97lin Thank you for bringing this up! You raise a very good point, which I overlooked on my first look at this issue. 

IMO, with the way that our code base has evolved, having `impute_all` (and especially having it default to `True`) doesn't make as much sense any more. As you mention, having it set to `True` was the default/original behavior, but there's nowhere in the code base that relies on this behavior. On the other hand, we now have the data checks providing usage for `impute_all=False`, or therefore removing the parameter altogether. Keeping this behavior for the sake of history doesn't make much sense to me.

Of course, removing this parameter doesn't provide a true solution for the underlying problem of being unable to impute `DateTime` columns, but I agree with @chukarsten that that should be tackled by a separate issue. For now, removing the `impute_all` parameter provides a short-term solution to things that are currently breaking, and has the added benefit of potentially mitigating the same problem with other future data types as well.

**Comment by freddyaboulton** [comment]
@angela97lin thanks for explaining the context behind `impute_all`! 

> Alternatively, maybe what we should discuss is what the PerColumnImputer should do when a column is not specified: should it impute it anyways, or should it not?

I think @eccabay and I think it should only impute the columns specified in the `impute_strategies` dict. The old behavior of using `default_impute_strategy='most_frequent'` on columns that are not specified is what the `Imputer` does when `numeric_impute_strategy='most_frequent'`, `categorical_impute_strategy='most_frequent'`. I don't think we need two components that do the same thing.

Let us know what you think!

**Comment by eccabay** [comment]
From discussion in office hours today, we will be moving forward with removing the `impute_all` parameter.
