### ISSUE TITLE
NullDataCheck vs DateTimeNaNDataCheck and NaturalLanguageNaNDataCheck

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#3242]
Right now, we have a general ``HighlyNullDataCheck`` (soon to be ``NullDataCheck``) in addition to  ``DateTimeNaNDataCheck`` and ``NaturalLanguageNaNDataCheck``.

Do we need all of these?

From our tests, it seems like we expect NullDataCheck to handle natural language and datetime features (see, for example, ``evalml/tests/data_checks_tests/test_data_checks.py::test_default_data_checks_classification``). Is this the assumption we want to make, and then remove the other data checks?

Note that this is related to https://github.com/alteryx/evalml/issues/3241 and https://github.com/alteryx/evalml/pull/3237 because if we want to use a ``PerColumnImputer`` component, it will need to support all of these other data types too.

**Comment by freddyaboulton** [comment]
Posting my comment in #3237 about how I think we should handle this:

> My thought is that if we allow NaturalLanguage & DateTime in this check and update the action for those columns to only be "drop column" if they are highly null, then we can close out #3240 and #3242 with minimal changes to what you have here.


Note this means we don't need to update `PerColumnImputer` since we won't impute those kinds of features and it means we can delete `NaturalLanguageNaN` and `DateTimeNaN` data checks.
