### ISSUE TITLE
Improve documentation for validate_holdout_datasets

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#3270]
After #3208 the helper `validate_holdout_datasets` is only used in `test_gen_utils.py`. Let's delete it unless there's a justifiable reason to keep it. If we do keep it, let's improve the docstring since its currently vague: "Validate the holdout datasets match our expectations."

**Comment by freddyaboulton** [comment]
Our users use this function for time series problems. So let's not delete it and instead improve the docstring and maybe add it to the time series user guide.

**Comment by dsherry** [comment]
@freddyaboulton @ParthivNaresh 👍 SGTM!
