### ISSUE TITLE
Invalid target data check (time series regression), apply interpolation for small chunks of missing target values

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#3317]
**Feature request**
For TS reg with a target missing a few values, we should be able to recommend a target interpolator component to fill in those values. This issue tracks making that happen.

**Suggested behavior**
* Define two types of TS reg targets: those with zero or some missing values, and those with "too many"
    * One idea on how to define "too many": define a threshold on a) number of consecutive missing and b) overall percentage missing
    * Note we have similar logic in place already in our TS data checks for inputted features. Ideally we should use the same logic for both
* For TS reg targets with some missing values, raise a data check error saying the target has missing values, and recommend interpolation to fill in the missing values as the action
* For TS reg targets with "many" missing valaues, raise a data check error saying the target has too many missing values to get good modeling results with, and suggesting the user truncate their data to remove the regions which have missing values.

**Comment by rpeck** [comment]
This came up in this dataset from Alan:

`s3://collected-datasets/misc/San_Fran_Airport_Time_Series/SF_Airport_USW00023234_pycarat_combined_99_1_reformatted_dates.csv`

I have also put it in `collected-datasets`, so it's on JupyterHub.

- Two days (out of 40 years) are completely missing
- Of days that are present, 20 rows have missing values for the weather data, including `Tmax(F)`, which is the primary target
