### ISSUE TITLE
Update `NullDataCheck` so that natural language columns with nan values (but are not highly null) suggest dropping rows rather than imputation

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#3320]
https://github.com/alteryx/evalml/pull/3260 removed `DateTimeNaNDataCheck` and `NaturalLanguageNaNDataCheck`, which didn't have any actions associated with the errors. However, now that datetime and natural language columns are lumped into `NullDataCheck`. We still do not have any actions associated with these two types of columns.

For natural language columns, this isn't desireable--we probably don't want to take the most frequent value and impute the nan rows with it. Hence, for these columns, we should suggest a separate action to take: dropping nan rows.

This issue tracks updating `NullDataCheck` so that when natural language columns with nan values (but are not highly null) suggest dropping rows rather than imputation (the current action).

**Comment by freddyaboulton** [comment]
Thanks for filing! I agree with the proposed change. But minor nit-pick: The current recommended action for null natural language / datetime is "no action".

![image](https://user-images.githubusercontent.com/41651716/153476351-bc6d99b7-9adc-4ccb-82ce-2eebfa806815.png)

**Comment by angela97lin** [comment]
@freddyaboulton Oops thanks for the catch! Updated 😁
