### ISSUE TITLE
NoVarianceDataCheck should allow the target to be optional

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#3337]
#### Code Sample, a copy-pastable example to reproduce your bug.

```python
from evalml.demos import load_diabetes
from evalml.data_checks import NoVarianceDataCheck
import pytest

X, _ = load_diabetes()

with pytest.raises(AttributeError, match="'NoneType' object has no attribute 'ww'"):
    NoVarianceDataCheck().validate(X, None)
```

Calculating whether a column is "no variance" does not depend on a target variable being defined. This is a break from out DataChecks api of having a default value of `None` for the target variable.

**Comment by gsheni** [comment]
test
