### ISSUE TITLE
 AutoMLSearchException: All pipelines in the current AutoML batch produced a score of np.nan on the primary objective 

### ISSUE THREAD

**Issue by AhmedEwis** [alteryx/evalml#3390]
Hello all,

After installing EVALML in colab, I have only followed the example of the breast cancer.

import evalml
X, y = evalml.demos.load_breast_cancer()
X_train, X_test, y_train, y_test = evalml.preprocessing.split_data(X, y, problem_type='binary')
from evalml.automl import AutoMLSearch
automl = AutoMLSearch(X_train=X_train, y_train=y_train, problem_type='binary')
automl.search()

But unfortunately, it gives the below error:
 AutoMLSearchException: All pipelines in the current AutoML batch produced a score of np.nan on the primary objective

**Comment by freddyaboulton** [comment]
Hi @AhmedEwis ! Thank you for filing. Can you please post AutoMLSearch's console output ? That way we'll have more information to diagnose what happened. You can also run AutoMLSearch with `verbose=True` so that more information is displayed.

**Comment by AhmedEwis** [comment]
> Hi @AhmedEwis ! Thank you for filing. Can you please post AutoMLSearch's console output ? That way we'll have more information to diagnose what happened. You can also run AutoMLSearch with `verbose=True` so that more information is displayed.

Hi @freddyaboulton Thanks for your reply!
I got this warning from the console output:
/usr/local/lib/python3.7/dist-packages/traitlets/traitlets.py:2205: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '172.28.0.2' instead of '"172.28.0.2"' if you require traitlets >=5.

**Comment by AhmedEwis** [comment]
> Hi @AhmedEwis ! Thank you for filing. Can you please post AutoMLSearch's console output ? That way we'll have more information to diagnose what happened. You can also run AutoMLSearch with `verbose=True` so that more information is displayed.

I also set the verbose = True. I only found that the below output:

**Comment by freddyaboulton** [comment]
Hi @AhmedEwis ! Can you post a screenshot? I don't think it shows up correctly in your previous comment.

**Comment by chukarsten** [comment]
@AhmedEwis , going to close this one. If you still need help, feel free to reopen and post the requested screenshot!
