### ISSUE TITLE
Graphs not appearing in documentation

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#3447]
[Link here](https://evalml.alteryx.com/en/v0.48.0/user_guide/model_understanding.html#Permutation-Importance)

Scrolling around the model understanding documentation, the graph cells do not appear in the docs. The graphs appear fine for v0.47.0, but disappear as of v0.48.0.

**Comment by freddyaboulton** [comment]
🤦‍♂️  

Could it be related to this? https://github.com/alteryx/evalml/issues/1692
