### ISSUE TITLE
Implement an option to prevent feature generation on time index column for time series problems

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/evalml#3590]
If a user has previously used Featuretools to generate feature values for a time series problem, including features created from the time index column (year, month, day, etc), EvalML should provide a mechanism to prevent additional datetime features from being generated by the `DatetimeFeaturizer` component.

Since the time index is required as part of the data input, if EvalML uses this time index to create new features, there can be duplication of features, with the some of the same features generated by both Featuretools and EvalML. There should be some mechanism for users to instruct EvalML to skip generating new features on datetime columns in this scenario.

**Comment by gsheni** [comment]
@chukarsten @jeremyliweishih How large of a lift would this be? Would it be possible to get it in next sprint?

@asniyaz FYI
