### ISSUE TITLE
Undo Skipping of Tests for Python 3.9 

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#3600]
In [PR #3133](https://github.com/alteryx/evalml/pull/3133), we marked tests to skip if the environment was a Python 3.9 environment.  I don't think all the tests that are being skipped need to be skipped anymore.  In working through the PolynomialDetrender tests, it was noted that Python 3.9 environments were skipping these tests, probably due to sktime not being compatible with that version of Python at the time. 

We should: 

1. Search for `pytest.mark.skip_if_39` in the evalml codebase
2. Generate an EvalML environment with Python 3.9.
3. Attempt to run any testing modules using this pytest mark.
4. Remove the mark from modules that are now successful with Python 3.9.
5. Generate some feedback as for any modules that still don't support Python 3.9.

**Comment by 9gl** [comment]
Hey @chukarsten , I would like to work on this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some of the resources to get started, as I'm new to this.

**Comment by chukarsten** [comment]
Sorry @9gl , our intern was super high speed and knocked it out!

**Comment by 9gl** [comment]
No worries

**Comment by chukarsten** [comment]
@9gl there's a new good first issue if you want to try : #3621
