### ISSUE TITLE
Conditionally include the imputer in pipelines

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#3603]
Right now, we add the imputer to every pipeline that includes datatypes that the imputer supports. However, the imputer is only useful when there is missing data for the component to impute. On first sight this doesn't seem to be a huge issue, but recent profiling has highlighted this as a performance issue. Consider this snakeviz profile, where the input data has no missing values:
![Screen Shot 2022-07-07 at 11 39 25 AM](https://user-images.githubusercontent.com/60074782/177814632-7648bc19-c924-496e-ab69-50c4a7c0ff5d.png)
Here, despite having no need for the imputer, the one component takes up a full quarter of the time it takes to call predict on the pipeline.

It is possible that there may be null values in the holdout data, which `make_pipeline` doesn't see, in which case we may want the imputer regardless. We should discuss this, but my initial thought is that it's too much of an edge case for us to take the performance hit for.

**Comment by chukarsten** [comment]
Thanks for filing this...this is extremely interesting.  Which block here is the imputer?  The magenta one toward the middle?

**Comment by eccabay** [comment]
@chukarsten yup, that bright magenta, next to the `estimator.py:80(predict)`. The details are on the side, annoyingly the screenshot removed my mouse hovering over that section.
