### ISSUE TITLE
Refactor test_components.py

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#3621]
As an EvalML dev, I would like the unit tests to be refactored so that they are parameterized with `pytest.mark.parameterize` vs. a for-loop within the test so that I can more easily identify and debug issues.

The current `test_components.py` looks like this : 
```
def test_components_init_kwargs():
    for component_class in all_components():
        component = component_class()
        if component._component_obj is None:
            continue
        if isinstance(component, StackedEnsembleBase):
            continue
```

Instances where the for-loop iterates over the components should be done like this:

```
@pytest.mark.parametrize("component_class", all_components())
def test_components_init_kwargs(component_class):
      component = component_class()
      if component._component_obj is None:
          continue
      if isinstance(component, StackedEnsembleBase):
          continue
```

As a bonus, if `pytest.mark.xfail` can be applied for the `if..continue..` cases, that would be bonus points.

**Comment by harshvardhanb25** [comment]
Hi @chukarsten! I would like to try fixing this issue since I am a first-timer.

**Comment by chukarsten** [comment]
Go get it @harshvardhanb25 !

**Comment by harshvardhanb25** [comment]
@chukarsten using pytest.mark.xfail increases the number of cases that show up as ignored. Is this the expected outcome?

**Comment by harshvardhanb25** [comment]
I have updated all tests as specified except for one with a loop that looks like `for component_class in all_components() + [test_estimator_needs_fitting_false]:` may I issue a PR if this is not something to be fixed?

**Comment by harshvardhanb25** [comment]
I have opened the above PR. Please let me know if anything is out of order, this is my first contribution to a project.
