### ISSUE TITLE
Text data support

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#367]
We'll need transformers for building features from text. Preprocessing ideas: removing invalid characters, html tags, remove stopwords. Feature engineering: [TF-IDF](https://en.wikipedia.org/wiki/Tf%E2%80%93idf), n-grams, lsa/svd.

Questions:
* What third-party libs can we use to support all this other than [sklearn](https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html)?
* Does featuretools support working with text data? (@kmax12 @rwedge)

**Comment by dsherry** [comment]
Status: still blocked on my PR for the `nlp_primitives` packaging. I plan to push to have that wrapped that up this week.

**Comment by dsherry** [comment]
We merged [the packaging change](https://github.com/FeatureLabs/nlp_primitives/pull/31). Just need to merge [one more PR needed for featuretools](https://github.com/FeatureLabs/nlp_primitives/pull/35) (no change expected to evalml), and we can do the `nlp_primitives` release and get this in!

@eccabay now that the downloads have been removed from `nlp_primitives`, could you please rerun the perf tests using the latest from the `nlp_primitives` `master` branch? Once we have those results, and we like the way they look, all we'll be blocked on is the `nlp_primitives` release, and merging the automl PR!

**Remaining steps**
* Get fresh perf test results, review.
* Do `nlp_primitives` release.
* Approve and merge automl PR -- should expect latest version of `nlp_primitives`

@rwedge FYI

**Comment by tyler3991** [comment]
All issues in this epic are completed, closing.
