### ISSUE TITLE
Installing fresh env, make installdeps-dev, and running single test file wouldn't work until make test was run

### ISSUE THREAD

**Issue by tamargrey** [alteryx/evalml#3711]
Not sure if this is reproducible or was just a weird state I got myself into, but after creating a new virtualenv on python 3.8.2 and following contributing.md (running `make installdeps-dev` and then `brew install libomp`), running a direct pytest command on a single file (ex `pytest '/Users/tamar.grey/repositories/evalml/evalml/tests/component_tests/test_target_encoder.py'`) resulted in 

```
ImportError while loading conftest '/Users/tamar.grey/repositories/evalml/evalml/tests/conftest.py'.
evalml/__init__.py:6: in <module>
    import sklearn
E   ModuleNotFoundError: No module named 'sklearn'
```

I then ran `make test`, and the tests ran. After deactivating and reactivating my env, running the pytest command on a single file worked. 

I'm not sure what was going on with the env, but, if this is reproducible, it might be worth investigating and understanding what's going on there.

**Comment by gsheni** [comment]
This might be env specific. `make installdeps-dev` should do `pip install -e .[dev]` which should install core reqs + dev reqs
