### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Mcd6** [alteryx/evalml#3839]
Why do I import eval report this error?
![image](https://user-images.githubusercontent.com/87841835/202140827-5654ba3b-72aa-4ed4-ac4d-732eb198d825.png)
I located the relevant local files and found this code on github.
 
![image](https://user-images.githubusercontent.com/87841835/202141255-ae14279c-f080-4ccc-8ca4-ea2af1c3b618.png)
![image](https://user-images.githubusercontent.com/87841835/202141312-7d0163ca-3a53-4bdd-b210-6ff9c1eb62ab.png)

Then I went to github of featuretools to find primitives files, and found that there were no such files as DiversityScore.
![image](https://user-images.githubusercontent.com/87841835/202141536-d06b9119-1cb6-4c7f-8342-5d91bd3a27fb.png)

So is there something wrong with my evalml installation or something else?
My system is Windows 10.

I hope good people can help me.

**Comment by thehomebrewnerd** [comment]
@Mcd6 This likely has to do with the versions of `featuretools` and `nlp-primitives` you have installed. Please make sure that you have the most recent versions of both of those packages installed. If the error persists after upgrading, please let us know what versions of `evalml`, `featuretools` and `nlp-primitives` you have installed so we can try to reproduce.

**Comment by thehomebrewnerd** [comment]
@Mcd6 I thought about this a little more, and I think the issue might be slightly different than I originally thought. If you are using `conda` to install your packages, you might also try to use Woodwork version 0.19.0 instead of version 0.20.0 by running `conda install woodwork==0.19.0` in your environment.

**Comment by Mcd6** [comment]
> @Mcd6 I thought about this a little more, and I think the issue might be slightly different than I originally thought. If you are using `conda` to install your packages, you might also try to use Woodwork version 0.19.0 instead of version 0.20.0 by running `conda install woodwork==0.19.0` in your environment.


Thank you for your answer and directions. I upgraded to the latest evalml and found that it did solve the import error even though there were some warnings.Thank you again.

**Comment by HrBiuz** [comment]
pls how did you upgrade it?

**Comment by Mcd6** [comment]
> pls how did you upgrade it?

emm, I use pip and just pip install evalml --upgrade.

**Comment by HrBiuz** [comment]
still not working.....

**Comment by Mcd6** [comment]
> i ran the code you suggested on my PC (Anaconda and Deepnote ) idle. it's not working infact I'm another error

I ran the demo and found no bugs.

**Comment by HrBiuz** [comment]
After upgrading evalml i still into same bug or error
![error1](https://user-images.githubusercontent.com/53976220/202341076-cbb665f2-faa0-48e6-af7a-5d02a0737a4f.png)
![error2](https://user-images.githubusercontent.com/53976220/202341086-6ecdca8e-c0c6-4cbb-929b-2c49af00d09f.png)

**Comment by Mcd6** [comment]
> After upgrading evalml i still into same bug or error ![error1](https://user-images.githubusercontent.com/53976220/202341076-cbb665f2-faa0-48e6-af7a-5d02a0737a4f.png) ![error2](https://user-images.githubusercontent.com/53976220/202341086-6ecdca8e-c0c6-4cbb-929b-2c49af00d09f.png)

Go back with automl.errors, I'm not sure why.

**Comment by thehomebrewnerd** [comment]
@Mcd6 Now that you are able to run the demo successfully, I am going to close this issue. Feel free to reopen or create a new issue if you have additional problems.
