### ISSUE TITLE
Pin ipywidgets under 8.0.5

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#4098]
ipywidgets 8.0.5 added [this change](https://github.com/jupyter-widgets/ipywidgets/pull/3533), which led to [these errors](https://github.com/alteryx/evalml/actions/runs/4481256266/jobs/7877697500?pr=4094) in our tests with regards to building our search iteration plots.

**Comment by bollwyvl** [comment]
A quick fix might be (e.g. in `conftest.py`):

```py
from ipykernel.ipkernel import _create_comm
```
