### ISSUE TITLE
"allowed families" argument ignores LightGBM

### ISSUE THREAD

**Issue by ismorphism** [alteryx/evalml#4259]
Hello everyone! Unfortunately when I use `allowed_model_families`  in the `AutoMLSearch` class, it is absolutely ignored and other models like Random Forest are used. I want to use only LightGBM  and it is really annoying to see other models during the search. Also there is funny difference between `allowed_model_families`  and `excluded_model_families`. First one uses `str` data type as an element of a list which goes into the argument, and latter one uses only `ModelFamily` instances. What's the reason behind this difference? 

#### The command I use to run

```python
automl = AutoMLSearch(
    X_train=X_train,
    y_train=y_train,
    data_splitter=cv,
    problem_type="binary",
    objective='f1',
    additional_objectives=["auc", "precision"],
    allowed_model_families=["lightgbm"],
    max_batches=3,
    optimize_thresholds=True,
    verbose=True,
)

automl.search()

```
![image](https://github.com/alteryx/evalml/assets/13585987/aa66128c-7c5a-4c80-a60a-0269af118404)

As you can see Random Forest are used somehow, but I do not need it. Only LightGBM. Thanks in advance.

**Comment by eccabay** [comment]
Hi @ismorphism, thanks for filing. This is certainly a documentation failure on our part. The `allowed_model_families` argument only effects searches run with the `IterativeAlgorithm`, rather than our default `DefaultAlgorithm`. To limit to LightGBM, I would recommend this code instead:
```
automl = AutoMLSearch(
    X_train=X_train,
    y_train=y_train,
    data_splitter=cv,
    problem_type="binary",
    objective='f1',
    additional_objectives=["auc", "precision"],
    allowed_model_families=["lightgbm"],
    automl_algorithm="iterative",
    max_batches=3,
    optimize_thresholds=True,
    verbose=True,
)
```
We will update the documentation to include this.
