### ISSUE TITLE
Improve CatBoost Pipeline

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#447]
Currently for CatBoost pipelines we only allow `most_frequent` to be used with `Simple Imputer` because CatBoost natively handles categorical data and we need the imputer to as well. Should we keep this pipeline structure and this behavior. Or should we rethink this and remove the comment associated within the pipelines?

**Comment by angela97lin** [comment]
Closing, since I believe this was addressed by our change from `SimpleImputer` to `Imputer`.
