### ISSUE TITLE
Validate component and pipeline fields at class definition

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#561]
As #360 gets merged and more custom functionality gets added to automl users will be defining more and more pipelines. I think it is best that pipeline structure, pipeline components, and problem types are validated on definition as they errors would only surface on instantiation. If users are using pipelines with automl these errors would surface during model search which is confusing.  

Likewise, currently pipeline and component required fields are check on instantiation (as part of an ABC) instead of checked on definition.

I've done some brainstorming in the branch ` js_test_decorators` where I explored using a class decorator to check for required fields (this can be extended to check the fields themselves). We can use this solution to also enable properties we need for these classes such as returning copies of class variables.

**Comment by dsherry** [comment]
Incomplete list of some things we could validate on components at definition-time:
* supported_problem_types
* hyperparameter_ranges: ensure that each range contains the default from `default_parameters` (@bchen1116 and I discussed this on #767 )

Incomplete list of some things we could validate on pipelines at definition-time:
* component_graph: ensure all entries are valid components. After pipelines as DAGs (#273 ), check for cycles etc.
* custom_hyperparameters: same as for components
