### ISSUE TITLE
Create Featuretools Entityset to EvalML Walkthrough 

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#566]
- We should create a page in the documentation that walks guide of using Featuretools with EvalML. It will show users how EvalML fits into the ML space/pipeline. 
- This should be jupyter notebook and go in the docs. 
- The notebook should have no output, and be rendered when the docs are built

**Comment by dsherry** [comment]
We have examples at https://www.featuretools.com/demos/. Will file new issues for specific things,
