### ISSUE TITLE
Re-enable binary classification threshold tuning by default

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#648]
We added this feature on the #346 feature branch, then backed it out in #606 because it was recomputing `predict` and slowing down automl.

We should re-enable this by default. In order to do so, we'd have to cache the prediction output, which is currently computed in score. The long-term solution is to memoize predictions with a cache (#466), but short-term we should be able to do something.

This also relates to #579, which tracks cleaning up the duplicate code between the pipeline classes' `score` methods.

**Comment by dsherry** [comment]
@freddyaboulton you're not working on this, right? Can @jeremyliweishih take it?

**Comment by freddyaboulton** [comment]
@jeremyliweishih @dsherry Please take it! The initial analysis showed that simply enabling tuning doesn't improve scores. Using a different data splitting strategy might help!

**Comment by jeremyliweishih** [comment]
Moving back to Dev Backlog and will follow through with this after more data splitting work.

**Comment by jeremyliweishih** [comment]
Moving back to Dev Backlog and will follow through with this after more data splitting work.

**Comment by dsherry** [comment]
@bchen1116 and I discussed, and we feel this is necessary for #973
