### ISSUE TITLE
Ability to freeze specific hyperparameters

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#767]
**Description**
There are cases where we'll want to fix certain pipeline parameters to a predetermined value, thus excluding them from the search.

Today, in order to do this, we'd have to define a new pipeline subclass which updates `custom_hyperparameters` to set only one allowed value for the parameters being held constant. Then we'd have to exclude the original pipeline from automl and add the new subclass to automl. This should work fine but feels heavy-handed and hard to use.

**Options**
* Don't do anything; the way to do this is described above
* Same but add a convenience method to wrap the above
* A better way to support this would be to allow users to specify which parameters they want to freeze as an input to the automl search. We wouldn't need to create any subclasses or re-register any pipelines with automl. Instead, we could upgrade our use of the `Tuner` class to be able to exclude the specified parameters from the search space.

**Proposal**
The last option feels more sustainable. What would go into that:
* Add a `pipelines_freeze_parameters` parameter (name TBD) to `AutoSearchBase.__init__`. This could accept a map with partial parameters dicts for each pipeline:
```
{
    'Logistic Regression Pipeline': {
        'Simple Imputer': {
            'imputation_strategy': 'constant',
            'fill_value': 42
        }
    },
    ... # could include params from other pipelines
}
```
* When `AutoSearchBase` creates the tuners for each pipeline during init, it will pass that pipeline's frozen parameter dict to the tuner class
* Update `Tuner` to have an optional init arg `freeze_parameters`. If specified, when the tuner creates the search space, it will exclude the frozen parameters from the space. But when the tuner proposes a new set of parameters to evaluate, the proposal will include the frozen value(s).

**Comment by dsherry** [comment]
Discussed with @bchen1116 

Here's what we'd be asking users to run (i.e. add this to the automl search user guide, RE custom hyperparameters)
```python
# define custom hyperparameters for one or more parameters, for one or more components
# this supports both a) setting params to a const value and b) defining a new range for certain parameters
custom_hyperparameters = {                                                                                                                                                                                                                        
    'Imputer': {
        'imputation_strategy': ['constant', 'mean'],                                                                                                                                                                                                  
        'fill_value': 42
    }                                                                                                                                                                                                                                         }
# get a list of estimators supported for this problem type
estimators = get_estimators('binary')
# for each estimator, construct a pipeline, and assuming there's an impute step, override the hyperparameters for the imputer
pipelines_with_custom_hyperparameters = [make_pipeline(X, y, estimator, 'binary', custom_hyperparameters) for estimator in estimators]
# provide the constructed pipelines to automl, and run search
automl = AutoMLSearch(problem_type='binary', allowed_pipelines=pipelines_with_custom_hyperparameters)
automl.search(X, y)
```

Open question we still need to resolve: what validation, if any, do we do in the automl algo code? Example: custom hyperparams exclude "mean" strategy for imputer, but that's our default value, so automl 1st batch would run with that.

**Comment by dsherry** [comment]
**Edge case**
User defines value(s) which weren't the default. So 1st automl batch will try to use the old defaults instead of using the custom value.

**Options**
1. Do no validation. Batch 1 of automl uses component defaults, regardless of what hyperparams are provided. Document this behavior.
    1a. Same as above, but also add the default for each parameter to the hyperparameter range, on top of what users specified.
2. Validation: if a parameter default is not in the custom hyperparameter range for a particular parameter, raise an error.
3. Add logic which overrides the defaults with the new value from the custom hyperparameters.
    * But what happens if a range was specified for a parameter, instead of a single value? We'd either have to choose a random value from the range, or ask users to also provide a new default alongside each hyperparameter range.

Disadvantage of 1 is that batch 1 of automl ignores what the user has provided. Also we can't do this because the tuner won't accept recommendation for a parameter not in the space.

Option 2 is the simplest. 

Should we define an API to override default values?

**Conclusion**
* Let's go with option 2: add validation that if a parameter's default value in the component is not in the custom hyperparameter range for a particular parameter, raise an error.
* RE defining API to override default values, let's punt on that for the time being.

**Comment by bchen1116** [comment]
Rather than validating if the parameter default is in the hyperparameter range during instantiation, we decided to simply catch the error that AutoMLSearch throws if the default isn't within the provided range values, and instead use [this issue](https://github.com/alteryx/evalml/issues/561) to later track the args provided for hyperparameter range definition
