### ISSUE TITLE
Add a data check to validate problem type

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#818]
@kmax12 just raised this in the channel.

Idea: add a `ProblemTypeDataCheck` (first attempt at a name) which would check that the target matches the problem type. I.e. if the problem type is binary classification, the target should contain two distinct values, error if there's more than two and warn if there's only one.

We should give some thought to the implementation strategy. Do we define one data check class which accepts problem type as input? Do we define a different `DataChecks` collection for each problem type? My hope is that we can find a way to pass the `problem_type` into `DefaultDataChecks`, but if not we may need to define different collections for binary/multi/regression. This may be a better strategy long-term anyways since some checks can be problem-type-specific.

@angela97lin FYI

**Comment by freddyaboulton** [comment]
After [discussing](https://github.com/alteryx/evalml/pull/1167#discussion_r494643747) on #1167 , we decided to close this issue and file an issue for enhancing the `InvalidTargetDataCheck` to do specific checks for multiclass and regression problems.
