### ISSUE TITLE
Pipelines: run data checks on fit data

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#968]
As a user of evalml *who is training pipelines outside of automl*, I would like pipelines to catch any data errors before I call `fit`.

I think this can be accomplished by letting `PipelineBase` accept a list of `DataCheck`s on `__init__`. It would be cool if pipelines returned by `AutoMLSearch.get_pipeline` already have data checks passed in to them. This would also make sure all our validation logic lives in the same place, which would be easy to maintain.

**Comment by dsherry** [comment]
@freddyaboulton is this still relevant?

**Comment by ParthivNaresh** [comment]
Based on our conversation in OH, is this issue still relevant or does a broader discussion on the philosophy/intention of Data Checks need to take place?

**Comment by freddyaboulton** [comment]
@ParthivNaresh I think we can close it out! We'll only throw exceptions for egregious problems (which is a subset of what our data checks catch) which is incompatible with this feature request. I think there's a challenge in making sure there isn't a lot of code duplication between data checks and pipeline code but that's not suited for this issue.
