### ISSUE TITLE
Add mocking to `test_all_estimators_check_fit`, `test_all_transformers_check_fit` and `test_no_fitting_required_components`

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#990]
In #969 we added three tests that iterate through all components and then test if predicting or transforming before fitting raises an error. Then we fit these components and check if predicting or transforming does not raise an error. This issue tracks mocking the fit/predict/transform methods to lower runtime.

**Comment by angela97lin** [comment]
@dsherry @jeremyliweishih 
Locally just tried running each test 5 times:

- `test_all_estimators_check_fit` took 6-7s
- `test_all_transformers_check_fit` took 4-5s
- `test_no_fitting_required_components` took 2-3s

Way under 30 seconds, so closing for now. We can always revisit if by adding more components this grows too much!

**Comment by dsherry** [comment]
Ooh @angela97lin thanks for circling back on this! SGTM
